### ISSUE TITLE
Donation method?

### ISSUE THREAD

**Issue by twzkxkan** [M66B/NetGuard#11]
Thank you for your dev work, this is exactly what I was looking for! Is there any way I can support your efforts?

**Comment by pylerSM** [comment]
http://www.xprivacy.eu/

Via Paypal, Bitcoin etc.

**Comment by M66B** [comment]
I will add in-app donations.

**Comment by twzkxkan** [comment]
>I will add in-app donations.

What about users who don't have Google Play services installed?

**Comment by M66B** [comment]
They can use Bitcoin / Paypal / bank transfer.

**Comment by M66B** [comment]
You can donate now from within the application (check the about dialog, version 0.10 or later required) or via this website:http://www.netguard.me/
