### ISSUE TITLE
Settings screen title

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#119]
Should be **<- Settings** using the translated text, `android:title="@string/menu_settings"` or so.

**Comment by M66B** [comment]
I am not sure what you mean.
menu_settings is localized (translatable)

**Comment by licaon-kter** [comment]
When you enter settings on the upper left side it says **<- NetGuard**, while I would like it to say **<- Settings** (localised)

**Comment by M66B** [comment]
Thanks for the suggestion!

I checked and for example the Play store does the same.
