### ISSUE TITLE
Ask if sure to disable

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#122]
_"Are you sure you want to disable NetGuard? All the apps that ask for internet permissions will be able to access the internet unrestricted as they see fit"_ 
checkbox "Never ask again"
Yes/No

**Comment by M66B** [comment]
IMHO this is not really needed, because we can assume the users knows what NetGuard is for and knows what will happen when the switch is set to off.

**Comment by M66B** [comment]
The UI design goal is to have as little as possible UI elements.

**Comment by licaon-kter** [comment]
Ok

**Comment by M66B** [comment]
Nevertheless your suggestions are appreciated.
