### ISSUE TITLE
NetGuard does not detect "Disable VPN" on Xperia 5.1.1

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#126]
Touching the VPN notification via https://github.com/M66B/NetGuard/issues/125 will either:
* (on Samsung A5 5.0.2) disable VPN in system and NetGuard registers as being toggled OFF
* (on Xperia 5.1.1) disable VPN in system but NetGuard registers as still being toggled ON; toggling it OFF and then ON again triggers the [explain the need for VPN](https://github.com/M66B/NetGuard/commit/c9196eb75a63cb7cac408846a006eb76b1df8564) screen and the Android dialog to allow a new VPN.

Steps:
* open NetGuard toggle is OFF
* turn NetGuard toggle to ON (VPN key appears)
* close NetGuard in task manager (VPN key stays)
* pull down quick settings, click on `Network may be monitored`, disable VPN  (VPN key disappears) 
* open NetGuard toggle is still ON
* turn NetGuard toggle to OFF
* turn NetGuard toggle to ON and your are advised to agree with VPN, OK, allow VPN, OK

Logcat after these steps: https://gist.github.com/licaon-kter/254ed65b789a140b6848

**Comment by M66B** [comment]
"*close NetGuard in task manager (VPN key stays)*"

You'll be warned that data may be lost.

**Comment by licaon-kter** [comment]
Umm, what do you mean?

It was not needed to close it, and it should not matter since the service stays, right?

**Comment by M66B** [comment]
Closing with the task manager will kill the application and may result in side effects, like not saving data/state.

**Comment by M66B** [comment]
Anyway, NetGuard handles all messages, signals and intent, so there is little that can be done to fix this behavior.

**Comment by licaon-kter** [comment]
Ok, I get it now, if not closed it will register the disable event ok.
Sorry for that.

**Comment by M66B** [comment]
No problem, your remarks are always welcome.
