### ISSUE TITLE
Add a settings button with "Disable notification"

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#128]
In which you show a dialog and explain explain:
> You can disable the notification by:
> * Long click the NetGuard notification
> * Tap the 'i' icon
> * Depending on your screen, either uncheck "Show notification" or toggle "Block"

Should help with the store ratings and such.

**Comment by M66B** [comment]
I think by having changed the notification to low (minimum) priority there is less need for this.
There were no more complaints fortunately.
