### ISSUE TITLE
App list w/ collapsable categories

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#145]
While the search is nice, scrolling through hundred of apps is no fun.

My idea, sort apps by status and make each (status) category colapsible ( I guess with [this](https://developer.android.com/reference/android/app/ExpandableListActivity.html) )

Mockup:
```
Allowed apps (10) (collapsed)
Blocked apps that have internet (124) (expanded)
* aapp
* bapp
* capp
Apps disabled or w/o internet permission (65) (collapsed)
```

Some notes:
* default is Allowed expanded
* If no allowed then it's Blocked apps expanded
* only one expanded category at a time
* fancy animations optional

Yeah yeah it's easier to throw ideas here than to code them. :)

**Comment by M66B** [comment]
I don't think this will help finding an application faster, on the contrary. What would help is fast scroll, but unfortunately this is not supported for the RecyclerViiew (I looked into this recently).

**Comment by licaon-kter** [comment]
FastScroll like in RecyclerView?

https://github.com/danoz73/RecyclerViewFastScroller
or

**Comment by M66B** [comment]
I want to stick to what Android has to offer, unless there are very good reasons not to, like for Picasso. Third party libraries often stop support at some time too soon and tend to break with new Android versions.

IMHO the search function is enough.

**Comment by okungnyo** [comment]
NetGuard uses Picasso?

**Comment by M66B** [comment]
See the attribution section of the read me.
It is something different than you might think.

**Comment by licaon-kter** [comment]
Those are more ProofOfConcept than libraries, given then age and support. You'd end up integrating and supporting them.

Although this would be nice, it's not essential.

**Comment by okungnyo** [comment]
But there aren't any images in NetGuard??

**Comment by M66B** [comment]
The application icons are images ...

**Comment by okungnyo** [comment]
Oh, I was going off the project website and was thinking of an image album.
