### ISSUE TITLE
Add a FAQ menu option

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#161]
I find it useful to have it above Support, just a plain view with the FAQ info from here.

Otherwise If you have a question/problem you go through
`menu -> Support -> XDA -> scroll to FAQ -> GitHub -> press Read whole README -> scroll to FAQ`
or
`Play store -> Show more -> scroll to links -> link to XDA (it's the first link, it will be pressed) -> scroll to FAQ -> GitHub -> press Read whole README -> scroll to FAQ`
compared with
`menu -> FAQ`

Yes, translations optional. :)

**Comment by M66B** [comment]
The problem with this is that there is no way I know of to force display the desktop version of a GitHub page, which is needed to make this work on a mobile device (people will not understand that they need to request the desktop page).

**Comment by licaon-kter** [comment]
No, include the text in the app.

**Comment by M66B** [comment]
Then I have to maintain it in two places, which I don't want to do.

**Comment by licaon-kter** [comment]
Well yeah, I know. :-|

https://github.com/falnatsheh/MarkdownView/network or https://github.com/Uncodin/bypass so it's straight forward and you don't need to convert first.

**Comment by M66B** [comment]
Test version: http://www.netguard.me/NetGuard-v0.34-faq.apk

**Comment by licaon-kter** [comment]
Nice.
