### ISSUE TITLE
Add a reset button

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#167]
In settings, after import/export, "Are you sure?Yay/Nay", only resets apps allowed/blocked status respecting the global toggles.
I know you can do it in `Settings->Apps->NetGuard->ClearData` but that's rather far away.

**Comment by M66B** [comment]
I am not sure what you mean.
Importing settings  resets all existing settings.

**Comment by licaon-kter** [comment]
By "after" I mean placed below import/export in the settings window.

**Comment by M66B** [comment]
I don't see users do often this and since I want to keep NetGuard as simple as possible, I don't want to add this.
