### ISSUE TITLE
Blocking all traffic on Asus ZenPad S 8 Z580CA

### ISSUE THREAD

**Issue by dajanusz** [M66B/NetGuard#168]
Hello,
as the titel says, its blocking all traffic on my Asus ZenPad S8 Z580CA.

I guess there are two possibilies:
1. either all ZenUI roms are affected by the VPN problem,
2. or its just all intel-based devices, as the ZenFone 2 and 4 are intel-based as well.

i know its not your fault, but maybe you can update the compatibility section.
keep on your amazing work!

**Comment by M66B** [comment]
It is not a CPU architecture problem.

I don't know which ROMs have this problem.

The Zenfones are already mentioned in the compatibility section, am I missing something?

**Comment by dajanusz** [comment]
ok, then just add the ZenPad S8 (Z580CA) to the incompatibility section.

**Comment by licaon-kter** [comment]
@dajanusz: Software version? Android version?

**Comment by M66B** [comment]
@dajanusz please send me the debug info: tap seven times on the about dialog title or background.

**Comment by dajanusz** [comment]
NetGuard: 0.36/36 
Android: 5.0 (SDK 21) 

Brand: asus 
Manufacturer: asus 
Model: P01MA 
Product: WW_P01M 
Device: P01M_3 
Host: mec7 
Display: LRX21V.WW_P01M-V4.3.2-20151030 
Id: LRX21V 
Fingerprint: true 
VPN dialogs: true 
Interactive: true 
WiFi: true 
Metered: false 
Network: WIFI/ CONNECTED 
Network: VPN/ CONNECTED 
Setting: initialized=true 
Setting: whitelist_wifi=false 
Setting: whitelist_other=false 
Setting: version=36 
Setting: whitelist_roaming=true 
Setting: dark_theme=false 
Setting: unused=false 
Setting: use_metered=false 
Setting: enabled=true 
Setting: manage_system=false

**Comment by M66B** [comment]
@dajanusz you are using NetGuard on this device, so it is working?

**Comment by dajanusz** [comment]
no it's not, i have to deactivate NetGuard before i can send the mail ...
i just resend the debug info with the logcat.txt

**Comment by dajanusz** [comment]
hm, this time the netlog looks very different

**Comment by M66B** [comment]
So, compatible or not?

**Comment by dajanusz** [comment]
no
