### ISSUE TITLE
Question about Hotspot

### ISSUE THREAD

**Issue by infabo** [M66B/NetGuard#175]
Hi!

Seems like when I setup a wifi Hotspot on my netguard enabled Smartphone, my tablet does not obtain an IP address if netguard is enabled in my Smartphone.

Is this a known issue or just a malconfiguration?

Thx
Ingo

**Comment by M66B** [comment]
This was reported/asked before in issue #42

**Comment by M66B** [comment]
See also this FAQ:
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ22
