### ISSUE TITLE
About gray background for unchanged rules 

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#177]
While I like the idea of grouping them visibly ( ahem https://github.com/M66B/NetGuard/issues/145 ) it find the current implementation underwelming:

![light](https://i.imgur.com/HIpiZ1j.png)

![dark](https://i.imgur.com/Xda6aSh.png)

I find it "unfinished'' or "dirty" somehow. :)

**Comment by M66B** [comment]
Thanks for your opinion.

Do you have a better suggestion to distinguish changed and non changed items?

**Comment by licaon-kter** [comment]
Not yet, I'll try to look around at other apps.

**Comment by M66B** [comment]
It looks the same on my device.

**Comment by licaon-kter** [comment]
First thing, those that are grey look "lighter" to me, look "higher" (on elevation), so I'd rather have the *changed rules* with this "grey highlight".

Second, keeping the different color, I'd rather have each app a bit separated, not sure your list type can be modified, but with a [*Full-bleed divider*](https://www.google.com/design/spec/components/dividers.html#dividers-types-of-dividers) between elements/apps.

Third, don't use colors, use [*Subheaders and dividers*](https://www.google.com/design/spec/components/dividers.html#dividers-types-of-dividers) between Changed /Controlled and Unchanged.

**Comment by M66B** [comment]
The RecyclerView is efficient and easy to use, but difficult to customize, so I don't want to do this.

I will think about reversing the grayish to the changed items.

**Comment by licaon-kter** [comment]
Oh, BTW, when scrolling the list does not go under the title bar/nav barbut under the **margin** that's below the title bar/above the nav bar. That's not very Material Design like, right? :P

**Comment by M66B** [comment]
The margins are Google's default.

**Comment by M66B** [comment]
Actually that is not completely true, since I have reduced the default of 16dp for small devices (not tablet) to 8dp.

**Comment by licaon-kter** [comment]
Default for this view type?

**Comment by M66B** [comment]
Default for any activity.

**Comment by licaon-kter** [comment]
I wanted it to be like [this](https://i.imgur.com/1BxkIkx.jpg), and I thought that's the default:
* image on left, see how the icon (list item) slides up under the title bar?
* image on roght, see how the icon (list item) slides up from under the nav bar?

**Comment by M66B** [comment]
Okay

**Comment by licaon-kter** [comment]
Also, as the greenish(!?) selected item in the right image shows, no left/right margins either!

**Comment by M66B** [comment]
Test version: http://netguard.me/NetGuard-v0.42-release-margins.apk

**Comment by licaon-kter** [comment]
Yep, pretty nice.
