### ISSUE TITLE
Tour / setup wizard

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#178]
While the [colouring thing](https://github.com/M66B/NetGuard/issues/177) is nice, a new user will not see any difference so unless it enters settings s/he does not know what the icons colours means *(cyan is allowed/dark red is blocked/icons have the diagonal line or not)*.

I actually got a bit confused myself given the app was **"block all by default"** in the older versions and now it's the other way around and I was expecting a different behaviour.

A warning on top might help those who **"block all"** in settings and then wonder why nothing can connect.

The warning text could be positioned where the *"netguard is disabled please use..."* text resides.

**Comment by M66B** [comment]
Isn't this less of an issue now, because all is allowed for new users?

**Comment by M66B** [comment]
I think the best what can be done is adding a tour through the application.

**Comment by licaon-kter** [comment]
Can you quantify if users expect "whitelist" or "blacklist" behaviour?

My take, I guess one would not like to end up without any connection ( aka all blocked), but that forces the user to actually use the app.

Comparing the workflow with 250 apps.

*Allow all* by default:
* install app
* enable
* all allowed means app does nothing ( it does not **guard** anything )
* (user sees warning that all are allowed)
* user blocks an app
* user draws the conclusion that s/he needs to block 245 more apps
* user uninstalls app

or (if not that average user)

* uses Settings (which most don't, right?) to block all
* user allows 5 apps
* user happy

*Block all* by default:
* install app
* enable
* all blocked
* (user sees warning that all are blocked)
* user allows 5 apps
* user happy

PS: I'm not a *UI interaction designer*, I just play one on the internet.
PS2: Did I just turn this to "Bring back block all by default" ? :)

**Comment by okungnyo** [comment]
Wait, block all by default is gone now?

**Comment by licaon-kter** [comment]
@okungnyo: Yep for a while now, you won't notice it if only upgrading.

**Comment by M66B** [comment]
We agree it depends on the type of user. The tour could help here to select white it black list mode in the process.

There were too much complaints in the Play store when everything was blocked by default. People seem not to expect this and I can imagine this. Just installing an application should not alter the behavior of the system on such a scale. This should be a user choice, hence why I think a tour or wizard is s good idea.

A tour has given the limited number of users (about 10K currently) not a high priority though.

**Comment by licaon-kter** [comment]
Yes a tour or a question on first run solves this.

**Comment by okungnyo** [comment]
A tour would be lovely.

Even just simple startup screen that says "All apps have Internet access. Tap the green Wi-Fi and cellular icons to individually block Internet access for those apps. Orange means they are blocked." or something along those lines would be more than enough, no?

**Comment by M66B** [comment]
I like to do the things thorough, so the icons/colors and rule conditions should be explained and there should be a few switches to change the defaults right away (white/black list at least).

**Comment by okungnyo** [comment]
Sounds great, how soon can we expect to see all that?

**Comment by M66B** [comment]
@okungnyo https://github.com/M66B/NetGuard/issues/178#issuecomment-159544648

**Comment by okungnyo** [comment]
??

**Comment by licaon-kter** [comment]
@okungnyo He said: "**A tour has given the limited number of users (about 10K currently) not a high priority though.**"

**Comment by M66B** [comment]
"*A tour has given the limited number of users (about 10K currently) not a high priority though.*"

Of course you are free to contribute this yourself, it is an open source project after all.

**Comment by licaon-kter** [comment]
Inspiration: http://www.android-app-patterns.com/category/tutorials

Can I vote for a "Allow all / Block all" end of tour option?

**Comment by M66B** [comment]
Start on boot, which is enabled when you shutdown your device with Netguard enabled, should be mentioned as well.

**Comment by M66B** [comment]
Although I don't like using third party libraries, because it often appeared that I support my software longer than the third parties are supported, this library seems to be nice:
https://github.com/worker8/TourGuide

**Comment by licaon-kter** [comment]
Can you even control "Start on boot" apps without root? I have [this](http://repo.xposed.info/module/de.defim.apk.bootmanager) for that.

**Comment by licaon-kter** [comment]
Another lib: github.com/PaoloRotolo/AppIntro
