### ISSUE TITLE
Firewall leak

### ISSUE THREAD

**Issue by coombez** [M66B/NetGuard#179]
I've been testing out netguard for a couple of days.  Thanks for putting it together! I've been looking for exactly this!

Last night I turned off WiFi and noticed that Google maps was able to use cellular data even thought I have that blocked.  I then tested another blocked application and it too could access cellular data.  I had previously confirmed that netguard successfully blocked these.

I'm not sure how netguard entered this state but disabling and re-enabling put it back into working order.  I'll update this issue if I'm able to observe when it might enter this state.

In case it matters I'm on nexus 6p marshmallow.

**Comment by M66B** [comment]
Which version of NetGuard are you using?

Did you read this FAQ?
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ21

Please send me the logcat describing the problem when this occurs again, without reproducing the problem or a logcat with the problem it is difficult to fix something.

**Comment by M66B** [comment]
Please send me a logcat now as well, maybe I can discover something: tap seven times on the title or background of 'about'.

**Comment by coombez** [comment]
Sent two logcat's although I don't think it worked as expected.  Version 0.36. I have read and understood the FAQ.

**Comment by M66B** [comment]
Please upgrade to the latest beta, since I have added some code to handle doze mode (as far as possible, because Google does limit this severely and for good reasons, because Google don't want applications to keep the device awake, unless absolutely necessary).

All releases:
https://github.com/M66B/NetGuard/releases

If you prefer you can received beta released through the Play store:
https://play.google.com/apps/testing/eu.faircode.netguard

**Comment by M66B** [comment]
Ow, and send me a Nexus 6P and I will extensively test this.
(just joking a being a little bit jealous of your device, since I have "just" a Nexus 5 only ;-) )

**Comment by coombez** [comment]
Heh, your jealousy is completely driven by my dropping my nexus 4 and cracking it! Don't worry, you'll drop your nexus 5 eventually and then leapfrog me to an even better phone! ;)

I will switch to the beta in the play store.  Hopefully the logcat will work if I experience the issue there.

I'll update with my findings.

**Comment by M66B** [comment]
While implementing and testing a new feature inspired by this issue, I discovered the root cause for this bug. Please update to version 0.43:
https://github.com/M66B/NetGuard/releases/tag/0.43

**Comment by coombez** [comment]
Sweet! So happy I could do my tiny little part in helping you build this awesome app!  About how long does it typically take until your releases hit the play store beta?

**Comment by M66B** [comment]
Mostly about two hours (which is in my opinion far too long).

**Comment by coombez** [comment]
Meh, it is what it is.

Thanks for the fix and the app!

After I confirm it's fixed I'll send you a logcat to make sure that works properly too.

**Comment by M66B** [comment]
You can always directly download here:
https://github.com/M66B/NetGuard/releases

(just enable "Unknown source" in the Android "Security" to allow side loading apps)

The releases are exactly the same as in the Play store, so you will still get updates from the Play store.
