### ISSUE TITLE
BusyBox applications are blocked when running as root

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#180]
Steps:
* disable NetGuard
* allow terminal emulator in NetGuard 
* start terminal emulator
* su
* ssh/ping *somehost*
* switch to NetGuard
* enable NetGuard
* switch back to the terminal to see it stuck

Or try [cSploit](https://github.com/cSploit/android), it can see hosts but it can't do anything else like scanning since it uses BusyBox as root.

**Comment by M66B** [comment]
Sorry, but root is not supported.
NetGuard is a no-root solution.

You could try to allow 'android', but I don't think that will be enough, since there are processes running with uid 0 having no package name and so cannot be allowed internet access (the VPN service API doesn't support this).

**Comment by licaon-kter** [comment]
All allow does not help. :(

**Comment by M66B** [comment]
All allow does route nothing into the VPN sinkhole, so there is little that can be done.
Does it work when you turn NetGuard off with the switch?

**Comment by licaon-kter** [comment]
Yes.

Just posted this here for posterity, and maybe to throw ideas at it/you.
Maybe I'll add a FAQ# pointing here.

**Comment by licaon-kter** [comment]
#283 did not fix this per se, since this issue is before `filtering` was implemented and currently apps that run as `root` when `filter off` still get blocked.

From a terminal:
* `ping google` -> OK
* `su`
* `ping google` -> BLOCKED

```
I NetGuard.JNI: get uid v4 p1 10.1.10.1/2
D NetGuard.JNI: Packet v4 10.1.10.1/2 > googleip/2 proto 1 flags  uid 0
W NetGuard.JNI: Address v4 p1 googleip/2 syn 0 not allowed
D NetGuard.JNI: Loop thread af3f9000
D NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 1 sdk 22
D NetGuard.JNI: pselect ready 1
```

Or other:
```
I NetGuard.JNI: get uid v4 p17 10.1.10.1/49957
D NetGuard.JNI: Packet v4 10.1.10.1/49957 > someip/port proto 17 flags  uid 0
I NetGuard.JNI: UDP blocked session from 10.1.10.1/49957 to someip/port
W NetGuard.JNI: Address v4 p17 someip/port syn 0 not allowed
D NetGuard.JNI: Loop thread af3fa000
D NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 1 sdk 22
D NetGuard.JNI: pselect ready 1
D NetGuard.JNI: Packet v4 10.1.10.1/49957 > someip/port proto 17 flags  uid -1
I NetGuard.JNI: UDP ignore session from 10.1.10.1/49957 to someip/port state 3
D NetGuard.JNI: Loop thread af3fa000
D NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 1 sdk 22
D NetGuard.JNI: pselect ready 1
D NetGuard.JNI: Packet v4 10.1.10.1/49957 > someip/port proto 17 flags  uid -1
I NetGuard.JNI: UDP ignore session from 10.1.10.1/49957 to someip/port state 3
D NetGuard.JNI: Loop thread af3fa000
D NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 1 sdk 22
D NetGuard.JNI: pselect ready 1
```

Process `root` is allowed. Interesting to note that the first packet is from `uid 0` and gets `blocked` while the other two are from `uid -1` and they get `ignored`. Always 3 of these.

I do also get the notification that `Process root attempted to access these addresses`.

**Comment by M66B** [comment]
When not in filtering mode, there is no way to tell Android not to route root traffic into the VPN, because root has no package name.

What you can try is not to add DNS servers to the VPN when not in filtering mode, to prevent DNS from being routed into the VPN. This requires a source code change/experiment.

0=root
-1=uid could not be determined


licaon-kter <notifications@github.com> schreef op 17 maart 2016 01:50:28 CET:

**Comment by licaon-kter** [comment]
Umm, yes back to the missing package name thing.

Regarding the VPN creation, it's like that already, sytem logcat says: vpn created w/o DNS, oh you have no DNS? setting VPN DNS as 8.8.8.8. :-/

**Comment by M66B** [comment]
So, change the code to experiment without DNS servers set is the logical step.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 08:59:03 CET:

**Comment by licaon-kter** [comment]
Not sure I follow, I see this:
```
E ConnectivityService: Attempting to register duplicate agent for type 17: NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]}  network{515}  lp{{InterfaceName: tun0 LinkAddresses: [10.1.10.1/32,fd00:1:fd00:1:fd00:1:fd00:1/128,]  Routes: [0.0.0.0/2 -> 0.0.0.0 tun0,64.0.0.0/3 -> 0.0.0.0 tun0,96.0.0.0/4 -> 0.0.0.0 tun0,112.0.0.0/5 -> 0.0.0.0 tun0,120.0.0.0/6 -> 0.0.0.0 tun0,124.0.0.0/7 -> 0.0.0.0 tun0,126.0.0.0/8 -> 0.0.0.0 tun0,128.0.0.0/2 -> 0.0.0.0 tun0,192.0.0.0/9 -> 0.0.0.0 tun0,192.128.0.0/11 -> 0.0.0.0 tun0,192.160.0.0/13 -> 0.0.0.0 tun0,192.168.0.0/19 -> 0.0.0.0 tun0,192.168.32.0/21 -> 0.0.0.0 tun0,192.168.40.0/23 -> 0.0.0.0 tun0,192.168.44.0/22 -> 0.0.0.0 tun0,192.168.48.0/20 -> 0.0.0.0 tun0,192.168.64.0/18 -> 0.0.0.0 tun0,192.168.128.0/17 -> 0.0.0.0 tun0,192.169.0.0/16 -> 0.0.0.0 tun0,192.170.0.0/15 -> 0.0.0.0 tun0,192.172.0.0/14 -> 0.0.0.0 tun0,192.176.0.0/12 -> 0.0.0.0 tun0,192.192.0.0/10 -> 0.0.0.0 tun0,193.0.0.0/8 -> 0.0.0.0 tun0,194.0.0.0/7 -> 0.0.0.0 tun0,196.0.0.0/6 -> 0.0.0.0 tun0,200.0.0.0/5 -> 0.0.0.0 tun0,208.0.0.0/4 -> 0.0.0.0 tun0,224.0.0.0/4 -> 0.0.0.0 tun0,240.0.0.0/4 -> 0.0.0.0 tun0,::/0 -> :: tun0,] DnsAddresses: [] Domains:  MTU: 0}}  nc{[ Transports: VPN Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED]}  Score{0}  everValidated{true}  lastValidated{true}  created{true}  explicitlySelected{false} }
D ConnectivityService: registerNetworkAgent NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true, isConnectedToProvisioningNetwork: false]}  network{null}  lp{{InterfaceName: tun1 LinkAddresses: [10.1.10.1/32,fd00:1:fd00:1:fd00:1:fd00:1/128,]  Routes: [0.0.0.0/2 -> 0.0.0.0 tun1,64.0.0.0/3 -> 0.0.0.0 tun1,96.0.0.0/4 -> 0.0.0.0 tun1,112.0.0.0/5 -> 0.0.0.0 tun1,120.0.0.0/6 -> 0.0.0.0 tun1,124.0.0.0/7 -> 0.0.0.0 tun1,126.0.0.0/8 -> 0.0.0.0 tun1,128.0.0.0/2 -> 0.0.0.0 tun1,192.0.0.0/9 -> 0.0.0.0 tun1,192.128.0.0/11 -> 0.0.0.0 tun1,192.160.0.0/13 -> 0.0.0.0 tun1,192.168.0.0/19 -> 0.0.0.0 tun1,192.168.32.0/21 -> 0.0.0.0 tun1,192.168.40.0/23 -> 0.0.0.0 tun1,192.168.44.0/22 -> 0.0.0.0 tun1,192.168.48.0/20 -> 0.0.0.0 tun1,192.168.64.0/18 -> 0.0.0.0 tun1,192.168.128.0/17 -> 0.0.0.0 tun1,192.169.0.0/16 -> 0.0.0.0 tun1,192.170.0.0/15 -> 0.0.0.0 tun1,192.172.0.0/14 -> 0.0.0.0 tun1,192.176.0.0/12 -> 0.0.0.0 tun1,192.192.0.0/10 -> 0.0.0.0 tun1,193.0.0.0/8 -> 0.0.0.0 tun1,194.0.0.0/7 -> 0.0.0.0 tun1,196.0.0.0/6 -> 0.0.0.0 tun1,200.0.0.0/5 -> 0.0.0.0 tun1,208.0.0.0/4 -> 0.0.0.0 tun1,224.0.0.0/4 -> 0.0.0.0 tun1,240.0.0.0/4 -> 0.0.0.0 tun1,::/0 -> :: tun1,] DnsAddresses: [] Domains:  MTU: 0}}  nc{[ Transports: VPN Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED]}  Score{0}  everValidated{false}  lastValidated{false}  created{false}  explicitlySelected{false} }
E ConnectivityService: no dns provided for netId 516, so using defaults
D ConnectivityService: Setting Dns servers for network 516 to [/8.8.8.8]
```

I did not think `ConnectivityService` is this under NetGuard's control?!

**Comment by M66B** [comment]
The Android connectivity service manages the Android VPN service.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 12:21:49 CET:

**Comment by licaon-kter** [comment]
So, as far as my understanding goes, although the app creates a DNSless VPN, Android will add one anyway. Did I get this right?

**Comment by M66B** [comment]
Yes, it seems that is what happening.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 12:41:04 CET:
