### ISSUE TITLE
Widget Not Working

### ISSUE THREAD

**Issue by malitech** [M66B/NetGuard#181]
Sometimes the widget toggle doesn't work. Nothing happens when I tap on it. It starts working again for sometime when I open netguard app manually.

**Comment by M66B** [comment]
Which device/Android version are you using?
Which NetGuard version are you using?
Is there are particular state when the widget doesn't work (on or off or maybe after a reboot) ?

Please send a logcat after this happened again and detail what you did, so I can check this against the stuff in the logcat.

**Comment by malitech** [comment]
Hello!

I'm using a nexus 5 with lollipop 5.1.1 and latest netguard 0.44

I add the widget first. I tap on it and the firewall gets disabled. When I tap again, Google feedback window appears. When I close the window and tap on the widget again, nothing happens. When I add the widget again, it shows the off state (white and black). I have attached a screenshot. When I tap on the newly added netguard widget, it works as expected but after sometime without touching it, the behaviour repeats.

Here's the screenshot:
http://m.imgur.com/XxQhx43

Another fix is, if I open the netguard app and manually turn on the firewall, the widget starts to toggle. If I don't touch it for sometime, behaviour repeats.

When the feedback window opened, I sent it. I don't know if you received it. It contained information about a power manage java and wakelock...

I've also sent a logcat.

Do I have to clear netguard data or something? Or is there really an issue?

Thanks a lot.

**Comment by M66B** [comment]
"* ... Google feedback window appears ...*", please send it, referencing this issue, so I can see what is going wrong.

**Comment by M66B** [comment]
Logcat for reference:

```
NetGuard: 0.44/44
Android: 5.1.1 (SDK 22)

Brand: google
Manufacturer: LGE
Model: Nexus 5
Product: hammerhead
Device: hammerhead
Host: kpfi14.cbf.corp.google.com
Display: LMY48M
Id: LMY48M
Fingerprint: true
VPN dialogs: true
Interactive: true
WiFi: true
Metered: false
Network: WIFI/ CONNECTED
Setting: initialized=true
Setting: whitelist_wifi=true
Setting: whitelist_other=true
Setting: dark_theme=false
Setting: enabled=false
Setting: screen_other=false
Setting: manage_system=true
Setting: imported=true
Setting: version=44
Setting: whitelist_roaming=true
Setting: use_metered=false
Setting: screen_wifi=false
```

**Comment by M66B** [comment]
@malitech can you please try this version:
http://netguard.me/NetGuard-v0.44-20151127-release.apk

Please send the feedback if it pops up again.

**Comment by licaon-kter** [comment]
Using this version, tapping 7 times:
* I'm offered a dialog to directly save logcat.txt
* and a dialog to *share* it, I guess, the thing is that selecting ES Explorer to save the file somewhere **now** fails with a toast *Operation unsupported* (not sure who is sending the toast though).

**Comment by M66B** [comment]
You should get a dialog to *store* logcat.txt.
ES Explorer seems not to support the storage framework.

**Comment by licaon-kter** [comment]
Yes, I guess.

**Comment by malitech** [comment]
Hello, I just installed the version you sent. The bug seems to have been gone for now. No feedback popup. I'll test to see if it's stable now. Thanks a lot.

Also, where does the google feedback go? Did you get it when I sent last time? :)

**Comment by M66B** [comment]
Great it seems to work now!
Please keep an eye on this and let me know if something unusual happens.

The feedback should go to the Play store developer console, but I didn't see it appear that.

Please send me a logcat after you see a crash or feedback by tapping seven times in the title of the about dialog.

**Comment by malitech** [comment]
Ah well.

Certainly sir. :)

**Comment by malitech** [comment]
Hey, I just sent a google feedback. This happened again. But this time the widget toggle didn't stop working but still I got this feedback screen.

**Comment by M66B** [comment]
I received the feeback, but it contains very little information.
Please send a logcat as well.

**Comment by malitech** [comment]
I did too. :)

**Comment by M66B** [comment]
I received it, and it appeared Android stopped the NetGuard service in a not so nice way (assuming there was no crash). This results in the service wakelock being under-locked, which is being worked around in this version: http://netguard.me/NetGuard-v0.44-2015112703-release.apk

**Comment by M66B** [comment]
Can you please try to toggle the widget a few times with this version and send me another logcat (even if there is no apparent problem):

http://netguard.me/NetGuard-v0.44-2015112704-release.apk

I have added some extra logging to diagnose the underlying problem.

**Comment by malitech** [comment]
I see. :)

Oh there was no visible crash before.
