### ISSUE TITLE
Notification on new app install

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#182]
I find a feature from AFWall+ really nice: [detect apps installs](https://developer.android.com/reference/android/content/Intent.html#ACTION_PACKAGE_ADDED)

It takes out the confusion part of "why does my new app not connect to the internet?" because the firewall is just something you set up once in a while:
* **if and only if** the app has permission internet (now on install): have a notification with "New app installed press here to allow/block internet access"
* press notification takes you to NetGuard
* the new app is put first on the list ( temporary )

/LE: 1000 commits soon :)

**Comment by M66B** [comment]
Test version: http://netguard.me/NetGuard-v0.44-2015112702-release.apk

There is no scroll to yet.

**Comment by licaon-kter** [comment]
Not scroll, maybe that's harder to code anyway ( even highlight it with a different colour somehow :P ), but I find it easier to notice the new app by having it as the first app on NG open.

**Comment by M66B** [comment]
You should really learn to develop yourself ;-)

**Comment by licaon-kter** [comment]
So you wanna have 1000 commits or not? :)

Notice that most of my idea/requests are more cosmetic ones, I was rather satisfied with the app a month ago ( ignoring the A5 though ), these help with the "easy for the users part", maybe even for a 5* rating or something. :P

**Comment by M66B** [comment]
No.

**Comment by okungnyo** [comment]
No?

**Comment by M66B** [comment]
Adding this features, means people will go asking for an option to turn it off and I want to keep NetGuard as simple as possible. Also people will go asking for a scroll to, which isn't simple to implement and in fact this is due to the simplicity of NetGuard, which has no separate activity to manage application rules, since this is done inline. Finally there is a feature stop, I will fix bugs only from now on.

**Comment by okungnyo** [comment]
What I'm confused about is what this feature that OP is requesting is, and why it needs 'scroll' (whatever that is). Can you explain?

**Comment by M66B** [comment]
Suppose the notification shows, you tap on it and the application you want to change settings for is at the bottom.

**Comment by licaon-kter** [comment]
It's not at the bottom since you control the view and put any/this new app on top, the first time you open NG via the notification at least. Like I said: `the new app is put first on the list ( temporary )`

@okungnyo You don't understand the need to have the *new* app easily accesible once NetGuard is opened or you don't understand what the issue is about?

If the latter:
* Install the version above **NetGuard-v0.44-2015112702-release**
* be sure to NOT block the NetGuard notification
* install a new app 
* what happens?

**Comment by okungnyo** [comment]
OK thanks.

**Comment by licaon-kter** [comment]
Thanks, ummm, again.

**Comment by M66B** [comment]
I thought of a simple way to implement this using notification actions, which does not even require you to open NetGuard. So, no need for scrolling to the application, which is not really supported by the recycler view.

**Comment by licaon-kter** [comment]
And you can't open a search query directly?

**Comment by M66B** [comment]
Not tried yet, please create a feature request for this to remind me.
