### ISSUE TITLE
Play Store screenshots for phone and tablet

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#184]
For the languages that were kinda complete: cn, de, en, es, it, nl, pt, ro, ru and uk.

Link: https://mega.nz/#!EUpAXILJ!9Q-YQUbYGyO1FOT9OXGziWf1152VsoQzII9CGTe2D7o

**Comment by M66B** [comment]
Thanks for providing the screenshots, they needed updating anyway!

Localized screenshots are only possible for localized Play store descriptions, so I have uploaded the English, Chinese and Romanian screenshots only.

For the next set better use the application defaults (=black list, etc).

**Comment by licaon-kter** [comment]
Should I re-take the tablet screenshots? I guess not, since there are 3G enabled tablets out there anyway.

Regarding non localized Stores, the Store forces you to have a localized translation so you can't upload screenshots otherwise?

**Comment by M66B** [comment]
I think the screenshots are okay, since they are just a sample of what to expect.

I cannot upload the screenshots other than creating a localized Play store description, which I don't want to do, since I don't have such a description.
