### ISSUE TITLE
Improve F-Droid support

### ISSUE THREAD

**Issue by M2ck** [M66B/NetGuard#189]
Could you improve F-Droid support, currently your app appears in [Failing builds category] (https://f-droid.org/wiki/page/Category:Apps_with_failing_builds) on F-Droid Wiki.
Thanks in advance.

**Comment by M66B** [comment]
I have no control over F-Droid and I do not support F-Droid.

**Comment by M66B** [comment]
See also this FAQ: https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ15

**Comment by M66B** [comment]
Looking into the [F-Droid build log of version 0.46](https://f-droid.org/wiki/page/eu.faircode.netguard/lastbuild_2015112902), F-Droid is using the wrong version of the build tools. I cannot fix that.

**Comment by M2ck** [comment]
Thanks for quick reply!
So it means that this is a problem coming from F-Droid?

**Comment by M66B** [comment]
Yes, it is.

I am using the *com.android.tools.build:gradle-experimental*, which is required to develop native code, but apparently F-Droid doesn't support this.

**Comment by M66B** [comment]
I have updated the Gradle build system to version 2.9 / experimental 0.4.0, but I am afraid it won't solve the F-Droid build problems.

**Comment by M66B** [comment]
The maximum I can do is report a F-Droid issue:
https://gitlab.com/fdroid/fdroiddata/issues/358

**Comment by M2ck** [comment]
Thank a lot for your support!

**Comment by M66B** [comment]
You're welcome, although I don't support F-Droid, I do support the NetGuard users.
(isn't that amazing for a free and open source application?)

**Comment by M2ck** [comment]
Yes i've noticed it!
French translation done by the way.

**Comment by M66B** [comment]
Thanks, the translation will be in the next release: https://github.com/M66B/NetGuard/commit/18c5049aa51e153a1577870641e37756db4ba8c6

**Comment by M2ck** [comment]
Great, I'm glad to help you (a bit).

**Comment by licaon-kter** [comment]
Fixed by [disabling build](https://gitlab.com/fdroid/fdroiddata/commit/ec077abfae38f26a2893d8c2b66d46f9ccf25082), wat?
Needs more poking.
