### ISSUE TITLE
Support profiles

### ISSUE THREAD

**Issue by cklam2** [M66B/NetGuard#19]
A handy feature would be support for modes so one can create multiple lists of apps that are allowed/blocked. Eg Abroad, national, limited data, etc.

**Comment by licaon-kter** [comment]
Although useful, this looks like a donation feature to me :)

**Comment by M66B** [comment]
[Donations](https://github.com/M66B/NetGuard/issues/11) will be completely voluntary now and in the future.

**Comment by M66B** [comment]
Profiles should in my opinion be a last resort, since you have to manually activate them, which is easily forgotten.

The option '*Allow when device in use*' is an example of a better solution, because it is automated.

So, my questions is, which options like this are desired?

**Comment by RealR** [comment]
A pre-defined option to deny internet access to all systemapps which do not need access for normal system operation would be a great feature.

**Comment by M66B** [comment]
@RealR it will be difficult to build a reliable list with all the different devices and ROMs available.

**Comment by M66B** [comment]
Rules for roaming will be supported in the next release.
Roaming will be default blocked.

**Comment by M66B** [comment]
I will close this issue now, but please let me know if there are more rule conditions required.
