### ISSUE TITLE
[Question] What does [Allow X when screen is on] mean, and what does it do exactly?

### ISSUE THREAD

**Issue by okungnyo** [M66B/NetGuard#190]

**Comment by M66B** [comment]
It does exactly what it says: checking this option will allow internet access to the application when the screen is on.

Could you please ask your next question on XDA:
https://github.com/M66B/NetGuard#support

**Comment by okungnyo** [comment]
I don't like XDA...

I don't understand, so basically it prevents the apps from using data while you're not using your phone?

Could you explain some use cases? Like, what you were thinking of when you added the feature?

Because I'm still having a hard time grasping what it does.

**Comment by M66B** [comment]
There is nothing wrong with XDA.

You block access to the internet for an application, but you want to allow internet access when the screen is on: check this option.

**Comment by okungnyo** [comment]
I just don't understand, you said you wanted to keep the app simple and not add any extra features that would bloat the app, right?

Well, what are the use cases of allowing Internet access only when the screen is on?

Can you give me some real-world examples of when you might need it?

I'm asking because I'm genuinely confused.

**Comment by M66B** [comment]
A use case can be cut off all internet while the screen is off to save battery or to protect your privacy (for example by not allowing applications to report your location).

**Comment by M66B** [comment]
IMHO netguad is still simple to use, you don't have to use these rule condition and they are by default not visible.

**Comment by okungnyo** [comment]
Yeah, I never said it wasn't, I'm just dumb and so I did not understand what that feature was.
