### ISSUE TITLE
Show statistics which net access were blocked

### ISSUE THREAD

**Issue by tomtom** [M66B/NetGuard#191]
In the status bar, net guard displays the number of blocked / not-blocked net accesses. There doesn't seems a way to find out, which apps were blocked. It would be nice if netguard provided a way for users to find out which app tried to access the net how often (and maybe also when).

Regards

**Comment by M66B** [comment]
Please read this FAQ:
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ5

**Comment by M66B** [comment]
The number of packages shown in the status bar notification just reflects the number of application your have blocked/allowed.

**Comment by tomtom** [comment]
Thanks for your response. I misread the numbers in the menu.

Anyway, my request was probably imprecise. What I'm interested in is for which apps has netguard actually (not nominally) blocked net access.

I read the FAQ before. I assumed that this info should be available since netguard has to decide at one point or the other whether to redirect the traffic into a sinkhole or not. But maybe I misunderstood how the app works.

**Comment by M66B** [comment]
How NetGuard works is simple: traffic of applications you have blocked internet access to will be sent into a VPN sinkhole that does nothing, so no statistics, IP filtering, etc, but also no extra battery usage and network speed reduction, as with all other no-root firewall solutions.
