### ISSUE TITLE
Home Wi-Fi network selector improvements

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#192]
Like:
* show multiple networks
* have it as checkboxes instead of radio buttons
* list saved networks

Right now:
* I don't know if the network selection is saved and if the next time time I connect it applies
* I wan't to setup them all at once

If it's possible that is.

**Comment by M66B** [comment]
Preferences do not allow for multiple selection.

**Comment by licaon-kter** [comment]
Yeah, so  you need some other type of menu then.

**Comment by M66B** [comment]
Apparently this exists: http://developer.android.com/reference/android/preference/MultiSelectListPreference.html

**Comment by M66B** [comment]
Test version: https://github.com/M66B/NetGuard/releases/tag/0.55
