### ISSUE TITLE
Speed graph notification improvements

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#194]
Like:
* make the graph move to the right (left side is older)
* a way to disable icon in status bar (make that notification low priority too maybe)
* integrate graph in main notification, have only one notification

**Comment by M66B** [comment]
There is a setting to disable the speed graph.

The main notification does but have enough room for the graph and the graph is displayed/updated at different moment than the main notification.

Not sure about the direction.

**Comment by licaon-kter** [comment]
It can't be set up now, it's all (icon+high prio notification+notification on lockscreen) or nothing.
Also, it's on the lockscreen _all_ the time, the private setting will keep it on screen but without content, so it will be even less useful. 

Maybe compact them a bit, but you say it can't be done, eh.

(I've swapped directions in my text, my bad) Right now, as I see it, new values are recorded on the left side, I want them shown on the right and have the old(er) values crawling to the left.

**Comment by M66B** [comment]
I will reverse the direction tomorrow.

The notification is not private and the contents should be visible on the lock screen. The priority of three notification is normal.

I see no reasons to configure the notification graph, you either want it or not IMO.

The graph in the notification is some trickery to work around Android limitations, which is another reason why the notifications cannot be merged.

**Comment by licaon-kter** [comment]
Maybe, make notification `low prio` to hide the icon that only states *hey you have a graph here*. :)

The notification on lockscreen, it's either:
* permanent notification on lockscreen with full graph and no way to turn it off
* permanent notification on lockscreen stating `private content` with no way to turn it off

Not sure how many want that, I don't. BTW, `low prio` fixes this too, one still can look at the notification after unlocking screen.

The thing is that I've been trained to action if I see an icon there in the status bar, it's the reflex response to *hey something needs your attention*, useful for *a chat message*, *e-mail*, *firewall stopped* or *buy more milk reminder* but not so much for *pushing 0.166kb/s up and 0.166kb/s down* (yes it's stays like that most of the time) :)

Also, since you have `pref_stats_base` you could have the graph on it's own.
And another toggle for `Show speed` but that gives me another idea: use the main notification to show speed numbers, which does not collide with your `trickery to work around Android limitations.` ;)

**Comment by M66B** [comment]
Low priority will move the notification to the bottom, which I don't want.

As said before, the speed graph notification and the main notification cannot be combined. The speed graph will for example work when NetGuard is off.

**Comment by M66B** [comment]
The next version will move the graph from right to left.

**Comment by licaon-kter** [comment]
An option to have net speed but not graph?

**Comment by M66B** [comment]
There are enough applications available for that.

**Comment by M66B** [comment]
Test version: https://github.com/M66B/NetGuard/releases/tag/0.55

**Comment by okungnyo** [comment]
Which application do you recommend for that?

**Comment by M66B** [comment]
I have nothing particular in mind.

**Comment by licaon-kter** [comment]
@okungnyo I've linked one above, but do not allow it to connect to the internet ;)

**Comment by licaon-kter** [comment]
Umm, no graph and no speed are shown in 0.55-2015121001 ?!

**Comment by M66B** [comment]
Works for me.
Is the option enabled?
Did you turn the screen off and on?

**Comment by licaon-kter** [comment]
Oh now it works.
Yes.
Did not know I had too, strange.

**Comment by licaon-kter** [comment]
At least disable graph icon & notification if no connection is active.

**Comment by M66B** [comment]
When is there no connection active (condition) ?

**Comment by licaon-kter** [comment]
If no network is connected, aka Wi-Fi off & mobile off, there is no reason to show the icon & notification.

**Comment by M66B** [comment]
For now you can manually turn of the notification.

The first one is already the highest bandwidth user.

**Comment by M66B** [comment]
The sort order was indeed incorrect and in fact the three application with the lowest bandwidth were shown. Fixed: https://github.com/M66B/NetGuard/releases/tag/0.58

**Comment by licaon-kter** [comment]
Thanks
