### ISSUE TITLE
Add certificate and force redirect to HTTPS for site

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#195]
For NetGuard.me get a free certificate from https://letsencrypt.org/howitworks/ ;)

**Comment by M66B** [comment]
As soon as letsencrypt has decent nginx support (not third party).

**Comment by licaon-kter** [comment]
You can bypass that, just get the certs, **certonly** , and link them where you want.
I not the type to let it auto-anyting, so many things can go wrong.

**Comment by M66B** [comment]
And redo that every 90 days manually, no thanks.

**Comment by licaon-kter** [comment]
You can then automate the renew, did not try that yet myself though. :)

**Comment by M66B** [comment]
That I why I said I am waiting for official nginx support.

**Comment by M66B** [comment]
Since the donation website will be less important with paid features, I am not going to add SSL to it.
