### ISSUE TITLE
Notification graph freeze

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#196]
Happened to me twice already, on a tablet, while NetGuard was off, but speed notification on.
Default settings of 1000ms / 90s.

Basically after some light web browsing and mail syncing, it just stood there frozen, graph not moving, speed values stuck at whatever values it reached, top app too.

Turning graph notification off and then on did not help, but turning NetGuard on and the off back made it work again.

Log while stuck: https://gist.github.com/licaon-kter/738c71a18de6bc1b6435

**Comment by M66B** [comment]
This doesn't surprise me, since the service will only be kept alive when NetGuard is active.
I will let NetGuard disable the graph when NetGuard is disabled.
