### ISSUE TITLE
Background leak

### ISSUE THREAD

**Issue by coombez** [M66B/NetGuard#197]
Hi,

I've noticed that apps that have been blocked from using Mobile (my default for all apps) are still able to sneak a little data through in the background (according to my data usage).  I work around this by restricting background data through the native settings for each app individually.

Neal

**Comment by M66B** [comment]
If the Android data counter increases a little, it doesn't say there is real internet access, it could be attempted internet access.

Traffic routed into the VPN sinkhole does not go to the internet, guaranteed.

**Comment by coombez** [comment]
So what your saying is the background mobile network data counter is prior to the vpnservice?

I don't think that is correct given the vpnservices I've seen that actually forward the data have all data usage counted as the vpnservice app instead of the originating app.  I think if the app is showing data usage that means the data was not properly routed to the vpnservice based on the rules.

I could be totally off base but I thought I'd throw that out there.

Neal

**Comment by M66B** [comment]
Check the data usage of NetGuard, it will be zero.

Also count in the startup delay as documented in the FAQ question 1:
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ1

Anyway, if Android doesn't route traffic into the VPN service for whatever reasons (intentional or unintentional) you will have data leakage which can be fixed.

On my stock Android version (Nexus 5, Marshmallow) this does not happen.

**Comment by M66B** [comment]
If you don't want to have a startup delay, your only option is to root and use a iptables bases firewall (my advice: AFWall+).

**Comment by coombez** [comment]
I haven't had any startup leakage yet and was already aware of that limitation. Obviously iptables is the correct solution, it's just broken that you have be logged in as root to use the correct solution.  They should really build system administration in to Android natively.

I'm also on stock marshmallow, do you not see this background usage? Or do you see it to buy have confirmed it is sinkhole usage?

**Comment by coombez** [comment]
Correction: 'See it too but'

**Comment by M66B** [comment]
I don't see background usage. I see some system services use a little, but that is most likely the startup leakage.

**Comment by M66B** [comment]
NetGuard is the best that can be done without root and don't count on Google adding this, since they will loose ad revenue if they do.

**Comment by coombez** [comment]
We're definitely seeing different behavior then.  The background usage I see is from most of the apps I use but have blocked with netguard.  It's also many days after the last reboot.  Interestingly I -never- see any foreground data usage, which I would expect to see if just any attempted access is measured since I know they are attempting access in the foreground.
