### ISSUE TITLE
Network detection

### ISSUE THREAD

**Issue by coombez** [M66B/NetGuard#198]
I tried to look into this myself to see what's possible, unfortunately I'm neither a Java guy or an android sdk guy.  So this issue is all I can do for now.  Apps that successfully detect they are offline normally (almost all Google apps for example) don't properly detect they are offline when blocked by netguard.  Not sure if there is anything in the vpnservice that can help?

**Comment by M66B** [comment]
All those apps are badly implemented, since they assume there is an internet access when there is internet access.

Anyway, without root you cannot fake to have no internet, so there is little that can be done here.

**Comment by coombez** [comment]
That's too bad. I was hoping the vpnservice api could simulate an econnreset on send or econnrefused on connect.  It behaves as though it just never gets a response.

**Comment by M66B** [comment]
The VPN service is a sinkhole, so there are no responses.

This differentiate NetGuard from all other similar solution which do IP decoding and encoding, which will use significant battery usage and reduce your network speed, since the CPU of your device is not infinite.

The code is on GitHub if you like to do this, just answer each SYN with a RST and you'll be done, but this will not be part of the NetGuard which I release, because of the aforementioned reasons.

**Comment by M66B** [comment]
BTW, the Android VPN service does not support ICMP, so RST is the only option before you ask.

**Comment by coombez** [comment]
I'm right there with you on the cpu usage and message processing. I would not want to interpret messages or simulate responses either.  I was hoping to simulate failures instead.

Can you point me to where the 'send' sinkhole is implemented? I already spelunked the code but like I said I'm not a Java or Android guy so navigating the code is a challenge for me.

**Comment by M66B** [comment]
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/SinkholeService.java

**Comment by coombez** [comment]
Thanks, unfortunately I've read that code and have no idea how to get from there to pretending the UNIX socket connect() function returns -13 and sets errno :)

**Comment by M66B** [comment]
The problem here is that there are no socket connections at this level, only lie level IP packets, which you need to handled in the code, hence the problem of battery usage. Note that using raw sockets is not possible without root in Android.
