### ISSUE TITLE
Average usage/day since boot strange

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#207]
The current implementation, while correct regarding the math part, it's strange for a human user.

Case, Chrome, download 270Mb:
* Settings -> Data usage-> Wi-Fi usage -> 270Mb
* NetGuard 15 minutes ago 4555891kb/day
* NetGuard now 3679990kb/day
* pull to refresh NetGuard 3650258kb/day
* repeat and it gets lower.

Yes it will stabilise after a while, but I just posted this maybe some other idea pops-up.

**Comment by M66B** [comment]
The math is correct, it is an average per day, to get a relative idea about how much an application will use.
