### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#211]
Android Studio 2.0-preview yields some warnings, they should be tackled maybe? Or it's just a problem with my setup?

First, on Gradle project import: `Error:Exception thrown while executing model rule: NdkComponentModelPlugin.Rules#createNativeBuildModel` (and some more info in the *idea.log* if you want it I could paste it)

Then on build/apk: 
* various *Note: duplicate definition of library class*
* various *Note: 'xxx' acesses a declared field 'yyy' dynamically*
* various *Note: the configuration keeps the entry point 'xxx' { void startActivityFromFragment(yyy); }', but not the descriptor class 'xxx'*
* various *Note: there were X classes trying to access generic signatures using reflection.*
* maybe more

Also, the debug build asks for `permission fine location` as XPrivacy pops-up, is this normal?

**Comment by M66B** [comment]
You can ignore the warning (the NDK is not being used at this moment) and all notices.

XPrivacy pops maybe up because of the phone state listener. My debug build doesn't request location permission (checked using the Marshmallow permission manager).

licaon-kter <notifications@github.com> schreef op 1 januari 2016 12:14:13 CET:

**Comment by licaon-kter** [comment]
That NDK error prevents Gradle sync which prevents getting builds type with `Missing Gradle Project Information. Please check if the IDE successfully synchronized its state with the Gradle Project Model.` which prevents generating signed APKs. (at least in my case)

**Comment by M66B** [comment]
Try changing the gradle plugin to 1.5.0

**Comment by M66B** [comment]
Do you use Android studio 1.5.1?

licaon-kter <notifications@github.com> schreef op 1 januari 2016 13:03:47 CET:

**Comment by M66B** [comment]
Changing back to gradle  plugin 1.5.0 requires revising the gradle files, since the DSL has been changed.

You could try experimental 0.6.0-alpha1


licaon-kter <notifications@github.com> schreef op 1 januari 2016 13:03:47 CET:

**Comment by licaon-kter** [comment]
Like I said `Android Studio 2.0-preview` and Gradle 2.8 apparently. Not sure how to change to 1.5.0 or *experimental 0.6.0-alpha1*
I wanted to generate a non-debug build, the only I get by default ends up unsigned and can't be installed.

**Comment by M66B** [comment]
It works in Android studio 1.5

licaon-kter <notifications@github.com> schreef op 1 januari 2016 17:14:52 CET:

**Comment by licaon-kter** [comment]
Yes, 1.5 does not show the same warnings.

**Comment by rgarza** [comment]
Im using Android 2.0 Preview 6 and works without problem, i am on osx

**Comment by licaon-kter** [comment]
@rgarza I'll retry also then.

https://medium.com/google-developers/android-studio-2-0-beta-what-s-new-87f8b3946888
