### ISSUE TITLE
Always on VPN

### ISSUE THREAD

**Issue by JasperWeiss** [M66B/NetGuard#214]
In Cyanogenmod (not sure if Android does this) there is an option under vpn settings to only allow networking over a given VPN. This ensures there are no leaks on boot or when say the app stops for whatever reason. 
But as I see it it only allows you to select a vpn which a user has manually configured, could we find a way to use this with netguard?

**Comment by M66B** [comment]
Android doesn't support always on VPNs provided by user applications.

**Comment by M66B** [comment]
I would like to use this feature too, since it would allow starting the VPN earlier in the boot process.

**Comment by JasperWeiss** [comment]
I know it doesn't that's why I'm asking. Perhaps 'Advanced' users could manually setup a VPN that redirects to a localhost adress and port supplied by netguard?

**Comment by M66B** [comment]
NetGuard is different from seemingly similar firewall applications in that it doesn't implement the VPN service. The VPN is used as sinkhole to route unwanted traffic into, with as big advantages that no extra battery is being used and that the overall network speed is not being reduced.

This also means what you are asking cannot be done.

**Comment by JasperWeiss** [comment]
If there's no service running that reduces battery life and such. how does the 'sinkhole' know which traffic to block or allow? Just curious. does it apply certain rules to the vpn that the system itself handles?

**Comment by M66B** [comment]
See here: https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ3

**Comment by JasperWeiss** [comment]
Ok, So it uses AddDisallowedApplication. But it still updates rules when changing from wifi/mobile data, doesn't that require a service?

**Comment by M66B** [comment]
Yes, it requires a service, but why should that we a problem?

**Comment by JasperWeiss** [comment]
But doesn't that mean it does affect battery life, contrary to what the description says?
Also, I couldn't find a way to buy the pro features. And since I don't have GAPPS, would I have to buy it again if I reinstall the app

**Comment by M66B** [comment]
Services use only battery when doing something, which the NetGuard service hardly does. It only applies other rules when connectivity changes (from/to Wi-Fi/mobile) or when the screen turns on/off.

If you don't have Google apps, which I can totally imagine if you are privacy aware, you can donate using three other ways: http://www.netguard.me/

If you donated 4 euros or more, see here for how to proceed:
http://forum.xda-developers.com/showpost.php?p=64617344&postcount=745
