### ISSUE TITLE
Toaster on succesful import/export

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#215]

**Comment by M66B** [comment]
There is already one.
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L501
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L550

**Comment by licaon-kter** [comment]
Ok, notifications are not disabled, I'll retest.

**Comment by licaon-kter** [comment]
Ok, retested NetGuard-v0.67-2016010501 and it's ok, It will not always apply in an instant so that I might have missed the toaster.
