### ISSUE TITLE
Display 'has no internet' in notification

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#218]
As requested on XDA.

**Comment by licaon-kter** [comment]
It was not good enough when I asked for it https://github.com/M66B/NetGuard/issues/182 ? :P

**Comment by M66B** [comment]
I am still in doubt about this.

**Comment by licaon-kter** [comment]
Which part? Duplicate or usefulness?

**Comment by M66B** [comment]
People will complain not seeing a notification when installing a new application without internet.
Nowadays there are few such applications anyway, so this will not be very useful anyway.

**Comment by licaon-kter** [comment]
Yes, having it keeps the app consistent as it shows by default apps without internet anyway (in case they do get permissions in the future blahblah).

**Comment by M66B** [comment]
I hope 'blahblah' isn't meant in a negative way.

I know this feature request can be seen from multiple perspectives.

The remark 'notifications don't work' is to be expected if there are notification for applications without internet. Maybe a compromise could be to display 'has no internet', for which I will reopen this issue.

**Comment by licaon-kter** [comment]
Nothing negative, text cut out.

Yes, display that info, although many users might ask themselves "they why bother asking me what to do about it" hence my proposal to show the Allow/Block notification buttons only on internet enabled apps, and show no buttons otherwise.
