### ISSUE TITLE
No filters for "user" or "system" available in menu

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#220]
But I do have `disabled` and `no internet` available there.

Clean install NetGuard-v0.67-2016010501 from Github

Tablet non-3G, CM12.1.

**Comment by M66B** [comment]
These are only displayed if you enabled managing system applications

**Comment by licaon-kter** [comment]
You are right, but this needs finer controls maybe, since https://github.com/M66B/NetGuard/issues/219
