### ISSUE TITLE
Add prefix (PRO) to monetized features that are not bought

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#222]
Both in Menu and Settings.

**Comment by M66B** [comment]
Opening the pro features window is clear enough IMO and enables the user to directly purchase the feature.

**Comment by M66B** [comment]
Thanks for the suggestion, though.

**Comment by licaon-kter** [comment]
That is annoying, you click on something and that `buy it` screen pops-up.
I would find it nice to be able to recognize PRO features by reading the actual text.

Else, for someone new to the app, it's pop-up after pop-up, *oh, I need to buy this, back, oh and this, back, oh*...
