### ISSUE TITLE
No auto start on power up or restart

### ISSUE THREAD

**Issue by RowCom** [M66B/NetGuard#223]

**Comment by RowCom** [comment]
I have A Samsung Galaxy S5 & a Nexus 10 tablet and neither auto start.  Does Netguard do this function ?

**Comment by M66B** [comment]
If the firewall is enabled it will be auto started on boot. If it doesn't work, please send me shortly after booting a log file by tapping seven times on the title of 'about'.

**Comment by RowCom** [comment]
Unable to tap seven times as a 'Rate' dialog box appears after first tap

**Comment by M66B** [comment]
Try tapping on the title or background.

**Comment by RowCom** [comment]
How do i attach the log file.

**Comment by M66B** [comment]
You can send it to marcel(plus)netguard(at)faircode(dot)eu if your e-mail app doesn't open automatically.

**Comment by M66B** [comment]
```
01-06 21:05:27.729  5297  5409 E NetGuard.Service: java.lang.IllegalStateException: VPN start failed
01-06 21:05:27.729  5297  5409 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleIntent(SourceFile:227)
01-06 21:05:27.729  5297  5409 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleMessage(SourceFile:139)
01-06 21:05:27.729  5297  5409 E NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-06 21:05:27.729  5297  5409 E NetGuard.Service: 	at android.os.Looper.loop(Looper.java:145)
01-06 21:05:27.729  5297  5409 E NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

This means your Android version has a bug.
I cannot work around this.
Samsung ROMs are known for their many bugs.

**Comment by M66B** [comment]
Which Android version is on the device?
(Android settings, about the phone)

**Comment by RowCom** [comment]
The Samsung Galaxy S5 has Android 5.0 and the Nexus 10 has 5.1.1

Regards,
Jeff Rowley
e:  rowleyjeffj@gmail.com
#Nexus#



--- Original message ---

**Comment by M66B** [comment]
Are you using the latest version?
Somebody reported that this problem was fixed.

**Comment by RowCom** [comment]
v0.68.  When I reboot either device, Netguard doesn’t restart.  I start Netguard and, for a few seconds, I see the enable/disable switch in the enabled position then it drops to disabled.  I then enable it again, answer the VPN confirmation dialog boxes and all is OK.

**Comment by M66B** [comment]
What you are describing is a bug in Android. The Android VPN permissions dialog should be displayed only once per application, even when rebooting.


RowCom <notifications@github.com> schreef op 7 januari 2016 02:13:58 CET:
