### ISSUE TITLE
Notification app count wrong

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#225]
Device with both Wi-Fi and mobile.

Allow 1 app on Wi-Fi but not 3G, notification says `0 allowed`.

Allow on 3G and works as expected.

**Comment by M66B** [comment]
Please send a logcat referencing this issue.

**Comment by licaon-kter** [comment]
https://gist.github.com/licaon-kter/8f852fb6773748eef4b1

**Comment by M66B** [comment]
In this log file there is no internet connection:

```
Starting connected=false wifi=false home="mywifi2","mywifi" network=<unknown ssid> metered=true telephony=true generation=null roaming=false interactive=true
```

**Comment by licaon-kter** [comment]
It does not matter, there is no 3G either and it shows `1 app allowed` if 3G is allowed.

**Comment by M66B** [comment]
No connection will always apply mobile rules.
I will consider to change this.

**Comment by licaon-kter** [comment]
`Did test with Wi-Fi **on** and it's still the same`

**Comment by M66B** [comment]
Please check and report how this release behaves:
http://www.faircode.eu/NetGuard-v0.73-2016010901-all-release.apk

Please capture a logcat directly after seeing a problem (for each problem a separate one).

**Comment by M66B** [comment]
BTW, you can see which rule set is being applied in the UI, since the not applied rule set(s) are being low lighted.

**Comment by licaon-kter** [comment]
Low lighted? No idea what you mean. My `allowed on Wi-Fi` app is Opera, is listed first on a grayish background, icons are blue, the rest are red with a diagonal line.

The 2 issues occur at the same time, no need for 2 logs.

BTW, AFWall+ is disabled/quit, I'll uninstall it now and reboot just in case, right now with the new build it's worse: `0 allowed, 0 blocked` kinda always.

**Comment by M66B** [comment]
0 allowed, 0 blocked means no internet connection.

The information that is in header that is generated with the logcat is of importance here.

**Comment by licaon-kter** [comment]
Ok, so, no AFWall, rebooted.

Wi-Fi on and/or 3G on, Wi-Fi allow all, 3G allow all.

Network info for Wi-Fi on says:
* Connected False
* Wi-Fi or Metered True
* MOBILE/HSPA / DISCONNECTED my.telco.com 3G *
* Wi-Fi / DISCONNECTED "mywifiname" *
* VPN/ DISCONNECTED

**Comment by M66B** [comment]
Wi-Fi is not connected: Wi-Fi / DISCONNECTED "mywifiname" *
Mobile is not connected: MOBILE/HSPA / DISCONNECTED my.telco.com 3G *

Don't ask me why, but this is what Android reports.

**Comment by licaon-kter** [comment]
You are right, remembered I had XPrivacy exclude NetGuard, but since I tend to uninstall on each new version it got managed again. That `app asks for Internet` dialogue is tricky, especially since it follows `app asks for Location`, I might have answered *Deny*.

Yes, checking Expert will detail the exact permission which is makes the case clear for why the app needs that, but I'm no XPrivacy expert. ;)

Really sorry for the noise.
