### ISSUE TITLE
No Wi-Fi access if no 3G allow

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#226]
Guess it's related to https://github.com/M66B/NetGuard/issues/225, basically with Wi-Fi on and mobile off:
* allow only Wi-Fi (with Wi-Fi on and 3G off) -> blocked app
* allow Wi-Fi and 3G (with Wi-Fi on and 3G off) -> allowed app
* allow only 3G (with Wi-Fi off and 3G off) -> allowed app

Logcat: https://gist.github.com/licaon-kter/8f852fb6773748eef4b1

Opera was allowed on Wi-Fi yet the logcat has no entry for Opera, umm?

**Comment by M66B** [comment]
Likely a duplicated of #225

**Comment by licaon-kter** [comment]
That treats the info on screen.

This treats the actual rule not applying, although the UI **has** the small Wi-Fi icon blue aka I allowed it.
