### ISSUE TITLE
Activity Log option for 24h timstamps

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#229]
Have a Settings or Menu option for AM/PM or 24h timestamps ( to avoid this: https://github.com/M66B/NetGuard/commit/ecf83ac813c4f27cb953d3269b8b895ffa6430a9#commitcomment-15359705 )

**Comment by M66B** [comment]
There is a setting in Android for this and this belongs not in an application.

**Comment by licaon-kter** [comment]
Where is that *other* setting in Android? My Date/Time is set to 24h already.
All the other apps (clock/statusbar) show time in 24h, except that NetGuard pop-up.

**Comment by M66B** [comment]
Toggle the Android setting one time back and forth and you'll see NetGuard will show the correct time.

**Comment by licaon-kter** [comment]
Ok, change to am/pm, kill netguard, same, change to 24h, kill netguard and now it does, strange that it needs that. 

10q

**Comment by M66B** [comment]
Yes, Android bug.
