### ISSUE TITLE
List refresh cancels search

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#232]
Since you changed the list refresh type (I guess) it takes a while for the list to appear, one can see the spinner a lot, even without disabled/no internet visible.

But in the mean time you can open the search and start typing, it even works, it shows what it can find, until the list refresh finished in the back that is, when that happens your search is cancelled and you are forced back at the whole list.

Either block search access until list finishes to appear or if search is open never switch automaticaly to the whole list.

**Comment by licaon-kter** [comment]
10q @rgarza

**Comment by licaon-kter** [comment]
Reopen this as it's not fixed. 10q

**Comment by M66B** [comment]
Works for me

**Comment by licaon-kter** [comment]
Not for me, still stops my search and switches to main list as soon as the refresh finishes (the spinning circle disappears).

**Comment by M66B** [comment]
Then I don't know, sorry.

**Comment by licaon-kter** [comment]
Also tested on Samsung 5.0.2: pull to refresh, open search, type `ope` so Opera shows up, refresh finishes and the search is gone.

**Comment by licaon-kter** [comment]
How do I convince you this is a real issue?

**Comment by M66B** [comment]
What I missed was that you were typing during the refresh
