### ISSUE TITLE
Need to disable/enable NetGuard for newly-installed apps to have internet access

### ISSUE THREAD

**Issue by enervated** [M66B/NetGuard#233]
Huawei Nexus 6P
NetGuard 0.75
Android 6.0.1

Every time a new app is installed, and I enable access for it in NetGuard (whether by the notification or in the main GUI), the app has no access to the internet unless I disable/enable NetGuard. The problem happens every time, and the workaround works every time.

**Comment by M66B** [comment]
This will be fixed in the next (beta) release.
