### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by Babar-Bashir** [M66B/NetGuard#238]
Error:Execution failed for task ':app:compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC'.
 A build operation failed.
      C compiler failed while compiling netguard.c.
  See the complete log at: file:///C:/Users/babar/Desktop/%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23Android%20Studio%20Projects/NetGuard-master/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt

------------------------------------------------------------------
output.txt
-------------------------------------------------------------------

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
=========================================================

please tell me how to solve this issue

**Comment by M66B** [comment]
The C compiler compiles successfully for me.
Maybe this is a Windows problem (I develop on a Linux machine).
Please check .../output.txt for more details as the message says.

**Comment by licaon-kter** [comment]
@Babar-Bashir Hope you are using AndroidStudio 1.5.1 and not 2.0-preview ( see https://github.com/M66B/NetGuard/issues/211 )

**Comment by Babar-Bashir** [comment]
yes I am using AndroidStudio 1.5.1. Windows 10 x64

**Comment by M66B** [comment]
Please check .../output.txt for more details as the message says.

**Comment by Babar-Bashir** [comment]
See file:///C:/Users/babar/Desktop/%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23Android%20Studio%20Projects/NetGuard-master/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt for all output for compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC.
compiling netguard.c failed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: E:\adt-bundle-windows-x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk\ndk-bundle\toolchains\llvm-3.6\prebuilt\windows-x86_64\bin\clang.exe
File: /s/ndk-toolchain/src/llvm-3.6/llvm/lib/Option/OptTable.cpp, Line 285

Expression: Index >= End && "Unexpected parser error."

Finished compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC, see full log file:///C:/Users/babar/Desktop/%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23%23Android%20Studio%20Projects/NetGuard-master/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt.

**Comment by Babar-Bashir** [comment]
This is my output.txt file. I didn't figure out how to solve it

**Comment by M66B** [comment]
"*Unexpected parser error*" is a bug in the compiler. If you can figure out which source/line, we can try to change the source code, but better check if there is a newer version of the compiler.

I am using the compiler from android NDK r10e on Linux.

**Comment by GermMuz** [comment]
I have  very similar issue:

See file:///C:/Users/Glenn/Documents/Android/NetGuard-0.79/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt for all output for compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC.
compiling netguard.c failed.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

Finished compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC, see full log file:///C:/Users/Glenn/Documents/Android/NetGuard-0.79/app/build/tmp/compileArm64-v8aDebugNetguardSharedLibraryNetguardMainC/output.txt.


Android Studio 2.0 installed today as well as latest sdk.

**Comment by licaon-kter** [comment]
@GermMuz AndroidStudio 2.0preview is not yet final and not yet supported: https://github.com/M66B/NetGuard/issues/211

Go back to 1.5.1.
