### ISSUE TITLE
Use default DNS for VPN

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#246]
Looking at the [logcat](https://gist.github.com/licaon-kter/ad58d6c8e28d31b14f8b) for another issue I see a bunch of these:
```
NetGuard.JNI: get uid 8.8.8.8/53 syn 0
NetGuard.JNI: Packet v4 10.1.10.1/4754 -> 8.8.8.8/53 proto 17 flags  uid 0
NetGuard.JNI: UDP new session from 10.1.10.1/4754 to 8.8.8.8/53
NetGuard.JNI: Cached method ID protect
NetGuard.JNI: UDP forward from tun 10.1.10.1/4754 to 8.8.8.8/53 data 56
```

That's the wrong DNS, is the getdns function failing to default?
`dns = InetAddress.getByName(prefs.getString("dns", "8.8.8.8"));`

**Comment by M66B** [comment]
If you enable domain (ad) blocking the DNS will be set to 8.8.8.8 for the VPN for now.
There will be a setting later.
The default DNS on Android is 8.8.8.8 and as far as I know this cannot be changed without root.

**Comment by licaon-kter** [comment]
If you rename it it's a duplicate of https://github.com/M66B/NetGuard/issues/30

Anyway, my DNS is set up by DHCP (from Wi-Fi or mobile) so it's not 8.8.8.8 at all.

**Comment by M66B** [comment]
You are right, title changed.

**Comment by M66B** [comment]
There is not a public API to get the DNS server.
http://stackoverflow.com/questions/3070144/how-do-you-get-the-current-dns-servers-for-android

**Comment by M66B** [comment]
At the bottom here seems to be the best alternative:
http://stackoverflow.com/questions/28413530/api-to-get-android-system-properties-is-removed-in-arm64-platforms

But I don't want to go this road, since there is no guarantee there are system properties at all.
