### ISSUE TITLE
Crashing on filter activate

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#247]
Xperia 5.1.1

`Netguard has crashed` dialogue

Logcat from NetGuard: https://gist.github.com/licaon-kter/2d611de4a39713c35724

Without filter looks ok.
Is excluded in XPrivacy.

Basically as soon as I activate filter:
* open an allowed app, hit refresh, crash
* open Netguard to save logcat, save logcat, crash -> logcat 0 bytes
* open Netguard to save logcat, save logcat, leave Netguard started in the background, crash ( even multiple dialogue windows )

**Comment by M66B** [comment]
Can you please capture a full logcat?
The crash is not in the provided log.

I am also not sure how to reproduce this.
What is 'open allowed app'? You mean drill down in NetGuard?
What is 'hit refresh'? You mean pull to refresh in NetGuard?

**Comment by licaon-kter** [comment]
No, allowed Opera, switch to Opera, refresh, crash

**Comment by M66B** [comment]
So, this might not be a NetGuard problem.
The logcat might tell what is going on.

**Comment by licaon-kter** [comment]
What does it say?

**Comment by M66B** [comment]
See above: "*The crash is not in the provided log.*".

**Comment by licaon-kter** [comment]
The second one is from **aLogCat** filtered to *netguard*. Do you want to see the full one with all the apps?

Also, this happens on a non-rooted Xperia 5.1.1 too.

**Comment by M66B** [comment]
Yes, a full logcat please.

**Comment by licaon-kter** [comment]
The in-app logcat on the no-rooted device is useless. :(
I'll see how I can retrigger this on the rooted one.

**Comment by M66B** [comment]
Please try again to get a logcat with the built-in function.
(I have removed all filtering)

**Comment by M66B** [comment]
This should be fixed in the upcoming version, please let me know if it is not.

**Comment by licaon-kter** [comment]
Nope, still having it.

Xperia 5.1.1
0.77-beta5

W/ or w/o internet connection.

NetGuard disabled -> Enable `filtering` -> Enable NetGuard -> Disabled

```
NetGuard.Service: DNS system=my.dns.ip.yeah VPN=
01-26 00:40:29.513 23739 23815 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
01-26 00:40:29.513 23739 23815 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.net.VpnService$Builder.addDnsServer(VpnService.java:536)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.net.VpnService$Builder.addDnsServer(VpnService.java:557)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.startVPN(SourceFile:673)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.access$1300(SourceFile:76)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.start(SourceFile:324)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleIntent(SourceFile:259)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleMessage(SourceFile:168)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.Looper.loop(Looper.java:211)
01-26 00:40:29.513 23739 23815 E NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-26 00:40:29.514 23739 23739 I NetGuard.Main: Preference enabled=false
```

Without `Filtering` works ok.
It might work ok if app already enabled and then enable `filtering`.

**Comment by M66B** [comment]
This is a DNS problem and will be fixed in the next release.
For now enter a DNS address in the development options.
