### ISSUE TITLE
Flush DNS entries on filtering

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#249]
Or at least on `block domain names` activation. 
For now testing right away after activation you can still reach a blocked domain since it can be in cache.

Not sure if achivable w/o root though.

**Comment by M66B** [comment]
I don't think there is a way to flush DNS without root and in a compatible way.

**Comment by licaon-kter** [comment]
Any idea at least on how big the table is? Maybe you can overload it?

**Comment by M66B** [comment]
Overloading seems like a very ugly hack to me.
This will not be in NetGuard.

**Comment by licaon-kter** [comment]
Ok, it's not a super needed function anyway. I guess the cache will get flushed after a while and it won't matter any more.

**Comment by M66B** [comment]
The default cache timeout on Android is 10 minutes.
