### ISSUE TITLE
Dns fails to update after network change 

### ISSUE THREAD

**Issue by actinium227** [M66B/NetGuard#251]
Dns seems to be stuck after a network change from wifi to mobile network, netguard would fail to enable if it was disabled, the slider button would turn on then force back to the disabled position with no vpn notification (program starts okay), this would only be resolved by uninstall and reinstall (clearing data / force close doesn't fix it). This seems to occur when I tried to enable tethering, netguard cannot be enabled again.

**Comment by actinium227** [comment]
It is only on 0.77b5, works fine on 0.77b4

**Comment by M66B** [comment]
0.77 beta 4 had a fixed DNS address.
