### ISSUE TITLE
Mixed up tech info

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#254]
Just noticed this in NetGuard-v0.78-2016012701-all-release but it was there all along

So on my Samsung 5.0.2 SIM/Network are in General and not in Subscriptions.

![image](https://i.imgur.com/AlgNWWv.jpg)

**Comment by M66B** [comment]
This is how it supposed to be.

The network section is for general network info, not specific for mobile networks (these belong in the general section). Subscriptions are mostly for dual SIM devices.

**Comment by licaon-kter** [comment]
Xperia 5.1.1 has them the other way around, hence may enquiry.

**Comment by M66B** [comment]
This has to do with permissions, temporarily enable one of the mobile metered settings or the national roaming setting to allow the required permission (or use the Android settings to allow the phone state permission).

**Comment by licaon-kter** [comment]
Nothing changed. I use the same settings on both devices hence my confusion.

Xperia says 
* Slots 1/1
* SIM 1/1
* Network 1/1

And since there are versions with DualSIM, they might just use the same modules, but limit them to 1 SIM in my device and two in the others.

**Comment by M66B** [comment]
Maybe the device have a different Android version.
I am going to move the technical info to the debug section, since this is not important to support.
The same information will be sent with the logcat as well.

**Comment by licaon-kter** [comment]
Can you make the debug toggle hide all the stuff (it manages) if disabled?
