### ISSUE TITLE
All traffic blocked in beta7

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#255]
Xperia 5.1.1 non-rooted, filtering and domains toggled on
I did not get a chance to repro yet as it's not my device.

Basically, it had 0.77-beta6 and was working ok, update to beta7 and it went dark, nothing worked.
Journals last entry was 12 hours ago when it updated to beta7.

Logcat with Wi-Fi and/or mobile turned on, yet all traffic blocked: https://gist.github.com/licaon-kter/dff39ea17f5986e36a44

Switched block domains off and traffic flowed again.
Cleaned journal, yet no new entries are registered.

Reloaded [hosts file](https://github.com/StevenBlack/hosts/blob/master/hosts), turned blocked domains on again and now it works.

**Comment by M66B** [comment]
I will rewrite the logic to check for block/allow soon, so I am not going to fix this.

**Comment by licaon-kter** [comment]
I'm not sure I understand.

What does the log tell you?

**Comment by M66B** [comment]
The log file tells very little, but I am aware of some problems in the beta 7.
Just have some patience.
