### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by halcyonest** [M66B/NetGuard#26]
<resources>
    <string name="app_name" translatable="false">넷가드</string>
    <string name="app_copyright">Copyright \u00A9 2015 by M. Bokhorst (M66B)</string>

    <string name="menu_search">앱 검색</string>
    <string name="menu_network">네트워크 설정 열기</string>
    <string name="menu_whitelist_wifi">Wi-Fi 차단을 기본 설정으로</string>
    <string name="menu_whitelist_other">모바일 데이터 차단을 기본 설정으로</string>
    <string name="menu_dark">어두운 테마 사용</string>
    <string name="menu_vpn_settings">Android VPN 설정 열기</string>
    <string name="menu_support">지원</string>
    <string name="menu_about">넷가드 정보</string>

    <string name="msg_sure">계속 하시겠습니까?</string>
    <string name="msg_disabled">넷가드가 해제되어 있습니다. 상단 스위치를 사용해 넷가드를 활성화하세요.</string>
    <string name="msg_revoked">넷가드가 해제되었습니다</string>

    <string name="title_using">기기가 사용중일때 허용</string>
    <string name="title_launch">앱 시작</string>
    <string name="title_donate">기부</string>
    <string name="title_thanks">기부해주셔서 감사합니다!</string>

    <string name="fingerprint" translatable="false">ef46f813d2c8a064d72c936b9b96d1cccc989378</string>
    </resources>

**Comment by M66B** [comment]
Thank your very much!
