### ISSUE TITLE
List refresh cancels app details

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#260]
Refresh manually (it sometimes auto refreshes too), open app details for a managed app (say Opera) to look at access, when refresh finishes the app details are closed, you got back to the main list.

Kinda like https://github.com/M66B/NetGuard/issues/232#issuecomment-177260477 so not sure if duplicate.

**Comment by licaon-kter** [comment]
Killer combo with https://github.com/M66B/NetGuard/issues/261

http://imgur.com/7UmES5m

**Comment by M66B** [comment]
This happens only on manual refresh and is the intended behavior to get the application list in virgin state again.

**Comment by M66B** [comment]
There are automatic updates, for example when a new application has been installed.
This is an edge case and I will later see if I can fix this.

**Comment by M66B** [comment]
IMHO this is too much an edge to complicate the code for, so I am not going to fix this.
