### ISSUE TITLE
Add address:port redirection abilities

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#272]
Say to run local servers, since you can't listen to common <1024 ports (80,53,443,21,22 etc) as a non root user, maybe have the servers at >1024 (8080,5353,4433,2121,2222 etc) and the filter function could just redirect them to the wanted addresses and ports (both on output and on input).

Not sure how 127.0.0.1 is treated (or named) when the VPN is up, hopefully it's accessible as usual.

This could cover the MITM issue say for DNS with [Unbound](https://github.com/smarek/android-unbound-dns/issues/6) and/or [DNSCrypt](https://github.com/jedisct1/dnscrypt-proxy)

**Comment by M66B** [comment]
Refs #195

**Comment by licaon-kter** [comment]
Is there a need to run it as root? (besides the point for a no-root firewall; and you don't need/use a <1024 port anyway 5353). Also, if you go root, put the resolvers list in a root only accessible place too ;)

I'll test this later for full no-root ( like via https://play.google.com/store/apps/details?id=com.ryosoftware.initd )

**Comment by M66B** [comment]
No need to run as root.

I did only a quick test by putting the dnscrypt-proxy into /system/xbin, because there is no wrapper GUI application for dnscrypt-proxy (maybe I will make one later).

Note that these experiment commits have been reverted, so you will need to add them back in if you want to test.

**Comment by licaon-kter** [comment]
Did it work for you with dnscrypt-proxy?

I build commit https://github.com/M66B/NetGuard/commit/0d61d804d86ca908aec81e9c837140e0d5a7ccd3
Have Unbound running on 127.0.0.1:5353 ( I pass these http://docs.menandmice.com/display/MM/How+to+test+DNSSEC+validation )

Netguard disables itself after few seconds: https://gist.github.com/licaon-kter/effe91441c655c856608

**Comment by M66B** [comment]
dnscrypt-proxy worked perfectly for me.

You should not change the VPN DNS address:

```
02-05 12:59:32.710  9445  9477 I NetGuard.Service: DNS using=/127.0.0.1
02-05 12:59:32.710  9445  9477 I NetGuard.Service: vpn4=10.1.10.1 vpn6=fd00:1:fd00:1:fd00:1:fd00:1
02-05 12:59:32.711  9445  9477 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
02-05 12:59:32.711  9445  9477 E NetGuard.Service: java.lang.IllegalArgumentException: Bad address
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at android.net.VpnService$Builder.addDnsServer(VpnService.java:536)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.startVPN(SinkholeService.java:790)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService.access$1500(SinkholeService.java:89)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.start(SinkholeService.java:352)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleIntent(SinkholeService.java:286)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at eu.faircode.netguard.SinkholeService$ServiceHandler.handleMessage(SinkholeService.java:192)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at android.os.Looper.loop(Looper.java:211)
02-05 12:59:32.711  9445  9477 E NetGuard.Service: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

with the commit DNS will be forwarded automatically to 127.0.0.1:5353 for uid 2000 (shell).
You could change the port (5353) and the uid (200).

Later there will be a convenient GUI for this.

**Comment by licaon-kter** [comment]
Does the UID need to be burned in? I'm using the [Unbound app](https://github.com/smarek/android-unbound-dns/issues/6) compiled from git.

I'll retry without forced DNS.

**Comment by M66B** [comment]
"*Later there will be a convenient GUI for this.*"

**Comment by licaon-kter** [comment]
Was wondering why you need to specify the app by UID, just so you can allow traffic to it by default? If so, if I allow traffic manually it would not work?

Or is there another reason altogether ?

**Comment by M66B** [comment]
We don't want to forward port 53 of dnscrypt-proxy or unbound to itself, hence the exception by uid.

**Comment by licaon-kter** [comment]
Nice catch.

**Comment by M66B** [comment]
With the next version, you can do this to start port forwarding:

```
am startservice -a faircode.netguard.START_PORT_FORWARD --ei source 53 --ei target 5353 --ei uid 2000
am startservice -a eu.faircode.netguard.STOP_PORT_FORWARD --ei source 53
```

Later on I will protect the start service intent with a permission, so not everybody can do this.
(so, don't build anything on this yet, it is an experimental feature for now)

**Comment by licaon-kter** [comment]
Just say when...

**Comment by M66B** [comment]
Next beta release, likely today, will have this feature, but somewhat changed.
Port forwarding will need to be approved for security reasons, see here for the new intents:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivityForward.java#L75

**Comment by M66B** [comment]
If you don't want to wait, you can use this version:
https://github.com/M66B/NetGuard/issues/290#issuecomment-180789408

I am just waiting some time for feedback on test version and then I will release this version.

**Comment by licaon-kter** [comment]
Approved in what way?

**Comment by M66B** [comment]
To prevent that a rogue applications forwards traffic to itself.
So, user approved, you'll see when you fire the intent using am in a shell.

**Comment by M66B** [comment]
http://developer.android.com/tools/help/shell.html#am

**Comment by licaon-kter** [comment]
This is as an intent for future use, say another app wants to set a redirection vs a NetGuard setting that the user needs to set up for that app?

**Comment by M66B** [comment]
Yes, indeed, think of DNS proxy or HTTP proxy applications which can send this intent to request the traffic forwarded to them.

A little not: disabling NetGuard will erase the port forwardings.

**Comment by licaon-kter** [comment]
```
am start -a eu.faircode.netguard.START_PORT_FORWARD \
                     -n eu.faircode.netguard/eu.faircode.netguard.ActivityForward \
                     --ei protocol <protocol> \
                     --ei source <source> \
                     --ei target <target> \
                     --ei uid <uid>
```

`protocol` is what? 6 for TCP an 17 for UDP... else ? mmm
`source` is target port? from this port...
`target` is destination port? to this port...
`uid` is app that's allowed to listen on the port, so app with UID 21212 can ask for redirect to app UID 81728?
new IP is 127.0.0.1?

**Comment by licaon-kter** [comment]
Via ssh (openssh server in Termux) yields:
```
$ am start -a eu.faircode.netguard.START_PORT_FORWARD -n eu.faircode.netguard/eu.faircode.netguard.ActivityForward --ei protocol 6 --ei source 53 --ei target 5353 --ei uid 10447
Starting: Intent { act=eu.faircode.netguard.START_PORT_FORWARD cmp=eu.faircode.netguard/.ActivityForward (has extras) }
java.lang.SecurityException: Permission Denial: startActivity asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
        at android.os.Parcel.readException(Parcel.java:1553)
       at android.os.Parcel.readException(Parcel.java:1505)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2475)
        at com.android.commands.am.Am.runStart(Am.java:766)
        at com.android.commands.am.Am.onRun(Am.java:305)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
```

**Comment by M66B** [comment]
Only TCP (6) and UDP (17) have ports.
source is the port to redirect
target is where to redirect it to
uid is the app for which the port is not redirected.
The target IP if always local host (127.0.0.1 for IPv4 and ::1 for IPv6.

Regarding the crash: I don't have this with adb. Do you have multiple user accounts on your device?

**Comment by licaon-kter** [comment]
No other profile created.

At first NetGuard was not enabled, but it yields the same when enabled too.

**Comment by M66B** [comment]
I don't know why this happens. It works from adb.

**Comment by licaon-kter** [comment]
```In order to use adb with a device connected over USB, you must enable USB debugging in the device system settings, under Developer options.```
Might be a bit of OCD, but it feels like a security seal has been breached to have Developer Options activated, since most of the time (most of ROMs) it can't be deactivated.
