### ISSUE TITLE
Miracast/Wifi-direct crashes Netguard 0.82beta

### ISSUE THREAD

**Issue by thunderduster** [M66B/NetGuard#274]
Tested on two Nexus 5, Netguard 0.82beta

Connecting to a Miracast-enabled LG TV:
Test A. Netguard on: I can see the TV in the casting choices, but can't connect. Sometimes the phone crashes.
Test B. Netguard on, and then I disable it: Sometimes it will do option A, sometimes option C (sometimes casts successfully, sometimes it will disconnect plus/minus crash the phone.)
Test C. Netguard off (never enabled since boot): Casts successfully.

Catlog link below. Sorry it's almost 12,000 lines. It's my first attempt at catlog.
This catlog is an exampled of "Test A", where Netguard is on, then I attempt to cast to the LG TV, but the Nexus 5 cannot connect to the TV, and then the Nexus crashes/self-reboots after 1-2 minutes.
https://gist.github.com/thunderduster/62ade162efc4466d5f58

**Comment by M66B** [comment]
Unfortunately the crash is not in the logcat.

Try setting the NetGuard native log level to warning (to have less lines) and keep the logcat capture running a minute or so after the crash happened.

**Comment by thunderduster** [comment]
Ok, thanks, here is a log of a full crash cycle.
So this records trying to connect to Miracast --> device freezing --> rebooting itself at 11:51:27 --> then i try to connect to miracast again --> froze again and rebooted itself a second time at 11:55:26.
https://gist.github.com/thunderduster/08e7550124624fcd7c29

**Comment by M66B** [comment]
The 11:51 crash is caused by the Android watchdog kicking in, because things take too long. Maybe the watchdog is overly critical or things go to slow or hang.

Could you please try if you can reproduce this problem with filtering turned off in the NetGuard settings?

Which Android version is your Nexus running?

**Comment by thunderduster** [comment]
Actually one of the two Nexus 5's that I tested this on did not have filtering. The crash happened on both devices:
1st Nexus 5 (v6.0.1, MMB29Q): Netguard 0.82beta with filter on.
2nd Nexus 5 (v6.0.1, MMB29S): Netguard 0.75 from the playstore (so no filter).

**Comment by M66B** [comment]
If you have logging enabled, try disabling it and see if things improve.

**Comment by thunderduster** [comment]
Logging wasn't disabled on the second Nexus 5 (Netguard 0.75) that crashed.

**Comment by M66B** [comment]
http://forum.xda-developers.com/showpost.php?p=65135350&postcount=1158

**Comment by thunderduster** [comment]
The crashes also occurred on both Nexus 5's using version 0.83beta.

**Comment by M66B** [comment]
@thunderduster please provide a logcat capture using adb from your PC, so I can look into it.

**Comment by thunderduster** [comment]
https://gist.github.com/thunderduster/077a3f6c10036f048037
Nexus 5 (v6.0.1) using version 0.83beta.
It's worth noting that my Nexus 5 felt "less" frozen than version 0.82beta. It still crashed on both devices, but I could at least flick around the homescreen. I couldn't access the Netguard app though.

One Nexus 5 had filter traffic enabled. The logcat is from that one.
The other Nexus 5 had no filter traffic.

**Comment by M66B** [comment]
I am glad the responsiveness improved, but the watchdog is still killing android.display:

```
02-04 08:04:39.936   780  1262 I Watchdog_N: dumpKernelStacks
02-04 08:04:40.051   780  1262 W Watchdog: *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on display thread (android.display)
02-04 08:04:40.051   780  1262 W Watchdog: display thread stack trace:
02-04 08:04:40.051   780  1262 W Watchdog:     at android.media.RemoteDisplay.nativeDispose(Native Method)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.media.RemoteDisplay.dispose(RemoteDisplay.java:113)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.media.RemoteDisplay.dispose(RemoteDisplay.java:92)
02-04 08:04:40.051   780  1262 W Watchdog:     at com.android.server.display.WifiDisplayController.updateConnection(WifiDisplayController.java:572)
02-04 08:04:40.051   780  1262 W Watchdog:     at com.android.server.display.WifiDisplayController.retryConnection(WifiDisplayController.java:553)
02-04 08:04:40.051   780  1262 W Watchdog:     at com.android.server.display.WifiDisplayController.-wrap13(WifiDisplayController.java)
02-04 08:04:40.051   780  1262 W Watchdog:     at com.android.server.display.WifiDisplayController$20.run(WifiDisplayController.java:935)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.os.Handler.handleCallback(Handler.java:739)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.os.Looper.loop(Looper.java:148)
02-04 08:04:40.051   780  1262 W Watchdog:     at android.os.HandlerThread.run(HandlerThread.java:61)
02-04 08:04:40.051   780  1262 W Watchdog:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-04 08:04:40.051   780  1262 W Watchdog: *** GOODBYE!
```

there is not much relevant NetGuard logging before this:

```
02-04 08:03:13.326  3564  3958 W NetGuard.JNI: TCP unknown session from 192.168.0.231/54525 to 23.21.75.243/443 uid -1
02-04 08:03:29.472  3564  3958 W NetGuard.JNI: TCP unknown session from 192.168.0.231/45336 to 23.21.75.243/443 uid -1
02-04 08:04:31.576  3564  3958 E NetGuard.JNI: recv error 104: Connection reset by peer
02-04 08:04:31.949  3564  3958 E NetGuard.JNI: recv error 104: Connection reset by peer
```

which could me that NetGuard was started later than the cast and is ignoring/killing existing connections. It would be quite stupid if the watchdogs kills the display process for this reason (and can be considered as a bug in Android, because no application or system component should assume a perfect internet connection).

It is hard to pinpoint the exact problem with out the ability to cast myself.

**Comment by thunderduster** [comment]
Ok, just let me know if there's anything I can do to help.
Temporarily disabling Netguard allows Miracast to work, so at least there's that.

**Comment by M66B** [comment]
For reference: https://en.wikipedia.org/wiki/Miracast

**Comment by M66B** [comment]
Can you please install this version and allow 'mediaserver'?
http://www.netguard.me/NetGuard-v0.84-beta-2016020501-all-release.apk

The filter rules are changed, so better export, uninstall, install this version and import to prevent trouble.

**Comment by thunderduster** [comment]
version 0.85 = success!
Miracast is working perfectly on both of my Nexus 5's.
Thanks!

**Comment by M66B** [comment]
Great!
