### ISSUE TITLE
Options for local network access

### ISSUE THREAD

**Issue by thunderduster** [M66B/NetGuard#276]
An enhancement idea: An option to allow a blocked app to access its local network.

For instance, I'd like to block my file explorer from access the internet, but I'd like to retain it's ability to access my local NAS.

**Comment by licaon-kter** [comment]
https://tools.ietf.org/html/rfc1918

**Comment by M66B** [comment]
This can be done by blocking internet access for the application (main icon rules) and make an exception in the application access list for your NAS.

**Comment by licaon-kter** [comment]
So https://github.com/M66B/NetGuard/commit/1b0b7819b1bf5488b9473ca9b0f80f506821a1ee and  

Why does [Connectbot](https://github.com/connectbot/connectbot) connect even if LAN is toggled off?

**Comment by M66B** [comment]
I don't understand the question/remark, so please explain in more detail.

licaon-kter <notifications@github.com> schreef op 31 maart 2016 13:28:57 CEST:

**Comment by licaon-kter** [comment]
Connectbot not allowed -> no connection to LAN address
Connectbot allowed but LAN toggled **off** -> **connection** to LAN address

**Comment by M66B** [comment]
That is not how this setting works, it is for allowing, not blocking. So block the application and allow LAN is what will work. Basically enabling the setting will set the LAN outside the VPN, disabled is how everything was before (this is why this setting is disabled by default).

licaon-kter <notifications@github.com> schreef op 31 maart 2016 13:40:26 CEST:

**Comment by licaon-kter** [comment]
Ok, so, Connectbot not allowed:
* `filter off`+ `LAN off` -> no connection
* `filter off`+ `LAN on` -> connection
* `filter on`+ `LAN off` -> no connection
* `filter on`+ `LAN on` -> no connection
