### ISSUE TITLE
Hosts lists

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#277]
I find [uBlock origin](https://github.com/gorhill/uBlock/tree/master/assets/thirdparties) / [uMatrix](https://github.com/gorhill/uMatrix/tree/master/assets) ones pretty ok, listed below for convenience. 

HOSTS format:
* [Dan Pollock’s hosts file‎](http://someonewhocares.org/) -> [raw list](http://someonewhocares.org/hosts/hosts) 
* [hpHosts’s Ad and tracking servers‎](http://hosts-file.net/) -> [mirrrors](http://hosts-file.net/?s=Download) 
* [Malware Domain List‎](http://www.malwaredomainlist.com/) -> [raw list](http://www.malwaredomainlist.com/hostslist/hosts.txt) 
* [MVPS HOSTS‎](http://winhelp2002.mvps.org/) -> [raw list](http://winhelp2002.mvps.org/hosts.txt) 

Just domains format
* [Long-lived malware domains](http://malwaredomains.lehigh.edu/) -> [raw list](http://mirror1.malwaredomains.com/files/immortal_domains.txt) 
* [Malware domains‎](http://malwaredomains.lehigh.edu/) -> [raw list](http://mirror1.malwaredomains.com/files/justdomains) 

Can be customized
* [Peter Lowe’s Ad server list‎](http://pgl.yoyo.org/ads) -> [raw list](http://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=)

**Comment by M66B** [comment]
AdAway host sources: https://github.com/Free-Software-for-Android/AdAway/wiki/HostsSources

**Comment by licaon-kter** [comment]
Some ideas:
* multi check box selector, just like the home Wi-Fi?
* (it will be asked) can that list be expanded by the user (add -> new checkbox) or that would need an actual **hosts list view** with such controls? 
* can the local imported list be additive to all the downloaded hosts instead of replacing them?
* can the lists be numbered?
* (see above) can you add a `blocked by list X` to the host pop-up in the log/app details? so you know which list blocked it; although if the lists get concatenated and treated as one internally by NetGuard this might not be possible.

**Comment by M66B** [comment]
The idea was to do this on the netguard.me website, so that adding new hosts files will not require an application update.

I see two new feature requests:

* Optionally concatenate locally imported hosts files
* Add notifications for blocked domains (there are none at all currently)

Please create issues for these, since this issue is only about collection hosts files.

**Comment by licaon-kter** [comment]
> The idea was to do this on the netguard.me website
> so that adding new hosts files will not require an application update.

You'll have a list of URLs there that will populate the dialogue?

**Comment by M66B** [comment]
The dialogue will be on netguard.me, not in the application.

**Comment by licaon-kter** [comment]
Do detail more, as I still don't get the process exactly. :)

**Comment by M66B** [comment]
You will select which hosts lists you want on netguard.me.

If you do this from a device with NetGuard running, the custom URL for the selected lists will be automatically configured in NetGuard as hosts URL (so no manual entering).

There will be a option to start the browser from NetGuard tp navigate to the netguard.me configure page.

Maybe this will be a pro feature.

**Comment by licaon-kter** [comment]
So the site (so I hope a JS that runs locally in the browser only and not on your server) generates a custom URL which commands NetGuard to load X, Y and Z host lists?

I ask these since:
* privacy concerns (server logging; who loads what list)
* list MITM security since this is not implemented yet https://github.com/M66B/NetGuard/issues/195
* site access eg. might get blocked by the Golden Shield

**Comment by M66B** [comment]
It will run on the server and if you don't like it, you can always use your own URLs/files.

**Comment by licaon-kter** [comment]
Ok, so the option to import and/or add one or multiple URL stays in place. Great.

**Comment by M66B** [comment]
Yes, of course.

**Comment by M66B** [comment]
If you should have to point to one file which netguard.me should provide, which one would it be?

**Comment by licaon-kter** [comment]
Been using https://github.com/stevenblack/hosts (~800kb) all this time without issues.

```
Currently the hosts files from the following locations are amalgamated:
* The Adaway hosts file, updated regularly.
* MVPs.org Hosts file at http://winhelp2002.mvps.org/hosts.htm, updated monthly, or thereabouts.
* Dan Pollock at http://someonewhocares.org/hosts/ updated regularly.
* Malware Domain List at http://www.malwaredomainlist.com/, updated regularly.
* Peter Lowe at http://pgl.yoyo.org/adservers/, updated regularly.
```

**Comment by M66B** [comment]
http:://www.netguard.me/hosts now serves https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts plus:
```
# NetGuard extras
0.0.0.0 reports.crashlytics.com
0.0.0.0 settings.crashlytics.com
0.0.0.0 e.crashlytics.com
```

**Comment by enervated** [comment]
The Adaway hosts file is considered to be "updated regularly?" It hasn't been updated in almost two years.

# Changelog:
# **2014-05-18** Now with a valid SSL certificate available at https://adaway.org/hosts.txt
# 2013-03-29 Integrated some hosts from
#            http://adblock.gjtech.net/?format=hostfile
# 2013-03-14 Back from the dead

**Comment by licaon-kter** [comment]
Last upate 6 months ago: https://github.com/Free-Software-for-Android/AdAway/blob/master/hosts/hosts.txt
