### ISSUE TITLE
Add notifications for blocked domains

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#279]
Like from what source does this rule to block this host comes.

**Comment by M66B** [comment]
I am not sure if this will be useful, since the application for which the domain was blocked in unknown.
(this is because the root user does the DNS requests)

**Comment by licaon-kter** [comment]
The application does not matter, but if I start a browser and I can't access netguard.me, I go to the app details in NetGuard, see the domain in red, touch the domain and the pop-up should say:
* netguard.me
* blocked by list #7
* allow for this app
* block for this app
* reset (to general rule)

**Comment by M66B** [comment]
Domain blocking cannot be done per application.

Domain blocking is very efficient, since there are no IP packets sent besides the DNS packets, that is the reason I am keeping it for the time being.

Note that domain blocking <> IP filtering (also based on domains with a lot of trickery, but it basically stays IP filtering).

**Comment by licaon-kter** [comment]
I don't even see in the log the domain that was blocked, so yeah, not possible then?

Feel free to close it if there is no way,

**Comment by M66B** [comment]
In the log there should be blocked 'qname' entries.

**Comment by licaon-kter** [comment]
I don't see any, not in log, not in app detaills, the browser just yields an error like "dns failed check firewall".

**Comment by M66B** [comment]
Works for me.
Look for root UDP messages from vpn to dns.
The last line shows the blocked domain.

**Comment by licaon-kter** [comment]
I did not see those, Samsung 5.0.2 at least, just apps.
I'll retest later with the Xperia.
