### ISSUE TITLE
Option to import multiple hosts files

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#281]
User could just concatenate it herself (to the same effect), although doing this on a mobile device might be annoying.

**Comment by M66B** [comment]
This will be low priority.

**Comment by licaon-kter** [comment]
Loading from file clears database and puts only those from file and loading from link clears database and puts only those from link downloaded file, right?

Is NetGuard keeping unique hosts or does it keep duplicates? The thing is one can load infinite hosts files and/or concatenate infinite downloads, but if you don't keep duplicates it's kinda ok.

**Comment by M66B** [comment]
"*Loading from file clears database and puts only those from file and loading from link clears database and puts only those from link downloaded file, right?*": yes

"*Is NetGuard keeping unique hosts or does it keep duplicates?*": unique host names only.

**Comment by licaon-kter** [comment]
Looks like the last import text is not removed from file/URL import after URL/file import.

**Comment by M66B** [comment]
That is by design. They are separate now.

**Comment by licaon-kter** [comment]
Yes, but since only one is applied, only that one should be visible.

**Comment by M66B** [comment]
Currently you are right, but as soon as merging is allowed not anymore.

**Comment by licaon-kter** [comment]
Right, I'm not sure how the merging workflow will go though.

**Comment by M66B** [comment]
I am not going to implement this, since IMO we can expect from non Play store users to know how to merge files (for example with a script).

**Comment by licaon-kter** [comment]
Yeah, it was complex since you need to keep track of what was imported and more buttons to clear, merge,  etc.
