### ISSUE TITLE
On-screen notification when HOSTS file successfully downloaded/applied

### ISSUE THREAD

**Issue by enervated** [M66B/NetGuard#285]
In [0.83-1](https://github.com/M66B/NetGuard/releases/download/0.83/NetGuard-v0.83-beta-2016020401-all-release.apk), when a hosts file is downloaded via URL, a screen notification showing the URL is presented. Please consider a screen notification to indicate if/when the hosts file has actually been downloaded and applied successfully. (If this is what the current notification is conveying, it's not clear to me and I apologize.)

**Comment by M66B** [comment]
There is already a last downloaded date/time in the preference summary of the download host file preference.

**Comment by enervated** [comment]
No "last downloaded" date/time is showing for me. It simply says "Download hosts file" after I've attempted to download.

**Comment by licaon-kter** [comment]
Can you try with 0.82-beta3: NetGuard-v0.82-beta-3-2016020303-all-release.apk ?

Can you try with another list?

Do you have another firewall like AFWall that might block NetGuard?

**Comment by enervated** [comment]
I reverted to the default hosts URL (http://www.netguard.me/hosts), and only then did I get a progress dialog and a "Last download" date/time.

When I had been using my own URL (hosted on my own server), I got nothing except a screen notification that showed the URL. No progress dialog, no "Last download" date/time. The URL is valid, however, and I tested it in a browser on the same device.

After switching back to my own URL, the progress dialog and date/time began appearing correctly.

I have no other firewall installed. If the download was being blocked, I would expect NetGuard to tell me that the download timed out, not just sit and spin and/or put up a confusing notification.

**Comment by M66B** [comment]
There is only a (percentage) progress dialog if the server sends a content length header. I specially crafted a script to skip gzip compression and to send a content length header for the hosts file on netguard.me.

**Comment by enervated** [comment]
Thanks. But now that I've reverted to the same URL I tried originally (which I will not post publicly), I am getting a progress dialog. So it must be sending the header you mention... I don't understand why it was not working before.

I was not getting any errors; just as I've said, a screen notification showing the URL itself and nothing more. I've tested with intentionally-bad URLs and I do get an error in such a case.

**Comment by M66B** [comment]
Errors are properly handled and you'll get notified of errors.

**Comment by licaon-kter** [comment]
> So I am not a fool who asked for something needless

Don't get enervated :), I was just trying to weed out some possible issues, like the other day one user was [missing the 'import hosts' option](http://forum.xda-developers.com/showpost.php?p=65135482&postcount=1159) completely, after another update it was there, so...

**Comment by enervated** [comment]
I understand. Thank you. It was just a bit frustrating since I had no way of knowing that a date/time should appear. It was **not **appearing for me! Nor were any errors appearing.
