### ISSUE TITLE
Option to block ICMP

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#286]
Steps:
* install [Termux](https://github.com/termux/termux-app)
* **allow** Termux in NetGuard (just for the first run when it updates packages and such)
* exit Termux and **block it** in NetGuard
* start Termux 
* `ping blocked-domain-name.tld` (pick one from your current hosts list)
* see instant unknown domain error
* `ping valid-domain.tld`  (pick an unusual domain to avoid cache)

What one would expect to see:
* instant unknown domain error, since app is blocked all of it's requests should be ignored

What one sees:
* ping gets to know the domain host IP
* log is full of blocked ICMP4 packets to that IP

**Comment by M66B** [comment]
* ICMP (ping) is always allowed
* DNS requests are done by root

If the pinged address is not in your hosts file, then please provide a logcat, so I can look into the ICMP issue.

**Comment by licaon-kter** [comment]
Not sure I follow, ok,  got the DNS request, not a bug then.

But, ICMP is always permitted to non-blocked hosts even for blocked apps?

**Comment by M66B** [comment]
NetGuard can current only block UDP and TCP (protocol 17 and 6).
ICMPv4 and ICMPv6 (protocol 1 and 58) are currently always being allowed.

As a sidenote, Android accept no incoming connections, so NetGuard is design to process outgoing traffic only.

**Comment by licaon-kter** [comment]
> As a sidenote, Android accept no incoming connections,
> so NetGuard is designed to process outgoing traffic only.

Not sure I follow, I can run local servers (FTP/SFTP/SSH/etc)...

**Comment by M66B** [comment]
Running servers is not something people often do and can't be done on privileged ports (port number < 1024).

You can create an issue for blocking incoming traffic if you like.

**Comment by licaon-kter** [comment]
Not sure if needed, if Android drops packets on ports where no server is listening that's ok.
A new settings just makes it more complex, if you allow an app that's it.

**Comment by M66B** [comment]
NetGuard drops all packets it doesn't have a session for, so no incoming traffic which was not preceded by outgoing traffic is allowed anyway.

**Comment by M66B** [comment]
ICMP can be blocked after #284
