### ISSUE TITLE
Netguard doesn't turn on after flashing system partition

### ISSUE THREAD

**Issue by malitech** [M66B/NetGuard#290]
Hello,
I found another bug. After flashing the latest system image of nexus 5, if the filtering was turned on before flashing the system partition, netguard doesn't turn on either through the widget or through the application. It turns on only after turning off filtering from settings.

**Comment by M66B** [comment]
You should know by know that 'it doesn't work' is too little to work with, so please provide a logcat.

**Comment by malitech** [comment]
I let you know how the bug appears, so I didnt include a logcat. I thought you might not need it. Moreover I checked it with 0.83-beta with pro enabled. ;) Cant check the same with 0.84-beta.

**Comment by malitech** [comment]
Also because you are using the same device as mine. :)

**Comment by M66B** [comment]
Even then I expect you to do a little yourself.
I am not going to flash the system image when there is no need.

**Comment by malitech** [comment]
I didnt mean you had to do that. I just thought you could know just by that info bro. Why are you so mad at me?

**Comment by malitech** [comment]
[logcat.txt](https://github.com/M66B/NetGuard/files/120292/logcat.txt)

**Comment by M66B** [comment]
I am not mad (not in the sense you mean ;-)
I just need a logcat to look into this, like for most issue.
There is no trivial explanation for this, other than that Android stores info in the system partition, for example if an application was allowed to use the VPN service.

**Comment by malitech** [comment]
I understand. I've included it now. :)

**Comment by M66B** [comment]
The problem seems to be that there is no system DNS address.
This problem has been fixed in the latest beta.

**Comment by M66B** [comment]
```
DNS using=ip6-localhost/::1
```

**Comment by malitech** [comment]
See, this is exactly why I didn't include a logcat. I thought you would ask me to try the latest 0.84 beta. :)

I tried to turn it on before turning on the wifi. So, would it have worked if my wifi was turned on at first? Just to understand.

**Comment by malitech** [comment]
I think the bug might repeat if network is not turned on. So will I be unable to turn on netguard without turning on the network first in case filtering is on?

**Comment by malitech** [comment]
When netguard is on, turning on filtering from settings will disable netguard. Checked with a clean install with network off. You can check this on  v0.84 on your phone.

**Comment by M66B** [comment]
Can you please check if this build fixes the problem?
http://www.netguard.me/NetGuard-v0.84-beta-2016020501-all-release.apk

**Comment by malitech** [comment]
![screenshot_20160207-004423](https://cloud.githubusercontent.com/assets/7058205/12868799/42fe8c62-cd34-11e5-9cdc-22f024c41c13.png)
The problem seems to be gone but the widget shows like this.

**Comment by M66B** [comment]
A logcat might reveal why.

**Comment by malitech** [comment]
[logcat.txt](https://github.com/M66B/NetGuard/files/120410/logcat.txt)
Already on it.

**Comment by M66B** [comment]
There is nothing in the logcat what can explain this, but maybe the problem happened earlier.
Please set the native log level to error and try again to capture a logcat.

Maybe you need to add the widget again, because of the the system partition flash.

**Comment by malitech** [comment]
I actually removed netguard before installing the version you sent me.

Let me capture it, wait.

**Comment by malitech** [comment]
Oh, the widget started working.

**Comment by M66B** [comment]
After an update/upgrade it can take a while until Android has done all the necessary things in the background.

Anyway, I am glad this issue has been resolved.

BTW, there is a new beta, which some more fixes available than the version published here before.

**Comment by malitech** [comment]
Thanks a lot buddy. :)

**Comment by malitech** [comment]
How do I find netguard using UID?

**Comment by M66B** [comment]
I don't understand the question, so please explain in more detail.

**Comment by malitech** [comment]
How can I find netguard in the list of apps? Netguard isn't listed anymore, so how to get to it?

**Comment by malitech** [comment]
I mean inside the netguard application. How to access the hidden entry?

**Comment by M66B** [comment]
This has been explain on XDA recently.

**Comment by M66B** [comment]
Simply said: NetGuard will not list itself anymore.
Reason: NetGuard need internet access to resolve domain names, so turning NetGuard off for itself is pointless.

**Comment by malitech** [comment]
I know. I'm just curious to see the listing. I found netguard's uid from the logcat (10152) and it didn't list anything.

**Comment by malitech** [comment]
So can you tell me please? :)

**Comment by licaon-kter** [comment]
Why do you need it?

**Comment by malitech** [comment]
Just to know bro. ^^ Is it wrong to know? :)

**Comment by malitech** [comment]
Do you know how?

**Comment by licaon-kter** [comment]
TotalCommander -> random file properties -> change owner -> scroll to NetGuard

Ok, then what?

**Comment by M66B** [comment]
NetGuard is not listed in NetGuard anymore and there is nothing you can or should do about it, so I don't understand what you want to do/know.

**Comment by malitech** [comment]
Is there a way to search netguard inside netguard app?

**Comment by M66B** [comment]
No, since NetGuard is not listed in NetGuard anymore.

**Comment by M66B** [comment]
Why do you want to search for NetGuard anyway?

**Comment by malitech** [comment]
Licaon, don't be hostile. You act like there are secrets.

I just wanted to see the listing. Nothing else.

**Comment by malitech** [comment]
Even if I search, what would I even be able to do? I simply asked. I'm sure there could be a way.

And what if someone doesn't want to use IP filter and want to block netguard? :)

**Comment by malitech** [comment]
Also, you usually share everything. You even highlighted that netguard has no internet permission before. So, why is this question wrong? :/

**Comment by licaon-kter** [comment]
I'm not hostile, I understood what you meant the first time you've asked for this, BUT you've got your answer.

Read the source code, if you have any doubts, hey fork it and maintain your version just to be sure, even root your device and install AFWall+ to control NetGuard... oh wait NetGuard is a no-root firewall :-|

**Comment by malitech** [comment]
No, I haven't got it. ^^

I don't know how to read the source. :) That's why I asked the developer. It's pretty obvious. ;)
