### ISSUE TITLE
Some crashes in 0.84/0.85

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#291]
Xperia 5.1.1, no root 0.83/0.84: https://gist.github.com/licaon-kter/60232d28f3720f0dd112

Xperia 5.1.1, root, excepted in XPrivacy, 0.85: https://gist.github.com/licaon-kter/948a2abe0071cdde8459

**Comment by M66B** [comment]
First log:

```
Caused by: android.os.TransactionTooLargeException
```

This is caused by the kernel running out of memory for binder transactions.

Second log: did you navigate away from the settings screen while a download was in progress?

**Comment by licaon-kter** [comment]
> This is caused by the kernel running out of memory for binder transactions.

That's a 2Gb device with at least 500Mb of free memory almost all the time, if that's what you mean.

> Second log: did you navigate away from the settings screen while a download was in progress?

IIRC, no, I used a local hosts.txt.

**Comment by M66B** [comment]
The amount of memory the device has doesn't matter. The kernel allocates a fixed size buffer of just 1 MB for binder transactions. If it is full for whatever reason, there will be trouble. NetGuard doesn't play a role in this and I am quite sure you will have trouble with other applications as well.

```
at eu.faircode.netguard.ActivitySettings$11.onPostExecute(SourceFile:813)
```
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L813

You were importing hosts indeed, so the question is, did you navigate away from the settings screen soon after you started the import?

**Comment by licaon-kter** [comment]
That my be, yes, sometimes I don't have notifications enable so I'm not sure if it loaded or not, I wait a bit and then go somewhere else.

I'll keep an eye out for it, maybe retest with hosts re/import & re/download.

**Comment by M66B** [comment]
I am already fixing this, so no need to keep an eye on it. I was just trying to confirm the problem.

**Comment by licaon-kter** [comment]
And another in 0.87-beta2

https://gist.github.com/licaon-kter/b62e1d2226f73e041209

**Comment by M66B** [comment]
```
android.app.ServiceConnectionLeaked: Activity eu.faircode.netguard.ActivityMain has leaked ServiceConnection
```
This is the IAB connection, which will be properly unbound, unless there is another crash.

**Comment by licaon-kter** [comment]
And another while I was reporting these and did not touch Netguard at all, it went poof, no crash dialogue at all

https://gist.github.com/licaon-kter/fbb305fe36a9992fee53

**Comment by M66B** [comment]
Since there is
```
I NetGuard.Main: Destroy
```
either you or Android finished the NetGuard UI.

**Comment by licaon-kter** [comment]
Oh, right, so I saw the key missing from status bar (aka VPN not connected anymore), so I switched to NetGuard only to see a black window, then, as you remarked, I killed it (I have long press back button for that).

**Comment by licaon-kter** [comment]
Regarding IAB, I guess it hopes there are some Google services available while there are none or there is some [trickery](http://repo.xposed.info/module/xeed.xposed.dngmod) involved.

**Comment by M66B** [comment]
IAB in NetGuard is optional, so no worries.

**Comment by licaon-kter** [comment]
0.87-beta3 

Still IAB? https://gist.github.com/licaon-kter/0b9d08f6140356c15801

**Comment by M66B** [comment]
This was probably not a normal close.

**Comment by licaon-kter** [comment]
Xperia 5.1.1, no root, v0.87-beta-2016021102

Went to Settings to enable journal and disable Block hosts, hitting back arrow yield a crash: https://gist.github.com/licaon-kter/0f0b933ae7bc3cac9623

**Comment by M66B** [comment]
This is not a NetGuard problem, but lack of binder memory space.
The binder has a fixed kernel buffer of about 1 MB shared between all binder transactions.

Are you running XPrivacy?

**Comment by licaon-kter** [comment]
no-root

**Comment by M66B** [comment]
Is there anything here that rings a bell?
http://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception

Maybe it can help if your provide a piece of logcat before the exception.

Can you reproduce this or is it random?

**Comment by licaon-kter** [comment]
It's random, afaics.

Regarding large data, I think I made a run on Chrome Dev install for that issue, and then switched to NetGuard to enabe those preparing to make the small clip for https://github.com/M66B/NetGuard/issues/315

**Comment by licaon-kter** [comment]
Logcat with before and after (until logcat generated that is): https://gist.github.com/licaon-kter/23ce912fb4ac40b9bf68

**Comment by M66B** [comment]
Before I look into it: is this with the version I sent you by email or with an older version?

**Comment by licaon-kter** [comment]
v0.87-beta-2016021102, as I mentioned this crash was just before me making the video on it.

I'll take a look later at the email.

**Comment by licaon-kter** [comment]
Xperia 5.1.1, no root, still on v0.87-beta-2016021102 (yeah this device has a different update policy :P)

Was ok most of the day (except these), until some pictures would not be sent, tried to open NetGuard yielded a black screen and VPN disappeared. Closed it via task manager (no root to kill it), then restarted, everything worked ok then although I did not touch the Wi-Fi/mobile connections.

NetGuard is excepted in Stamina Mode and works ok most of the time.

Logcat: https://gist.github.com/licaon-kter/266499b84664ed081436

**Comment by M66B** [comment]
There is nothing special in the logcat, so update to the latest version and see if it happens again.

**Comment by licaon-kter** [comment]
Tablet, CM13 (xposed was installed but it can't be use yet, since this is a systemless root)

Might be v0.87-beta-2016021401 or 02 (given the speed of development, maybe you need to enable full version in about screen again once you make more betas in the future)

logcat: https://gist.github.com/licaon-kter/456d151a47311cdef240

**Comment by M66B** [comment]
The is a crash in the app compat library.
I have added some code to work around it.

**Comment by licaon-kter** [comment]
Xperia 5.1.1, root, 0.89-beta

Seeing connections working only sometimes and NetGuard showing up as a black screen and I need to kill it.

What's special here is that I limited all apps in AFWall+ to VPN only (except NetGuard that is), which in my mind should work ok, at the same time I see AFWall+ popping up toasters saying it blocked connections... which should not happen.

logcat: https://gist.github.com/licaon-kter/1111f5b5a1125a717183

**Comment by M66B** [comment]
I am seeing a few times TransactionTooLargeException, which is possibly the cause of the problem. This exception might be the result of XPrivacy hooking the binder, because of some extra overhead. Try to run XPrivacy in AOSP mode to prevent the binder from getting hooked.



licaon-kter <notifications@github.com> schreef op 17 februari 2016 07:25:10 CET:

**Comment by licaon-kter** [comment]
What's the Setting for that? Reading FAQ#68: _"You can force XPrivacy 3 into AOSP mode using the main settings. "_

**Comment by M66B** [comment]
Depending on the Android version you will need to create a file to force AOSP mode (this is due to SELinux).


licaon-kter <notifications@github.com> schreef op 17 februari 2016 09:39:34 CET:

**Comment by licaon-kter** [comment]
So there is no Settings option to just check and reboot?

I'll need to edit **build.prop** with `xprivacy.options=ignoreselinux` ?

**Comment by M66B** [comment]
Yes, that is what the FAQ also says.
After that you can see in the about dialog if it works (the message about compatibility mode should be gone).

licaon-kter <notifications@github.com> schreef op 17 februari 2016 09:49:12 CET:

**Comment by licaon-kter** [comment]
Ok, now the compatibility text is gone from the About screen.

**Comment by M66B** [comment]
Please let me if you have the issue again.

licaon-kter <notifications@github.com> schreef op 17 februari 2016 10:41:39 CET:

**Comment by licaon-kter** [comment]
So...

0.89beta, Xperia 5.1.1, root, Xprivacy in AOSP mode and excluded, (exited Wi-Fi range and it switched to mobile; I guess, it was the only change), poof: https://gist.github.com/licaon-kter/5c5da02e4d2690b35f62

0.89beta, CM13, root, Xposed installed w/o any module, noticed VPN down after some time: https://gist.github.com/licaon-kter/546e0527ed328623a87e

0.88beta3, Xperia 5.1.1, no-root, noticed VPN down after some time, log had no crash :(

**Comment by M66B** [comment]
The first crash is caused by an Xposed module with the package name serajr.xx.lp (might be obfuscated).

The other logcat reveals a problem with IAB, which I will fix, but I don't think it is the cause of the problem, so please keep a watch on this.

**Comment by licaon-kter** [comment]
It's [this module](http://forum.xda-developers.com/crossdevice-dev/sony/xposed-serajr-xperia-xposed-lp-v1-0-27-t3094251), I'll keep an eye on it since I find it pretty useful. :(

**Comment by licaon-kter** [comment]
Xperia 5.1.1, root, Xprivacy excluded, no Google Play store app or Services, modified *build.gradle* from `0.90-beta` to `0.90-my` (so I can see the PRO screen popup) an the date to 20, trying to access Settings yields a crash: https://gist.github.com/licaon-kter/3994d5028d5b4d485ada

All other accessible features look ok.

**Comment by M66B** [comment]
I don't know what is wrong here. In my build I don't have this problem.

It looks like this settings was not found:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L350

But it is present:
https://github.com/M66B/NetGuard/blob/master/app/src/main/res/xml-v14/preferences.xml#L232
https://github.com/M66B/NetGuard/blob/master/app/src/main/res/xml-v21/preferences.xml#L232

Try cleaning and rebuilding the project.

**Comment by licaon-kter** [comment]
Just removing `-beta` worked ok though, I see how `-my` yields in another clean build.

**Comment by licaon-kter** [comment]
0.96, another https://gist.github.com/licaon-kter/8208f528698761d369d9 while messing around with https://github.com/M66B/NetGuard/issues/345

**Comment by licaon-kter** [comment]
0.96, ore of the same I guess: https://gist.github.com/licaon-kter/03947e21354691228c13

**Comment by M66B** [comment]
Yes, the binder is out of memory here

licaon-kter <notifications@github.com> schreef op 28 februari 2016 10:39:02 CET:

**Comment by licaon-kter** [comment]
On connection type change: https://gist.github.com/licaon-kter/bc3416b185bdda57cf78

**Comment by licaon-kter** [comment]
Consider this scenario
* lock device
* battery optimisation kicks in (NetGuard/AFWall/chat app excepted)
* but I do have `only use network once in a while` type of battery optimisation

Now, after some time (10minutes, hours whatever), switch from screen off to screen on and unlock device, what does NetGuard do:
* Does it have (many) things to write in logs?
* Does it have a bunch of FD's opened ?
* Connections that suddenly need to work?
* Is the app list refresh via `getInstalledApplications` ?
* If so are the icons reloaded?
* Does NetGuard use mostly [intents to send this data around](https://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception/12809171#12809171)?

I believe (ummm around) here lies the answer.

**Comment by M66B** [comment]
* Battery optimization disables NetGuard logging and logging will not be queued.
* There are not a bunch of FD's to be opened.
* New connections are accepted as always
* The application list is refreshed on turning on the screen, but this list is cached by Android locally
* Icons are reloaded on demand (when becoming visible)
* NetGuard sends only very small amounts of data from the background to the foreground

So, no answer here.

**Comment by licaon-kter** [comment]
Regarding the FDs I thought about: https://github.com/M66B/NetGuard/blob/00edcd03e8c240729300907934fad9b5a6b89969/app/src/main/jni/netguard/netguard.c#L67

Are these flushed on connection cut off?

**Comment by M66B** [comment]
fd's are freed on socket close, which mostly happen due to local/remote close or idle timeout.
There are a few other reasons, for example when you block an existing connection.

**Comment by licaon-kter** [comment]
Xperia 5.1.1, rooted, still having a go at this and uninstalled Xposed, just in case.

A few days ago I saw this crash again when doing some specific thing, so today I repro it.

Steps:
* screen is always on (NetGuard is exempted from battery optimisations anyway)
* had [Conversations](https://github.com/siacs/Conversations) on just so it can ping the servers and re/connect and so on
* use [Kore](https://github.com/xbmc/Kore) to control a LAN Kodi instance (Wi-Fi only in NetGuard)
* send a command with Kore every few minutes (here I just instruct it to play something random from a share)
* sometimes disable Wi-Fi so (only) Conversations connects on mobile
* once it's online switch back to Wi-Fi
* do this for an hour or so
* until you can't reach the Kodi instance

Then you might open NetGuard (to a crash dialogue) or switch to mobile data (just to see the key in the status bar disappear aka VPN destroyed).

After the crash you start Netguard, and everything works again, but so many VPN restarts?!?

Logcat: https://gist.github.com/licaon-kter/68948f285554d92ca7c1

**Comment by M66B** [comment]
Maybe one of the applications if using an unreasonable amount of binder memory space and NetGuard suggested from it.

Did you try this with the latest beta version, which caches the package info?

**Comment by licaon-kter** [comment]
Like the log says, it's on 2.7 (https://github.com/M66B/NetGuard/commit/fffc2947253c83a577c085d0d9327bcb4da5dc78).

How would I detect that?

**Comment by M66B** [comment]
Detect what?

**Comment by licaon-kter** [comment]
If another app is at fault, like you said.

**Comment by M66B** [comment]
I don't know if there is a way to see what the binder memory space is being used for.

**Comment by licaon-kter** [comment]
I was about to start another test session, same build as above, culled 2 more background apps just in case.

But, to my surprise internet was already not working.

Log was a repeating sequence:
```
D NetGuard.JNI: Loop thread af14e000
D NetGuard.JNI: sessions ICMP 0 UDP 36 TCP 1 max 37/3276 idle 0 sdk 22
W NetGuard.JNI: pselect EBADF
```
(Wasn't this fixed for #316 and #351? Or not a bug actually?)

Opening NetGuard yielded another surprise a short black screen followed by: https://i.imgur.com/Hxen7NA.jpg that resisted several pulls to refresh, also the first symbol on the left (down arrow), on scroll, was replaced with a flashing random (app) icon instead.

I left it like this for some 30 minutes, as I had to do something else.

Later opened *aLogCat* again to see a repeating:
```
D NetGuard.JNI: Loop thread af14e000
D NetGuard.JNI: sessions ICMP 0 UDP 663 TCP 2 max 665/3276 idle 0 sdk 0
D NetGuard.JNI: pselect ready 143
```

Opening NetGuard to see that now icons are correct again, and testing other apps actually it started to let the internet work after some time. When I saw this I tried to open NetGuard and now it finally crashed.

Logcat with plenty of new stuff: https://gist.github.com/licaon-kter/028e2f38e73847555db5

**Comment by M66B** [comment]
This is all out of control of NetGuard.
It looks like this Android version has serious flaws.


licaon-kter <notifications@github.com> schreef op 14 maart 2016 21:55:17 CET:

**Comment by licaon-kter** [comment]
Yes, I'm pretty sure it's something with my own setup as the other (I believe identical compact version) Xperia 5.1.1 works flawlessly for months. But I still have to pinpoint what is exactly triggering this.

**Comment by licaon-kter** [comment]
I minimised the number of used apps. Switched `filter off`, so far so good.

I mentioned the no-root Xperia, I lied, it's not trouble free, although I can't access it as often to test that much, so far one glitch stands out, with `filter on` switching to mobile data will cut access to the internet.
It's not a big deal since it works otherwise, I'll try to give it some time and pinpoint what's at fault there.

**Comment by licaon-kter** [comment]
2 days without any incident what so ever, updated to 2.9 and I'll now switch `filter on` (plain, no hosts manipulation) and see how that fares.

One other good thing about `filter off` that was noted right away, app reconnection on connection change (eg. Wi-Fi to mobile or the other way around) is better/faster.
My test case is [Conversations](https://github.com/siacs/Conversations): with `filter on` it will get kinda stuck on a cycle of `server error, no connection, security error`, say after leaving a place with Wi-Fi so mobile kicked in, I would end up looking at the device 15 minutes later only to find that the app was still not connected and needing several manual forced connect/disconnect operations to connect or even stay connected (it might say connected for 3 seconds and then disconnect again). 
With `filter off`, it connects right away and stays there, it caught me by surprise to see it connected in situations where I was opening the app just so I can force it to connect, as I was used to.

**Comment by M66B** [comment]
Maybe it is worth a try to terminate all connections on reload (set the second parameter of jni_stop to true) in an attempt to improve the reconnect problem.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 02:04:15 CET:

**Comment by licaon-kter** [comment]
So I changed to `true`in [ServiceSinkhole.java](https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ServiceSinkhole.java) at lines 434, 446 and 459, is that enough?

**Comment by M66B** [comment]
For an experiment you can temporarily change all calls. If we are going to implement this for real, it needs to depend on connectivity change.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 08:43:50 CET:

**Comment by licaon-kter** [comment]
No sure where else applies though, line 421 will never be reached since I'm on SDK22

Now, with those 3, I still found it unconnected after a connection change while screen was off. Although, testing with screen on, I'm still seeing `Connecting...` much longer than with `filter off` but it does seem a bit snappier.

One question here, does this `stopNative(vpn, true)` introduces a bit of a leak each time?

**Comment by M66B** [comment]
No, there will be no leak introduced.

licaon-kter <notifications@github.com> schreef op 17 maart 2016 10:31:29 CET:

**Comment by licaon-kter** [comment]
BTW, screen off timeouts are 0.

Those `true` above are on enough, basically:
* have Conversation with an account/all accounts disconnected
* quickly do in order: switch off Wi-Fi (so it goes to mobile), toggle (an) account on, close screen

Come back after 10 minutes:
* `filter off` -> Conversation is connected
* `filter on`-> see the lockscreen notification that Conversation gave up trying to reconnect (it tries 3 times IIRC, with plenty of pauses in between)

I don't think reconnection speed is all what this is based on, as in _"it reconnects fast enough when screen turns off"_, I say this since when just walking with screen off out of Wi-Fi range the same behaviour applies.

**Comment by M66B** [comment]
So, what is exactly the change with 'true' for terminating existing connections?

licaon-kter <notifications@github.com> schreef op 17 maart 2016 11:29:04 CET:

**Comment by licaon-kter** [comment]
Maybe a faster reconnect, although with each test I'm more confused what works better though.

**Comment by licaon-kter** [comment]
Another day with `filter on`, still no `android.os.TransactionTooLargeException` in sight.
I'll start installing the other apps (I had prior) that I uninstalled, and see what stands out.

**Comment by licaon-kter** [comment]
I spoke too soon, so I'm messing around for the filter issue mentioned above, really convinced that other one of the uninstalled apps must be at fault and that i need to put `filter off` again to retest some bits, so I:
* open NetGuard 
* toggle NetGuard off
* open Settings 
* toggle `filter off`
* toggle NetGuard on

And I get a black screen and this: https://gist.github.com/licaon-kter/9c53c93bcc87c432a172

**Comment by M66B** [comment]
My guess is that your ROM is sending often/large messages internally to setup the VPN resulting in the dreaded transaction too large exception.

licaon-kter <notifications@github.com> schreef op 18 maart 2016 23:50:51 CET:

**Comment by licaon-kter** [comment]
And I'm back here (w/ 2.12), back with my setup and transactionstoolarge, although I suspected AFWall+, I just skipped its install so it looks like it's not at fault. Yay, more testing, luckily (!?) I can repro it with Kore like I mentioned before so it's just a matter of time until I can pinpoint exactly what app I disable last that might be at fault.

**Comment by licaon-kter** [comment]
Looks like the non-rooted device is not immune, internet was cut off all day. I do have an app in common, which was on my suspect list for a while so I'll see how it fares once I uninstall that.

Logcat (older crash in log, I guess with 0.98 or 2.0): https://gist.github.com/licaon-kter/c5b62e814d8c8a2c52e47f0574c5ead1

Logcat (crash today): https://gist.github.com/licaon-kter/1983e9f73b7d1f85f7e3b27ca0b313a5

**Comment by licaon-kter** [comment]
Later on the rooted device: https://gist.github.com/licaon-kter/67e8df6086bfb394821ba0954315d0ea

Internet was down, switching to Netguard yielded a black window, the log was getting huge, every milisecond it was outputting 14 lines of `W NetGuard.JNI: pselect EBADF`, then the crash above, then again EBADF and it crashed with a dialogue after some seconds later.

**Comment by M66B** [comment]
*android.os.TransactionTooLargeException* cannot be fixed from NetGuard.
This is an Android/kernel problem.

I like to see the EBADF logging however.

**Comment by licaon-kter** [comment]
> android.os.TransactionTooLargeException cannot be fixed from NetGuard.

Maybe true.
Right now my only hint is that maybe another app just pushes too many requests towards NetGuard. Say on a network switch or on a screen off->on switch.

**Comment by licaon-kter** [comment]
Full (more or less) logcat: https://gist.github.com/licaon-kter/9858ee975b38b01ca637b3811338c4cd

Notes:
* the screen was opened at 17:23
* it was a 19Mb big logcat
* it had 317589 lines with `W NetGuard.JNI: pselect EBADF`
* it chatters a lot (while stuck in black screen) about mobile connection although Wi-Fi should have been connected all the time

**Comment by M66B** [comment]
EBADF means an external connection has died, which seems to have happened in this case massively.

"*EBADF
An invalid file descriptor was given in one of the sets. (Perhaps a file descriptor that was already closed, or one on which an error has occurred.)*"
http://linux.die.net/man/2/pselect

This is outside the control of NetGuard.

**Comment by licaon-kter** [comment]
More logs from today, black screen for a while: https://gist.github.com/licaon-kter/052c3532900cb8dca3494952985c62b4

**Comment by M66B** [comment]
Same error as always:

```
android.os.TransactionTooLargeException
```

There is no use to keep posting logcat like this, since this is a Linux kernel problem and not a NetGuard problem.

**Comment by licaon-kter** [comment]
> Same error as always

I know, that's not the point. :)

**Comment by licaon-kter** [comment]
Also with `epoll()` version: https://gist.github.com/licaon-kter/967bf5c9cfdc1c54169670766fec4135

**Comment by licaon-kter** [comment]
Some parcel size from the logs, not sure if they help:
```
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 128)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2876)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3240)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 416)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 452)
E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 5400)
```

**Comment by M66B** [comment]
As explained before I cannot solve binder transaction problems, whatever the cause is.

**Comment by M66B** [comment]
Issue locked, because it can really not be solved.
