### ISSUE TITLE
Option to redirect to local proxy instead of sinkhole

### ISSUE THREAD

**Issue by JasperWeiss** [M66B/NetGuard#292]
Would it be possible to have NetGuard redirect traffic to a local proxy? So that one can use NetGuard to make apps use Tor/Orbot.

**Comment by M66B** [comment]
The latest beta has this option to forward ports to local hosts, see here for more information:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivityForward.java#L75

Note that you need to enable filtering for this.

In the near future I will add a UI for this.

**Comment by M66B** [comment]
@licaon-kter yes, but I will leave this issue open, since there is more interest in it then I assumed, justifying a nice UI for it.

**Comment by licaon-kter** [comment]
Great.

So I'll continue to write my finding here.

Now, does it work for you from a terminal? ( running `am somthingsomething' that is )

**Comment by JasperWeiss** [comment]
> Note that you need to enable filtering for this.

Would that significantly increase battery drain?

**Comment by M66B** [comment]
@JasperWeiss it will increase the battery usage, since there will be an extra IP stack running. It has been written in native code, so it is pretty efficient and the battery impact will likely be limited.

To forward traffic (either remote or locally) there needs to be an IP stack running to translate OSI level 2 messages to OSI level 3 messages, there is no other way.

**Comment by JasperWeiss** [comment]
Ok, thanks. 
Currently I'm using NetGuard to block applications that are supposed to use Orbot to prevent leaking. But some applications will just no longer work because their proxy isn't configured properly. So if NetGuard could transparently redirect their traffic through the proxy, it'd make so many things easier :)

**Comment by licaon-kter** [comment]
The command need a bit of tweaking to avoid the error `run as user -2 but is calling from user 0`

```
am start -a eu.faircode.netguard.START_PORT_FORWARD \
                     -n eu.faircode.netguard/eu.faircode.netguard.ActivityForward \
                     --ei protocol <protocol> \
                     --ei source <source> \
                     --ei target <target> \
                     --ei uid <uid> \
                     --user 0
```

Now, to find out why all traffic is blocked after I agree with the redirection :(

**Comment by M66B** [comment]
Possible causes: 

* the port redirected to is not listened to
* the uid of the proxy is wrong

**Comment by licaon-kter** [comment]
I got the UID from TotalCommander ( it's CHMOD option lists all apps and UIDs) and then I rememberend that NetGuard shows it :) :)

Server works ok: 
```
$ dig @127.0.0.1 -p 5353 4armed.com +dnssec +multi

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 5353 4armed.com +dnssec +multi
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52359
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;4armed.com.            IN A

;; ANSWER SECTION:
4armed.com.             300 IN A 108.162.206.126
4armed.com.             300 IN A 108.162.205.126
4armed.com.             300 IN RRSIG A 13 2 300 (
                                20160208102650 20160206082650 35273 4armed.com.
                                seoz5wRl03gbqVTtjcnAOPkRtGJcuZQGK54AAV0lGZFv
                                RFM0zB0xkkHDvy/GOCkf+cJu+mR0cuqHWWGdMiMG7g== )

;; Query time: 1121 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Sun Feb 07 11:26:49 EET 2016
;; MSG SIZE  rcvd: 177
```

But I was redirecting 6 (TCP) instead of 17 ( UDP) my bad, now, redirecting to UDP errors out:
```
$ dig 4armed.com +dnssec +multi

; <<>> DiG 9.10.3-P3 <<>> 4armed.com +dnssec +multi
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 29506
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;4armed.com.            IN A

;; Query time: 282 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Feb 07 11:32:29 EET 2016
;; MSG SIZE  rcvd: 39
```

Also 5353 errors out now:
```
$ dig @127.0.0.1 -p 5353 4armed.com +dnssec +multi

; <<>> DiG 9.10.3-P3 <<>> @127.0.0.1 -p 5353 4armed.com +dnssec +multi
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 31335
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;4armed.com.            IN A

;; Query time: 1686 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Sun Feb 07 11:35:44 EET 2016
;; MSG SIZE  rcvd: 39
```

BTW, I get no log entry and no notification that Unbound, net even when NOT redirecting.

**Comment by licaon-kter** [comment]
Ok, so after a while I got a notification, Unbound accessing one address, so that's kinda working, I don't get instant notifications, say press refresh in browser.

About menu logcat is 0.bytes.
Exported pcap is 0 bytes.

I'll retry.

**Comment by M66B** [comment]
The intent to start forwarding has changed, because it jas been made possible to forward to external addresses:

```
am start -a eu.faircode.netguard.START_PORT_FORWARD \
-n eu.faircode.netguard/eu.faircode.netguard.ActivityForward \
--ei protocol 17 \
--ei dport 53 \
--es raddr 8.8.4.4 \
--ei rport 53 \
--ei ruid 1 \
--user 0
```

Forwardings will be stored into a database, so disabling and enabling NetGuard will not reset forwarding anymore. This is also in preparation of a GUI for port forwarding.

**Comment by M66B** [comment]
To stop forwarding:

```
am start -a eu.faircode.netguard.STOP_PORT_FORWARD \
-n eu.faircode.netguard/eu.faircode.netguard.ActivityForward \
--ei protocol 17 \
--ei dport 53 \
--user 0
```

**Comment by licaon-kter** [comment]
Crashing hard here after a bit, although while working even DNSSEC validation seems to bein order now.

**Comment by licaon-kter** [comment]
Logcat: https://gist.github.com/licaon-kter/95f0226e32418ec85f89

**Comment by M66B** [comment]
I have already fixed this and will build a new version soon.

**Comment by licaon-kter** [comment]
Disables itself because of sqlite: https://gist.github.com/licaon-kter/382f3643fcaf9d0c0916

A clear app data fixed it.

**Comment by M66B** [comment]
A fix has already been released for this.

**Comment by licaon-kter** [comment]
I hope, it was your build https://github.com/M66B/NetGuard/commit/b3458e3bd9de5a52991e5488e5bfe8df8536a4fb and it was an update, and not a new install.

**Comment by M66B** [comment]
You'll have to export your settings, clear data and import your settings again to fix this.

**Comment by licaon-kter** [comment]
Yes, it's ok, just be sure to warn users if this happens.

**Comment by JasperWeiss** [comment]
@M66B @licaon-kter Thanks for implementing this

**Comment by M66B** [comment]
You're welcome.
The next version will have a little bit more polished UI, but it is quite usable as it is now.

**Comment by JasperWeiss** [comment]
I'll have to wait for f-droid to push the update

**Comment by M66B** [comment]
That could take quite some time and F-Droid builds are not supported (see the FAQ why).

**Comment by licaon-kter** [comment]
@JasperWeiss Just download the latest beta from Github, stop the network ;), export settings, uninstall current, install Github version, import settings, open network

**Comment by JasperWeiss** [comment]
Wouldn't that break automatic updates? (Different signing key).
Oh and just curious, I noticed the download page says "f-droid: not supported". last time I checked it was on f-droid

**Comment by JasperWeiss** [comment]
Hmm. I only have the option to fill in digits under protocol. Not sure how to type SOCKS5 on a keypad

**Comment by M66B** [comment]
F-Droid builds are not supported by me, see the FAQ why

UDP = protocol 17
TCP = protocol 6

Note that NetGuard.

**Comment by licaon-kter** [comment]
@JasperWeiss This is not a proxy related setting.

**Comment by JasperWeiss** [comment]
Oh, lol. Where can I find the proxy redirect setting?

**Comment by M66B** [comment]
The is and will be only port forwarding.
You can forward to whatever you like, but the other end needs to accept UDP or TCP traffic.
A http proxy server is most prepared to accept TCP traffic.

**Comment by licaon-kter** [comment]
So I guess you could try to redirect ports 80 and 443 to ip.of.proxy.host port 3128 (or whatver)
