### ISSUE TITLE
Add suport for custom DNS servers

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#30]
I guess [this](https://developer.android.com/reference/android/net/VpnService.Builder.html#addDnsServer(java.lang.String)) should do it, right?

**Comment by M66B** [comment]
This cannot be done, since the traffic routed into the VPN sinkhole doesn't go anywhere. You can use any applications to set the DNS servers system wide. Even if it could be done, NetGuard is not meant to change DNS servers.

**Comment by licaon-kter** [comment]
Umm [#define LWIP_DNS 1 & #define LWIP_UDP 1](https://github.com/M66B/NetGuard/blob/lwip/app/src/main/jni/lwipopts.h#L316) yes!

**Comment by licaon-kter** [comment]
Please re-open: https://github.com/M66B/NetGuard/commit/ec77f7403ea864c6c122794c324dd5ab0fb8816f

**Comment by M66B** [comment]
I was just doing the preparations for this: https://github.com/M66B/NetGuard/commit/8d6682515e1ccfdb1a12d09d69e2d49e47f05ba6

**Comment by M66B** [comment]
For now there is a development settings to override the default system DNS.
I am not sure if I will add a user option to override the system DNS.

**Comment by licaon-kter** [comment]
Any (external) reason not to?

**Comment by M66B** [comment]
I want to keep the number of option limited and I see no reason for NetGuard to make this configurable for now.

**Comment by licaon-kter** [comment]
So this will stay only in betas or be hidden under the Debug toggle or?

**Comment by M66B** [comment]
This will be in betas / debug builds only.

**Comment by M66B** [comment]
Unless there is a good reason to make it part of the feature set of NetGuard.

**Comment by licaon-kter** [comment]
How about port support? Say have [Unbound](https://github.com/smarek/android-unbound-dns/issues/6) on 127.0.0.1:5353.

**Comment by M66B** [comment]
Unfortunately Android doesn't support this:
http://developer.android.com/reference/android/net/VpnService.Builder.html#addDnsServer(java.lang.String)

**Comment by licaon-kter** [comment]
Ok, Github search is dumb, `adddns` will not find `adddnsserver` pfft

So anyway, filter is on, redirect all `UDP 53` to `myserver:myport` should cover this, right?

**Comment by M66B** [comment]
You can create a separate issue for general address/port redirection for this.

**Comment by licaon-kter** [comment]
Mmmkay
