### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by malitech** [M66B/NetGuard#301]
[logcat.txt](https://github.com/M66B/NetGuard/files/120909/logcat.txt)
![screenshot_20160208-020035](https://cloud.githubusercontent.com/assets/7058205/12875183/b2f15ac8-ce0a-11e5-8a83-720bf2e80181.png)
[data_app_crash@1454877143037.txt](https://github.com/M66B/NetGuard/files/120910/data_app_crash.1454877143037.txt)

Got this today. Happened twice.

**Comment by M66B** [comment]
This is likely related to #300, so I will close this issue now, but if you see this happen in the next release again, please let me know ASAP and I will look into it.
