### ISSUE TITLE
Port forwarding UI enhancements

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#303]
Protocol could be limited to UDP/TCP/ICMP?
Maybe have them as checkboxes?

Destination application could yield an app list to select from?

And one issue, when the keyboard is up, eg. you write destination port, the view does not scroll up so you can't write application UID: you need to hide keyboard, click on app field to write.

**Comment by M66B** [comment]
The keyboard handling is Android stuff.

**Comment by licaon-kter** [comment]
Oh I get it, I was expecting the view to be scrollable, at anytime.

But it works fine anyway since I can press enter on dest port and it slides up as expected.

**Comment by licaon-kter** [comment]
What app should be selected for external server? root? nobody?

**Comment by M66B** [comment]
nobody, since there is no local app handling anything and thus no app should be excepted.

**Comment by licaon-kter** [comment]
Can you add a text next to the selector `For external server choose *nobody*` ?
