### ISSUE TITLE
Rules not reloading after phone wakes up from sleep

### ISSUE THREAD

**Issue by malitech** [M66B/NetGuard#306]
[logcat.txt](https://github.com/M66B/NetGuard/files/123884/logcat.txt)

**Comment by M66B** [comment]
Why do you think the rules are not applied when waking up from sleep?
Which Android version are you using?
Which time did the device wake up? (this is needed to look at the logcat in this case).

**Comment by malitech** [comment]
Internet stops working when I unlock the phone after it's locked. I see NetGuard notification and it shows 0 allowed, 105 blocked, 0 hosts. 

I'm using a nexus 5 running marshmallow. 

I just mean unlocking the phone with wake.

**Comment by licaon-kter** [comment]
Doze setting for NetGuard?

**Comment by malitech** [comment]
Seems like this bug occurs only on mobile network. On WiFi, locking and unlocking doesn't affect the rules. 
On mobile, locking and unlocking disables the rules. It shows 0 allowed. It's like it is not detecting the mobile network. I have to open the NetGuard app and manually reload the rules.

**Comment by M66B** [comment]
**Which Android version are you using?
Which time did the device wake up? (this is needed to look at the logcat in this case).**

If you don't know anymore, please provide a new logcat with a time, so I can look into it.

On screen 'on' rules are always reloaded.

**Comment by licaon-kter** [comment]
He already said marshmallow, if that helps.

**Comment by M66B** [comment]
Indeed, missed that, sorry.

**Comment by malitech** [comment]
At the same time I took the logcat.

Yes but it's not loading on mobile network.

**Comment by M66B** [comment]
You changed the filter setting while on 3G:

```
02-10 03:58:08.191 32483 32527 I NetGuard.Service: Executing intent=Intent { cmp=eu.faircode.netguard/.SinkholeService (has extras) } command=reload reason=changed filter vpn=true user=0
02-10 03:58:09.349 32483 32527 I NetGuard.Service: Get allowed connected=true wifi=false home= network=<unknown ssid> metered=true generation=3G roaming=false interactive=true tethering=true filter=false
```

The screen was turned on or off while on 3G:

```
02-10 04:10:00.947 32483 32527 I NetGuard.Service: Executing intent=Intent { cmp=eu.faircode.netguard/.SinkholeService (has extras) } command=reload reason=interactive state changed vpn=true user=0
02-10 04:10:01.936 32483 32527 I NetGuard.Service: Get allowed connected=false wifi=false home= network=<unknown ssid> metered=true generation=3G roaming=false interactive=false tethering=true filter=false
```

```
02-10 04:12:31.940 32483 32527 I NetGuard.Service: Executing intent=Intent { cmp=eu.faircode.netguard/.SinkholeService (has extras) } command=reload reason=interactive state changed vpn=true user=0
02-10 04:12:33.069 32483 32527 I NetGuard.Service: Get allowed connected=false wifi=false home= network=<unknown ssid> metered=true generation=3G roaming=false interactive=true tethering=true filter=false
```

So, my conclusion is you have stuff blocked on 3G by some rule(s)

**Comment by M66B** [comment]
Ow, wait, last two events read 'connected=false', so you didn't had a connection at all, which will block everything. So, this is explained now.

**Comment by malitech** [comment]
I turned connection on and off to test this bug. Even when the connection was on, it showed 0 rules. :) I don't want to test it with the older version again. If you can send a test pro version, I will test again for any bugs. :)

**Comment by licaon-kter** [comment]
The beta version has all the Pro features enabled, not sure what you think you are missing.

**Comment by malitech** [comment]
Oh i thought it was temporary for the version marcel sent me.

The theme option is showing blank in settings.
If I select teal/orange, blue/orange, it shows,
Theme: UDP
Theme: TCP
If I select others, the theme text is gone. I see nothing, blank. Happens for both light and dark themes.

![screenshot_20160211-062146]
(https://cloud.githubusercontent.com/assets/7058205/12967281/49e8afe4-d08b-11e5-965f-8ca953ef9ed1.png)

I dont know if you need a logcat for this. Anyway here it is. Dont want you to get angry.
[logcat.txt](https://github.com/M66B/NetGuard/files/125760/logcat.txt)

The "Show names" is working now but a couple of apps still show IP instead of name. I use AVL Pro, an antivirus. It used to show names in previous version. Now it doesnt.

The rules issue is not seen in this version.

Thanks.

**Comment by malitech** [comment]
Marcel, can you please make the app show speed instead of graph icon? I want to use the feature but cant because of this. Requesting you to kindly add it so that I can uninstall speed meter apps. Really love this app. It's a prompt request from a teenager. Thanks.

**Comment by licaon-kter** [comment]
Speed meter was asked before on XDA, IIRC.

Theme issue is fixed already: https://github.com/M66B/NetGuard/issues/305

**Comment by malitech** [comment]
Yes I know it was already discussed. The notification shade has to be swiped down everytime to see the speed. If the icon shows speed the feature will be perfect.

**Comment by M66B** [comment]
Showing speed in an icon is not possible due to Android limitations (all icons need to be static).

**Comment by malitech** [comment]
But what about speed meter apps buddy? How do they work? I know a developer who has made an awesome speed meter app. He's very kind. Would you want me to ask him?

**Comment by M66B** [comment]
Speed meter applications generally work with an overlay window, but I don't want to ask the associated Android permission for this in NetGuard.

**Comment by malitech** [comment]
Oh ok. Thanks for the replies bro.
