### ISSUE TITLE
Merge applications/packages with same uid

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#309]
Currently all applications/packages are shown (separately) in the application list, even if they share the same uid. Filtering works on uid, so application/packages sharing the same uid should be grouped.

Currently there is a workaround in place that will replicate rules and condition for all packages sharing the same uid, but this is not very transparent.

**Comment by licaon-kter** [comment]
I'll vote for NO here.

OEMs tag plenty of apps, with different functions, with the same UID, I for one would like the flexibility to have them split up.

**Comment by M66B** [comment]
Even if there are >70 with the same uid, NetGuard cannot individually block/allow them, which is the point of this issue.

**Comment by licaon-kter** [comment]
Oh, then go ahead. My bad, it's per UID, now I remember. Probabil why AFWall+ does the same.

Now, what I would like is that the app detail somehow could show (text) all these apps names.

**Comment by M66B** [comment]
Android works internally also with uids:

http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.0_r1/com/android/server/connectivity/Vpn.java#Vpn.getAppsUids%28java.util.List%2Cint%29

**Comment by M66B** [comment]
More than 70 applications with the same uid us bothering me. Maybe it is not a good idea to merge all these. It will make searching/displaying more difficult.

One can always search on uid to see them all and this can be made easier by making the uid in the application drill down clickable.

Any thoughts on this?

**Comment by licaon-kter** [comment]
Clicking on it will show all apps with same UID?

**Comment by M66B** [comment]
That was the idea, yes.

**Comment by licaon-kter** [comment]
Not sure how you can make it discoverable though.

**Comment by M66B** [comment]
By underlining it was my idea.

**Comment by licaon-kter** [comment]
There is at least another underlined text there  yet that does not make it more desireable.
