### ISSUE TITLE
Xperia 4.0.4 issues

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#311]
`Logcat lines=0`

I have *OI Explorer* from F-Droid if that matters, also sending the log out of Bluetooth fails too, although I can send files fine from *ES Explorer* otherwise.

As soon as I choose one home network (currently connected or not: `wifi=true home="MyWifi1" network=MyWifi1 metered=true`) the log shows blocked access on mobile and I can't browse the internet.

`MyWifi1` is used as home by all the other devices (Xperia 5.1.1, Samsung 5.0.2, CM13) and not treated as metered.

Not sure if separate issue though, had https://github.com/ppareit/swiftp running, and while Chrome would register as blocked in mobile data and could not access the internet ( `... IP syn 1 not allowed` ), the FTP server was accessed successfully on local LAN, also it was not registering in the NetGuard traffic log at all but the logcat has the session.

Logcat via CatLog: https://gist.github.com/licaon-kter/a94928a4de4bd9f79658

**Comment by M66B** [comment]
Logcat lines=0: not solvable

Metered home network: please check the technical info to be sure

... the logcat has the session: can you point to where?

**Comment by licaon-kter** [comment]
I mean the logcat shows the FTP session that proves it worked, where the device is server and 192.168.100.xxx is client ( device->wifi ap->lan->PC )

**Comment by licaon-kter** [comment]
Tech info: https://i.imgur.com/mad4aTW.jpg

**Comment by M66B** [comment]
Could you please try to unselect the WiFi home network, toggle WiFi off and on and select the home network again?

**Comment by M66B** [comment]
Regarding the logcat, can you check if this command works:

```
logcat -d -v threadtime
```
(this is the command the built-in logcat function uses)

**Comment by licaon-kter** [comment]
`Unable to open log device '/dev/log/main': Permission denied`

Umm time to browse the source code then: https://github.com/nolanlawson/Catlog

**Comment by M66B** [comment]
CatLog has root permissions if I remember me correctly.

**Comment by M66B** [comment]
I have discovered a process without privileges can raise the file limit from its soft limit to its hard limit. On my device the file number limit is raised from the soft limit of 1024 to the hard limit of 4096. Only root can raise the soft limit above the hard limit. The soft limit represent the maximum number of files which can be open at any time. Files include pipes, sockets, etc. For NetGuard mainly sockets are open to forward traffic to the internet.

I am curious to the numbers on your device, so please install the linked version and watch for this line in the logcat:

```
W NetGuard.JNI: raised file limit from 1024 to 4096
```

The linked version also scales the session timeout down based on the file limit now and starts dropping connection requests if 80% of the file limit is being reached. This is better than crashing and without root this is the maximum that can be done.

The network speed notification shows the current number of open files and the maximum number of open files in the right top corner now (if debug level warning or lower).

http://www.netguard.me/NetGuard-v0.86-beta-2016020902-all-release-3.apk

**Comment by M66B** [comment]
About the FTP server: inbound traffic is not routed into the VPN tunnel and since it works, servers bind to all available interfaces, which includes the real devices (Wi-Fi, mobile network).

Try this command to see all listing servers and to find out to which address the server is bound:
```
netstat -nl
```
http://linux.die.net/man/8/netstat

You can see the interfaces with this command:
```
ifconfig
```
(on older Android version 'netcfg')

**Comment by licaon-kter** [comment]
`4096` on Xperia 5.1.1 and Samsung 5.0.2

**Comment by M66B** [comment]
I like to see the original limit before raising too to understand things better.

```
W NetGuard.JNI: raised file limit from 1024 to 4096
```

**Comment by licaon-kter** [comment]
> Could you please try to unselect the WiFi home network,
> toggle WiFi off and on and select the home network again?

No difference.

**Comment by licaon-kter** [comment]
> CatLog has root permissions if I remember me correctly.

[Not on <4.1](http://nolanlawson.com/2012/09/02/catlog-jives-with-jelly-bean-goes-open-source/) (where I am)

**Comment by M66B** [comment]
Regarding the Wi-Fi home issue, please install the linked version and search for the following line in the logcat:

```
NetGuard.Service: Get allowed connected=true wifi=true home="SUBRA_nomap" network="SUBRA_nomap" metered=false/false generation=null roaming=false/false interactive=false tethering=false filter=true
```

http://www.netguard.me/NetGuard-v0.86-beta-2016020902-all-release-4.apk

BTW, add the suffix "*_nomap*" to your WI-Fi network name(s) to prevent Google from mapping them.

**Comment by licaon-kter** [comment]
> netstat -nl

`tcp6 :::12345`

> BTW, add the suffix "_nomap" to your WI-Fi network name(s) to prevent Google from mapping them.

I doubt they'll suddenly delete it from their database though.

**Comment by M66B** [comment]
So the FTP server is listing on all interfaces as I expected.
Nothing can be done here seen from the perspective of NetGuard.

Wi-Fi name with and without quotes is a bug in Android.
I will add a workaround for this.
Good catch.

**Comment by M66B** [comment]
Could you please check if the Wi-Fi home problem is fixed?
http://www.netguard.me/NetGuard-v0.86-beta-2016020902-all-release-home.apk

**Comment by licaon-kter** [comment]
Works now. 10x
