### ISSUE TITLE
Show NetGuard in the application list again

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#312]
People ask for this, so let's show NetGuard again, but with the buttons disabled.

**Comment by licaon-kter** [comment]
Oh this again... AFWall+ shows itself also.

**Comment by malitech** [comment]
How about a warning when trying to disable instead of greyed out buttons?

**Comment by licaon-kter** [comment]
Why bother? Why have an option to disable it? If you don't want the app do uninstall it instead of crippling it and inventing reasons to give it 1star in Google Play store app.

**Comment by malitech** [comment]
Oh I wont disable it even if I can. Showing the app in the list with disabled buttons is the same as hiding it. We just say what we think, no need to be touchy. :)

**Comment by malitech** [comment]
I even said it because people wont have new reasons to complain.
