### ISSUE TITLE
Hosts list download failing

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#313]
0.87-beta2
Xperia 5.1.1

Hosts file link that I want (that I can open ok in browser): https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

Logcat: https://gist.github.com/licaon-kter/3c8400e54cd91c2774f3

**Comment by M66B** [comment]
```
Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
```

**Comment by M66B** [comment]
Was this handled corrected by the download dialog? (a toast message)

**Comment by licaon-kter** [comment]
No toast as notifications were off, oops, brb.

**Comment by licaon-kter** [comment]
Ok, AFWall was blocking the connection, although it's allowed... and only sometimes, strange.
