### ISSUE TITLE
App list taking too long

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#314]
Xperia 5.1.1

Not sure how to debug it or what to report, but, after some time, (w/ or w/o notification(s) visible/usually not dismissing it from taskmanager!), the app list will take a really long time or forever to appear.

Saw this on the main list for a while now (no idea on what version; sorry too many betas for me :P), and now since yesterday after 0.87-beta1 or 2 saw it in the port forward dest app list too.

https://mega.nz/#!YBwlTKZR!ECItli9fivBNg6mRTSmv5TW40sz-lo2-gIfIQ5wnes0

**Comment by M66B** [comment]
Try to unblock 10009

**Comment by M66B** [comment]
10009 = Backup transport

I have seen this problem myself to and it seems the package manager to be waiting for an external connection (directly or indirectly through a lock). Don't ask my why ...

**Comment by M66B** [comment]
Eventually, probably when the connection times out, the application list loads.

**Comment by licaon-kter** [comment]
I have no use for that, I'll test though.

**Comment by licaon-kter** [comment]
10009 is something else here.
`Backup Transport` I don't have.

**Comment by M66B** [comment]
Anyway, the package manager is likely not delivering a list of packages to NetGuard in a timely fashion.
This is outside the control of the NetGuard software.
