### ISSUE TITLE
Long downloads stalling

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#315]
0.86-beta, Xperia 5.1.1, no-root, Wi-Fi.

I'm seeing this on kinda every >25Mb download say from Google Play store app (say Skype or Chrome), it starts ok, goes to 7-8Mb and sits there, I then cancel, restart, maybe it downloads a bit more (no resuming there; always from 0%).

The log looks ok, app is never blocked, although I don't see new entries after it stopped.

I did retry a dozen times, always stopping at different points, but as soon as I stop NetGuard and restart the download it works instantly (or at line speed).

I'll try to get a logcat from NetGuard.

**Comment by M66B** [comment]
I don't think this is a NetGuard problem.
The Play store download speed varies considerably.

**Comment by licaon-kter** [comment]
I agree, but like I said, it stopsbut what a coincidence it started once I stopped NetGuard.

I'll have to retry w/ or w/o hosts blocking, since there are some hosts blocked for the Google Play store app there too.

**Comment by M66B** [comment]
I have downloaded Chrome (Beta) = 56 MB a dozen of times without any problems.

**Comment by M66B** [comment]
I cannot reproduce this issue at all.

**Comment by licaon-kter** [comment]
Hope the video makes it clearer on what I experience.
Now, i'll soon update to v0.87-beta-2016021201 and Google Play Store 6.2.10 and retest.

**Comment by licaon-kter** [comment]
Updated to v0.87-beta-2016021301 and Google Play Store 6.2.10 and no change, although I kinda found a workaround, just browsing the store while waiting, looking at other apps and after a bit it was installed as expected, so no idea if a Store issue or a NetGuard one.

I'll get to test this whether I like it or not every couple of days (maybe) as software updates come in Store and I'll report if anything new.
