### ISSUE TITLE
Native code crash: Bad file number

### ISSUE THREAD

**Issue by Gregy** [M66B/NetGuard#316]
Netguard sometimes displays notification about being disabled due to an error (I do not remember the text exactly). I managed to get adb logcat. The error appears to be:

`Native exit reason=pselect tun 932 thread f4194000 error 9: Bad file number `

```
NetGuard: 0.87-beta/2016021102 
Android: 5.1.1 (SDK 22) 

Brand: Sony 
Manufacturer: Sony 
Model: E5823 
Product: E5823 
Device: E5823 
Host: BuildHost 
Display: 32.0.A.6.200 
Id: 32.0.A.6.200 
Fingerprint: TRUE 
ABI: arm64-v8a 

VPN dialogs: TRUE 
Prepared: TRUE 
Permission: TRUE 

Interactive TRUE 
Connected TRUE 
WiFi TRUE 
Metered FALSE 
Roaming FALSE 
Type GSM 

WIFI/ CONNECTED "Gregy's network" * 

Slots 1/1 
SIM 1/1 cz/2303 Vodafone CZ * 
Network 1/1 cz/23003 Vodafone CZ TRUE 

Setting: filter=true 
Setting: stats_base=5 
Setting: notify_access=false 
Setting: dark_theme=false 
Setting: enabled=false 
Setting: show_top=false 
Setting: auto_enable=0 
Setting: unmetered_2g=false 
Setting: show_stats=false 
Setting: traffic_allowed=true 
Setting: version=2016021102 
Setting: whitelist_roaming=false 
Setting: resolved=false 
Setting: screen_delay=0 
Setting: tethering=true 
Setting: screen_wifi=false 
Setting: initialized=true 
Setting: wifi_homes=[] 
Setting: stats_samples=90 
Setting: whitelist_wifi=true 
Setting: whitelist_other=true 
Setting: stats_frequency=1000 
Setting: show_system=true 
Setting: unmetered_4g=false 
Setting: log_app=true 
Setting: national_roaming=false 
Setting: screen_other=false 
Setting: manage_system=true 
Setting: loglevel=3 
Setting: theme=teal 
Setting: use_metered=false 
Setting: log=true 
Setting: hosts_url=http://www.netguard.me/hosts 
Setting: unmetered_3g=false 
Setting: use_hosts=true 
```

I am attaching full logcat.
[netguard.native.crash.txt](https://github.com/M66B/NetGuard/files/129088/netguard.native.crash.txt)

Thank you very much.

**Comment by M66B** [comment]
```
D/NetGuard.JNI(27530): Loop thread f4194000
I/NetGuard.JNI(27530): UDP close from fd00:1:fd00:1:fd00:1:fd00:1/49712 to fd6a:be99:5dbb::1/53 socket 1026
D/NetGuard.JNI(27530): sessions ICMP 0 UDP 3 TCP 109 max 112/3276 idle 0 sdk 4
E/NetGuard.JNI(27530): pselect tun 932 thread f4194000 error 9: Bad file number
W/NetGuard.Service(27530): Native exit reason=pselect tun 932 thread f4194000 error 9: Bad file number
```
For some reason something went wrong with the file descriptor of the VPN tunnel, but I am not sure what.

If it happens again, please provide another logcat, so possible pattern can be deduced.

**Comment by M66B** [comment]
Maybe I know what is going on:

"*EBADF An invalid file descriptor was given in one of the sets. (Perhaps a file descriptor that was already closed, or one on which an error has occurred.)*"

http://linux.die.net/man/2/pselect

In English: one of the connections was closed by the remote in the small time fraction NetGuard was evaluating things. This error should be ignore.

**Comment by Gregy** [comment]
Ok, I managed to catch it again. Here is another logfile.
[netguard.native.crash2.txt](https://github.com/M66B/NetGuard/files/129126/netguard.native.crash2.txt)

**Comment by M66B** [comment]
Could you please check if this version fixes the problem?

http://www.netguard.me/NetGuard-v0.87-beta-2016021201-all-release-1.apk

Even if it works, I like to see a logcat to check if things go right.
It doesn't matter, and actually I prefer in this case, if the logcat is very long.

**Comment by M66B** [comment]
This problem does not occur on my device / Android version, so this is maybe a device / Android version specific problem.

**Comment by Gregy** [comment]
It seems fixed. Thank you very much. Also I have collected the long log you asked for:
[netguard.problem.fixed.txt](https://github.com/M66B/NetGuard/files/129243/netguard.problem.fixed.txt)

I will keep an eye on it and report back if the problem reappears.

And thank you for NetGuard :)

**Comment by M66B** [comment]
Reported to be solved.
Please reopen when this appears not to be the case.
