### ISSUE TITLE
IPsec packet can not block

### ISSUE THREAD

**Issue by hongpingwei** [M66B/NetGuard#318]
Encapsulating Security Payload can not block. Example VoLTE.

Can I ref  http://www.softether.org/?    IPsec.c.

**Comment by M66B** [comment]
All applications can be blocked with NetGuard, independent of the traffic type. Why do you think IPSec cannot be blocked?

**Comment by hongpingwei** [comment]
Thank your answer,I compare Netguard log and tcpdump log，lost packets.

**Comment by M66B** [comment]
Please be more specific, which packets were lost?

**Comment by hongpingwei** [comment]
Thank your answer!
pcap file here: http://pan.baidu.com/s/1bxCYdg

**Comment by M66B** [comment]
What do I need to look for?

**Comment by hongpingwei** [comment]
Thank your answer!
I use wirehsark
http://www.wireshark.org/

**Comment by M66B** [comment]
And how are you running IPSec  side-by-side with NetGuard?
Refs #320

**Comment by M66B** [comment]
Yes, I use wireshark too, but looking into a PCAP is only useful when you know what to look for.
There is much traffic in a PCAP and I am just a human ;-)

**Comment by hongpingwei** [comment]
I compare packet number and size of  two pcap file

**Comment by M66B** [comment]
How are you running IPSec side-by-side with NetGuard?
How can I try this myself?
Refs #320

**Comment by hongpingwei** [comment]
Thank your answer!
samumg s5,or other 5.0 upper.
VOLTE call any.can trace  IPSec side-by-side.

**Comment by M66B** [comment]
I guess you are using stock Samsung Android to make the VOLTE call.
My best guess is Samsung made an exception for the system application not being routed into the VPN.

**Comment by hongpingwei** [comment]
I guess system application routed into the VPN too.
Can I modify this ?
Thank your answer!

**Comment by M66B** [comment]
All packets routed into VPN are in the NetGuard PCAP, so if there is a difference with the tcpdump PCAP, then not all traffic is routed into the VPN. If you have root, then you could try to modify the routing table, but since this application is meant for no root, this is not supported.
