### ISSUE TITLE
fragment ipv4/ipv6 packet can not block

### ISSUE THREAD

**Issue by hongpingwei** [M66B/NetGuard#319]
www.tinc-vpn.org

 route.c 
/* RFC 791 */
static void fragment_ipv4_packet(node_t *dest, vpn_packet_t *packet, length_t ether_size) 

How can I do it? thank you.

**Comment by M66B** [comment]
I am not sure what you want to do, so please explain in more details.

The MTU value of the VPN tun device is high enough to prevent IP fragmentation. If fragmentation occurs I like to see a logcat and like to know how I can reproduce it.

**Comment by hongpingwei** [comment]
Thank your answer.I think MTU is more large，more  IP fragmentation

**Comment by M66B** [comment]
Normally yes, but not in the case of NetGuard.

The large MTU for the tun device prevents NetGuard from receiving fragmented IP packets.
NetGuard forwards the traffic using sockets, so NetGuard doesn't need to care about fragmentation.

NetGuard will log it when it received a fragmented packet from Android via the tun device.
Did you see this logging?

**Comment by M66B** [comment]
Did you see this logging?

**Comment by M66B** [comment]
I am closing this issue, but feel free to comment again if you find a line in the logcat which says a packet fragment was received by NetGuard.
