### ISSUE TITLE
Unable to start VPN - bad file descriptor

### ISSUE THREAD

**Issue by peter-sc** [M66B/NetGuard#322]
I'm testing the beta 0.87-2016021102. After running for some amount of time (1-2h) with loaded hosts file (downloade from netguard.me), enabled  IP traffic filtering, store remote domain names, block domain names, I'm getting the "bad file descriptor" error (VPN disconnects) and the after enabling Netguard (switch in application), it does not start the VPN service.
Then after disabling the IP traffic filtering, it suceeds sometimes, but not always. Logcat is attached
[netguard.zip](https://github.com/M66B/NetGuard/files/129943/netguard.zip)

Running the version from Play Store for more then a month without any similar issues.
LG G4, Android 6.0, non-rooted

**Comment by licaon-kter** [comment]
Update to v0.87-beta-2016021**4**02 and see what happens.

**Comment by M66B** [comment]
This has been confirmed to be fixed in later versions.
