### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#323]
Picture are new and updated features, screens, notifications, etc in two sizes.

**Comment by licaon-kter** [comment]
I'll do them later probably.
What languages?

**Comment by M66B** [comment]
Thanks, just English in the default theme will be enough for now.

Maybe one series of screenshots of the application list to show off the themes would be nice.


licaon-kter <notifications@github.com> schreef op 15 februari 2016 10:27:40 CET:

**Comment by licaon-kter** [comment]
I believe a special build (aka one that you just pushed in the Google Play store app beta) will be needed though.

**Comment by M66B** [comment]
All builds are the same, the builds downloaded from the Play store just present themselves differently.
But I see your point, so here is a version which always behaves as if downloaded from the Play store:
http://www.netguard.me/NetGuard-v0.88-beta-2016021502-all-release-play.apk

If you see anything which should not be visible, please let me know.

**Comment by licaon-kter** [comment]
Umm, and you want them in default mode (blacklist) ?
I might be able to do the tablet shots like this, AFWall+ doing the firewalling as backup, but no phone.

But if don't have a problem with whitelist mode (block Wi-Fi/block mobile/manage system) I could make you phone too.

**Comment by M66B** [comment]
There will be a change in the main action bar, so better wait a little with making screenshots.
There will be an icon to show if a network is metered or not.
To make room the name 'NetGuard' will be replaced by the NetGuard icon.

**Comment by M66B** [comment]
The just released beta version 0.90 has all the changes I planned.

**Comment by licaon-kter** [comment]
Depending on your answer to https://github.com/M66B/NetGuard/issues/332 I'll start making them again.

**Comment by licaon-kter** [comment]
Oh, wait, I forgot I need a special beta build...

**Comment by M66B** [comment]
* http://www.netguard.me/NetGuard-v0.90-beta-2016021902-all-release-regular.apk
* http://www.netguard.me/NetGuard-v0.90-beta-2016021902-all-release-play.apk

Could you please check the theming on lower Android versions (at least the legend) ?
Could you please check if you can reproduce #334 ?

There is one small new feature: logging of the number of connections along with the network usage.

**Comment by licaon-kter** [comment]
This is up to df6c43517d ?

**Comment by M66B** [comment]
One of the APKs include this commit, the other doesn't, but I don't remember which one.

**Comment by licaon-kter** [comment]
So I'll make shots only with the Play version, right?

**Comment by M66B** [comment]
Yes, please.

**Comment by licaon-kter** [comment]
Tablet, 0.90: https://mega.nz/#!ldwSwIqT!ajvWr0_Vq2mzExs_ybLCgJvcwp71WZDWQizzap48f_U

**Comment by M66B** [comment]
Thanks!

**Comment by licaon-kter** [comment]
Phone, 0.90: https://mega.nz/#!xAZFlJAI!jxGZFWriAga0K1mRuYnBISAck5mD8ZvpLD9uEOfl4HU

**Comment by M66B** [comment]
Thanks again!

**Comment by M66B** [comment]
The new option 'apply rules and conditions' doesn't require an update of the screenshots, since it will not be available on lower Android versions anyway.

**Comment by licaon-kter** [comment]
The translation was not pulled and I'd just GIMP any change anyway :)

**Comment by licaon-kter** [comment]
> Could you please check the theming on lower Android versions (at least the legend) ?

Looked ok on 4.0.4

> Could you please check if you can reproduce #334 ?

Never saw it, although on disable the notification stays, maybe you can dismiss them all then?!

**Comment by licaon-kter** [comment]
You could have asked for more specific one too, you know?

**Comment by M66B** [comment]
Yes, I know, thank you.
I just had the idea/spirit this morning to finally publish a new stable version, so I did it myself.
If you like you can take the corresponding tablet versions of the screenshots.
And if you feel screenshots need to be added, please let me know.
