### ISSUE TITLE
Unknown protocol xxx

### ISSUE THREAD

**Issue by peter-sc** [M66B/NetGuard#324]
Beta 0.88-2016021501, VPN starts, but after some time notification with text "Unknown protocol 2" is displayed. VPN is still running.
[logcat.txt](https://github.com/M66B/NetGuard/files/130346/logcat.txt)

**Comment by M66B** [comment]
You can ignore this error, since it is more a warning.
I will remove it in the next release

**Comment by licaon-kter** [comment]
Saw some of them too with v0.87-beta-2016021402 and then it crashed.

I'll get the logcat soon.

**Comment by M66B** [comment]
No need for a logcat

licaon-kter <notifications@github.com> schreef op 15 februari 2016 10:26:17 CET:

**Comment by M66B** [comment]
If the message annoys you, it should be gone in the new build:
https://github.com/M66B/NetGuard/releases/tag/0.88
