### ISSUE TITLE
Update Github readme and Google Play store app descriptions

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#325]
...for the new (store) version.

**Comment by M66B** [comment]
Lets make a list of things changes/added to not forget things:

* IP filtering per application per domain
* Network usage statistics per application per domain
* Notification on internet access
* Port forwarding
* PCAP export

**Comment by licaon-kter** [comment]
Others:
* Log search & filtering per protocol/rule
* Tethering support
* Option to set VPN IPv4, IPv6 and DNS address
* Android Android 4+ compatibility

**Comment by licaon-kter** [comment]
It's final then?

**Comment by M66B** [comment]
What is final?
I am planning to release soon, so I will use this version for now.
If you have suggestion for improvement, please let me know.

**Comment by licaon-kter** [comment]
I mean it's settled so I can revise the RO translation.

**Comment by M66B** [comment]
Yes, you can
