### ISSUE TITLE
PCAP recording checkbox issue

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#328]
Basically trying to check that "record PCAP" does not work, aka box is not checked, but Export PCAP is activated (and deactivated once Clean is pressed).

[Logcat says PCAP recording works](https://gist.github.com/licaon-kter/92944c71e1d7917adbc8) and export looks ok.

**Comment by M66B** [comment]
Export PCAP is enabled while there is a PCAP file available, so you can export while capturing is disabled. Clear will remove the PCAP file and this disable the export menu.

Does this answer your question?


licaon-kter <notifications@github.com> schreef op 18 februari 2016 11:54:51 CET:

**Comment by licaon-kter** [comment]
So what's the point of the *uncheckable checkbox* then?
