### ISSUE TITLE
Feature: to have the values of data sent and received in the log

### ISSUE THREAD

**Issue by Primokorn** [M66B/NetGuard#329]
Hi,
It would be great to have the quantity of data sent and received for each line (in kilobytes).
I'm currently using a dedicated app to monitor the traffic of data.

Thank you.

![unnamed](https://cloud.githubusercontent.com/assets/5938828/13145982/db400730-d653-11e5-982b-4560aace31b6.png)

**Comment by M66B** [comment]
There is an option to enable registering network usage per application per domain. This options depends on enabling IP filtering, also for allowed traffic.

The data sent/received will be visible in the application access log (drill down the application details).

This is more convenient than displaying this in the global traffic log, which is more meant to see real time connections (so it is not properly grouped for displaying network usage statistics).

If you meant something else than this, please let me know.

**Comment by Primokorn** [comment]
Perfect! Nothing to add.
