### ISSUE TITLE
Some connections are (abnormally) allowed

### ISSUE THREAD

**Issue by Primokorn** [M66B/NetGuard#330]
Hi,
I want to block all connections for microG app.
In the log, you can notice that some connections are allowed.

Thank you.

![unnamed](https://cloud.githubusercontent.com/assets/5938828/13146072/45861184-d654-11e5-9d0f-cefa2b25385b.png)
![screenshot_20160218-142312](https://cloud.githubusercontent.com/assets/5938828/13146073/459922d8-d654-11e5-939d-6fe6633c49b0.png)

**Comment by licaon-kter** [comment]
Red means blocked.
Red X means blocked.
Red triangle with line though it means blocked.
Little blue human figure means screen was on (when blocked).

DNS resolving is done by kernel, you can't block it (unless you block all apps that is).

**Comment by Primokorn** [comment]
Nothing is red on the screenshots but orange.
Why do I have a cross and sometimes a triangle + line?
Moreover, there's a cross next to K9 mail and the connection should not be blocked.

**Comment by M66B** [comment]
The exact color depends on the theme, but consider all reddish/orangish as blocked.
The triangle is the mobile connection icon. The line means blocked (so no connection).
It could also be the Wi-Fi icon with or without dash, reddish or greenish.

A cross means that there was no internet connection, which result in all blocked (obviously), so this is colored red. For some system applications there can be a green check mark when there is no internet connection to allow internal (local) traffic.

**Comment by M66B** [comment]
Let me know if this doesn't answer all your questions.
