### ISSUE TITLE
Internet access notifications appearing with "Notify on internet access" disabled

### ISSUE THREAD

**Issue by enervated** [M66B/NetGuard#334]
Huawei Nexus 6P
Android 6.0.1
NetGuard-v0.90-beta-2016021902-all-release.apk

I enabled "Log internet access" and "Notify on internet access". Then I disabled "Notify on internet access", yet still received notifications for internet access made to new destinations.

**Comment by M66B** [comment]
Sorry, I cannot reproduce this.
Both the global and application specific switch work for me.
