### ISSUE TITLE
Filtering bypass after waking from sleep

### ISSUE THREAD

**Issue by Gregy** [M66B/NetGuard#341]
Hello,
since upgrading to 0.90 from 0.87 I have again (#289) problems with data leakage after waking from sleep. This time I have filtering enabled. Toggling "Filter allowed traffic" seems to have no effect.

Symptoms are the same as last time. Blocked application has access to the network for few seconds after waking from sleep.

```
NetGuard: 0.90-beta/2016021902 
Android: 5.1.1 (SDK 22) 

Brand: Sony 
Manufacturer: Sony 
Model: E5823 
Product: E5823 
Device: E5823 
Host: BuildHost 
Display: 32.0.A.6.200 
Id: 32.0.A.6.200 
Fingerprint: TRUE 
ABI: arm64-v8a 

VPN dialogs: TRUE 
Prepared: TRUE 
Permission: TRUE 

Interactive TRUE 
Connected TRUE 
WiFi TRUE 
Metered FALSE 
Roaming FALSE 
Type GSM 

WIFI/ CONNECTED "Gregy's network" * 
VPN/ CONNECTED 

Slots 1/1 
SIM 1/1 cz/2303 Vodafone CZ * 
Network 1/1 cz/23003 Vodafone CZ TRUE 

Setting: filter_allowed=true 
Setting: filter=true 
Setting: stats_base=5 
Setting: notify_access=false 
Setting: dark_theme=false 
Setting: enabled=true 
Setting: pcap_file_size=2 
Setting: show_top=false 
Setting: auto_enable=0 
Setting: unmetered_2g=false 
Setting: show_stats=false 
Setting: traffic_allowed=true 
Setting: version=2016021902 
Setting: whitelist_roaming=false 
Setting: resolved=false 
Setting: screen_delay=0 
Setting: tethering=true 
Setting: screen_wifi=false 
Setting: initialized=true 
Setting: wifi_homes=[] 
Setting: track_usage=false 
Setting: stats_samples=90 
Setting: whitelist_wifi=true 
Setting: whitelist_other=true 
Setting: stats_frequency=1000 
Setting: show_system=true 
Setting: unmetered_4g=false 
Setting: log_app=true 
Setting: national_roaming=false 
Setting: pcap_record_size=64 
Setting: screen_other=false 
Setting: manage_system=true 
Setting: loglevel=4 
Setting: theme=teal 
Setting: use_metered=false 
Setting: log=true 
Setting: hosts_url=http://www.netguard.me/hosts 
Setting: unmetered_3g=false 
Setting: use_hosts=true 
```

ADB logcat starts just before screen off (but blocked browser already trying to connect) and ends after screen on and browser loading the page (even when it shouldn't be able to).

[netguard.bypass.txt](https://github.com/M66B/NetGuard/files/139510/netguard.bypass.txt)

Thank you

**Comment by M66B** [comment]
Are you sure the browser is not loading from the cache?
The browser loads from the cache whenever it detects network problems.

I am quite sure there is no leak when restarting the VPN on Android 5.1+

**Comment by M66B** [comment]
To be sure, I have tested this and clearing the cache, blocking the browser and turning the screen off and on does not result in loading a page. The browser reports 'NETWORK_CHANGED' and 'No access to the network' for me.

**Comment by Gregy** [comment]
I wanted to test it thoroughly and started by force stopping netguard, clearing its data and setting it up again. And the problem disappeared.

I am really sorry to have bothered you. :(

**Comment by M66B** [comment]
Don't worry, it could have been a real problem.

**Comment by Gregy** [comment]
Well, I reproduced it again. And now I know the trigger. It is related to the "allow tethering" option. That is the reason why clearing data on netguard helped (the option defaults to off).

"Allow tethering = off" -> No wake up data leak
"Allow tethering = on" -> Wake up data leak

**Comment by M66B** [comment]
The allow tethering option only does different VPN routing, so it is not likely it is an explanation for this problem.

**Comment by Gregy** [comment]
Also if it helps it appears that if you enable the tethering option you must also disable and enable filtering afterwards for the leak to kick in. If you go the other way around (disabling tethering) it fixes the leak immediately.

**Comment by M66B** [comment]
Changing the tethering option and filter option restart the VPN in exactly the same way.

**Comment by Gregy** [comment]
Can I somehow gather more information? I can get dump of the traffic from my wifi router if it would help debug the issue.

**Comment by M66B** [comment]
You could audit the code:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/SinkholeService.java#L379

**Comment by M66B** [comment]
You can check if you can find "*Handover failed*" in the logcat (which cannot be fixed, since this will be caused by a bug in Android).

**Comment by M66B** [comment]
I think this is all caused by bugs in your Android version, which I will try to workaround, provided that you are willing to test this (since I cannot reproduce this issue myself).

**Comment by M66B** [comment]
Can you please test v0.91-beta-2016022103
https://github.com/M66B/NetGuard/releases/tag/0.91

**Comment by Gregy** [comment]
Wow, you are really good. The leak is gone.

Thank you!

**Comment by M66B** [comment]
Great, thanks for testing.

Please note that this solution is not perfect, since the VPN will still be fully restarted when the VPN parameters change, for example when the DNS servers change (for example when connectivity changes from Wi-Fi to mobile or when you switch on/off tethering support). Nevertheless, screen on/off will not restart the VPN completely anymore, which will save some battery as well.

**Comment by M66B** [comment]
You can always thank me with an XDA thanks, a Play store review or a donation ...
