### ISSUE TITLE
Releases vs. Betas

### ISSUE THREAD

**Issue by krt16s** [M66B/NetGuard#343]
You are tagging quite a lot betas, are those safe to (and meant for) normal use or do you plan to release a "release" build any time soon?

**Comment by licaon-kter** [comment]
[0.92-beta is the last before release](http://forum.xda-developers.com/showpost.php?p=65453508&postcount=1503)

**Comment by M66B** [comment]
You can read that in the XDA NetGuard forum.

Building an application like this which is stable and bug free is not a simple task.

That said, the latest beta's seem to be quite stable.

Boris Kraut <notifications@github.com> schreef op 22 februari 2016 18:57:39 CET:

**Comment by licaon-kter** [comment]
@krt16s Wish granted https://github.com/M66B/NetGuard/commit/65ec9c2a608cb7d878a6f93269479e15828deb5d#diff-a4d21707ea79ee3bd6159958f3ffe22f
