### ISSUE TITLE
issue "pselect timeout" on HTC Sensation XL with Beats Audio X315e

### ISSUE THREAD

**Issue by lequangliem** [M66B/NetGuard#344]
Hello, 

I developing your project on HTC Sensation XL with Beats Audio X315e (android 4.0.3). Logcat always show "pselect timeout". That means I could not captured any packet on the device but still can access the Internet. 
(Sorry about my English).

```
02-23 15:41:47.788 D 3968     5909     NetGuard.JNI:                        Loop thread 915ba0
02-23 15:41:47.788 D 3968     5909     NetGuard.JNI:                        sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15 
02-23 15:41:52.793 D 3968     5909     NetGuard.JNI:                        pselect timeout
02-23 15:41:52.793 D 3968     5909     NetGuard.JNI:                        Loop thread 915ba0
02-23 15:41:52.793 D 3968     5909     NetGuard.JNI:                        sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-23 15:41:53.493 I 3968     5522     NetGuard.Service:                    Send broadcase mapSuspiciousSamples : {}
02-23 15:41:53.804 D 3968     5909     NetGuard.JNI:                        pselect ready 1
02-23 15:41:53.804 I 3968     5909     NetGuard.JNI:                        get uid v6 p6 fd00:1:fd00:1:fd00:1:fd00:1/42998
02-23 15:41:53.804 D 3968     5909     NetGuard.JNI:                        Packet v6 fd00:1:fd00:1:fd00:1:fd00:1/42998 > 2404:6800:4005:809::200a/443 proto 6 flags S uid 10016
02-23 15:41:53.804 D 3968     5909     NetGuard.JNI:                        TCP S fd00:1:fd00:1:fd00:1:fd00:1/42998 > 2404:6800:4005:809::200a/443 seq 1008623867 ack 0 data 0 win 65535 uid 10016
02-23 15:41:53.804 W 3968     5909     NetGuard.JNI:                        TCP S fd00:1:fd00:1:fd00:1:fd00:1/42998 > 2404:6800:4005:809::200a/443 seq 1008623867 ack 0 data 0 win 65535 uid 10016 new session mss 32708
02-23 15:41:53.804 E 3968     5909     NetGuard.JNI:                        connect error 101: Network is unreachable
02-23 15:41:53.804 D 3968     5909     NetGuard.JNI:                        Loop thread 915ba0
02-23 15:41:53.804 D 3968     5909     NetGuard.JNI:                        sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15 
02-23 15:41:58.818 D 3968     5909     NetGuard.JNI:                        pselect timeout
02-23 15:41:58.818 D 3968     5909     NetGuard.JNI:                        Loop thread 915ba0
02-23 15:41:58.818 D 3968     5909     NetGuard.JNI:                        sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15 
```

**Comment by M66B** [comment]
pselect timeout is a normal condition

**Comment by M66B** [comment]
Regarding your problem: the log shows traffic is flowing through the VPN, so your should be able to block  the traffic. If this is not the case, please provide more details.

**Comment by M66B** [comment]
Also, I see you have modified NetGuard ("*Send broadcase mapSuspiciousSamples*").
The license says that you MUST open source your code, so where is your code published?

**Comment by lequangliem** [comment]
This is my exercise on school. I do not publish it. I see on logcat "pselect timeout" but still access internet. I dont know why.

**Comment by M66B** [comment]
If you don't publish the code, you will need to solve problems yourself.

**Comment by lequangliem** [comment]
My mean is that this is an issue related the device HTC Sensation XL with Beats Audio X315e. 
You can try to install NetGuard on the device.

**Comment by M66B** [comment]
Send me such an device and I will test for you.
Please read this again: https://github.com/M66B/NetGuard/issues/344#issuecomment-187604059

**Comment by lequangliem** [comment]
HTC Sensation XL with Beats Audio X315e 
Android 4.0.3
NetGuard 0.88 beta

**Comment by M66B** [comment]
Begin with installing the official 0.93 on your device and enabling the traffic log.

**Comment by lequangliem** [comment]
I installed NetGuard 0.93 on HTC Sensation XL with Beats Audio X315e (Android 4.0.3). But the issue still occurs. I allowed all connection and try to access to google.com by Chrome. This is log : 

02-24 11:57:44.220 14946-14946/? D/dalvikvm: Late-enabling CheckJNI
02-24 11:57:44.410 14946-14946/? I/NetGuard.JNI: JNI load
02-24 11:57:44.410 14946-14946/? W/NetGuard.JNI: raised file limit from 1024 to 4096
02-24 11:57:44.520 14946-14946/? W/NetGuard.JNI: PCAP disabled
02-24 11:57:53.869 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Starting tun 105 fwd53 0 level 2 thread 0
02-24 11:57:53.869 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Started thread 287da10
02-24 11:57:53.889 14946-15335/eu.faircode.netguard W/NetGuard.JNI: Start events tun=105 thread 287da10
02-24 11:57:53.899 14946-15335/eu.faircode.netguard W/NetGuard.JNI: getrlimit soft 4096 hard 4096 max sessions 3276
02-24 11:57:53.899 14946-15335/eu.faircode.netguard D/NetGuard.JNI: Loop thread 287da10
02-24 11:57:53.899 14946-15335/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:57:53.899 14946-15335/eu.faircode.netguard D/NetGuard.JNI: pselect ready 1
02-24 11:57:53.899 14946-15335/eu.faircode.netguard W/NetGuard.JNI: Maximum tun msg length 76
02-24 11:57:53.899 14946-15335/eu.faircode.netguard W/NetGuard.JNI: IP6 extension 0
02-24 11:57:53.899 14946-15335/eu.faircode.netguard W/NetGuard.JNI: IP6 final extension 0
02-24 11:57:53.899 14946-15335/eu.faircode.netguard D/NetGuard.JNI: Packet v6 ::/0 > ff02::16/0 proto 0 flags  uid -1
02-24 11:57:53.899 14946-15335/eu.faircode.netguard W/NetGuard.JNI: Address v6 p0 ff02::16/0 syn 0 not allowed
02-24 11:57:53.899 14946-15335/eu.faircode.netguard D/NetGuard.JNI: Loop thread 287da10
02-24 11:57:53.909 14946-15335/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:57:56.562 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Stop tun 105 clear 0 thread 287da10
02-24 11:57:56.562 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Kill thread 287da10
02-24 11:57:56.562 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Join thread 287da10
02-24 11:57:56.562 14946-15335/eu.faircode.netguard D/NetGuard.JNI: Signal 10
02-24 11:57:56.562 14946-15335/eu.faircode.netguard W/NetGuard.JNI: pselect signaled tun 105 thread 287da10
02-24 11:57:56.562 14946-15335/eu.faircode.netguard W/NetGuard.JNI: Stopped events tun=105 thread 287da10
02-24 11:57:56.562 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Stopped thread 287da10
02-24 11:58:00.556 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Starting tun 65 fwd53 0 level 2 thread 0
02-24 11:58:00.566 14946-14965/eu.faircode.netguard W/NetGuard.JNI: Started thread 1c69d40
02-24 11:58:00.576 14946-15588/eu.faircode.netguard W/NetGuard.JNI: Start events tun=65 thread 1c69d40
02-24 11:58:00.576 14946-15588/eu.faircode.netguard W/NetGuard.JNI: getrlimit soft 4096 hard 4096 max sessions 3276
02-24 11:58:00.576 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:00.576 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:00.576 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect ready 1
02-24 11:58:00.576 14946-15588/eu.faircode.netguard W/NetGuard.JNI: Maximum tun msg length 76
02-24 11:58:00.576 14946-15588/eu.faircode.netguard W/NetGuard.JNI: IP6 extension 0
02-24 11:58:00.576 14946-15588/eu.faircode.netguard W/NetGuard.JNI: IP6 final extension 0
02-24 11:58:00.576 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Packet v6 ::/0 > ff02::16/0 proto 0 flags  uid -1
02-24 11:58:00.586 14946-15588/eu.faircode.netguard W/NetGuard.JNI: Address v6 p0 ff02::16/0 syn 0 not allowed
02-24 11:58:00.586 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:00.586 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:03.188 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect ready 1
02-24 11:58:03.188 14946-15588/eu.faircode.netguard W/NetGuard.JNI: IP6 extension 0
02-24 11:58:03.188 14946-15588/eu.faircode.netguard W/NetGuard.JNI: IP6 final extension 0
02-24 11:58:03.188 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Packet v6 ::/0 > ff02::16/0 proto 0 flags  uid -1
02-24 11:58:03.208 14946-15588/eu.faircode.netguard W/NetGuard.JNI: Address v6 p0 ff02::16/0 syn 0 not allowed
02-24 11:58:03.208 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:03.208 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:08.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:08.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:08.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:13.218 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:13.218 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:13.218 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:18.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:18.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:18.213 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:23.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:23.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:23.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:28.223 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:28.223 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:28.223 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:33.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:33.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:33.228 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:38.232 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:38.232 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:38.232 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:43.237 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:43.237 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:43.237 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:48.242 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:48.242 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:48.242 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:53.247 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:53.247 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:53.247 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:58:58.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:58:58.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:58:58.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:03.257 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:03.257 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:03.257 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:08.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:08.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:08.252 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:13.267 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:13.267 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:13.267 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:18.261 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:18.261 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:18.261 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:23.276 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:23.276 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:23.276 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:28.281 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:28.281 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:28.281 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:33.286 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:33.286 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:33.286 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:38.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:38.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:38.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:43.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:43.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:43.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:48.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:48.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:48.291 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:53.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:53.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:53.296 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 11:59:58.301 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 11:59:58.301 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 11:59:58.301 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 12:00:03.305 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 12:00:03.305 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 12:00:03.305 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 12:00:08.310 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 12:00:08.310 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 12:00:08.310 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 12:00:13.315 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 12:00:13.315 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 12:00:13.315 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15
02-24 12:00:18.320 14946-15588/eu.faircode.netguard D/NetGuard.JNI: pselect timeout
02-24 12:00:18.320 14946-15588/eu.faircode.netguard D/NetGuard.JNI: Loop thread 1c69d40
02-24 12:00:18.320 14946-15588/eu.faircode.netguard D/NetGuard.JNI: sessions ICMP 0 UDP 0 TCP 0 max 0/3276 idle 0 sdk 15

**Comment by M66B** [comment]
Then there is likely a bug in the Android VPN implementation.

```
Packet v6 ::/0 > ff02::16/0 proto 0 flags  uid -1
```

If nothing else is routed into the VPN than this, you are out of luck.

This cannot be worked around (only if you have root, but this is not supported, because NetGuard is meant for devices without root).

**Comment by lequangliem** [comment]
You means that does the issue only occur on rooted devices?

 I have tried to install on Galaxy Note 3 Android 5.0 and it is rooted. NetGuard works fine.

**Comment by M66B** [comment]
That is not what I said, it is a problem with the Android version on that device.

"*Then there is likely a bug in the Android VPN implementation*"
"*This cannot be worked around*"
