### ISSUE TITLE
[idea] Add password feature

### ISSUE THREAD

**Issue by franco999** [M66B/NetGuard#352]
It would be nice to have an optional security feature (add password to start the application) to avoid changes Internet access rules other people (children or adults). This feature would serve as a parental control, avoiding e.g. children access to the application and change the rules.

Something like that ↓↓↓
![pass-feature](https://cloud.githubusercontent.com/assets/12088580/13381190/5125f788-de34-11e5-91bb-e9b8d3e4553c.png)

**Comment by M66B** [comment]
I had added this in the past and removed it again, since there is no way to prevent the VPN service from being disabled using the Android settings, making this a useless option.

**Comment by licaon-kter** [comment]
@franco999 Read this https://github.com/M66B/NetGuard/issues/125 and https://github.com/M66B/NetGuard/issues/87#issuecomment-154709897
