### ISSUE TITLE
Why the change in internet permissions?

### ISSUE THREAD

**Issue by SADFJALSDKJF2303892749827** [M66B/NetGuard#353]
Reading the [FAQ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ6) and [commit](https://github.com/M66B/NetGuard/commit/1102c655073219db0efc65575348fa12358833e6) suggest "Full Internet Access" was added in 0.72 (I think?) to support IP filtering. Is that why? Mind elaborating in the FAQ? Anyway thanks for the great app!

**Comment by licaon-kter** [comment]
Nothing to elaborate, you've already answered your own question.

The Readme says: https://github.com/M66B/NetGuard/blob/master/README.md#permissions

**Comment by M66B** [comment]
The already referenced permissions section on GitHub says '*INTERNET: to forward allowed traffic to the internet*'. IMHO this should be clear, since allowed and filtered are the same here. If you have a suggestion to improve the explanation, please let me know and I will change it.
