### ISSUE TITLE
Export port forwardings

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#354]
`hosts_last_download` and `hosts_last` are not needed

Port forwarding settings are missing.

**Comment by M66B** [comment]
Hosts last .. are not imported, so there is no problem.

**Comment by M66B** [comment]
Can you please test if it works okay:
http://www.netguard.me/NetGuard-v2.0-2016022901-all-release-forward.apk

Please check the filter rule export/import as well, since I have revise this a little.

**Comment by M66B** [comment]
Did you test this already?

**Comment by licaon-kter** [comment]
Yeah, it's working.
