### ISSUE TITLE
"Log internet access" and "Notify on internet access" do not work as expected.

### ISSUE THREAD

**Issue by justmyhobby** [M66B/NetGuard#359]
It seems to Netguard from version 0.90 or higher, "Internet Access Log" only works when either the "Show Log" or "Traffic Filter" is enabled and "Notice on the internet" only works when "Filter traffic" is enabled.
To my understanding that these features do not depend on the "Show log" or "Traffic Filter". Am I right?
I modified the code of the class eu.faircode.netguard.SinkholeService as following and Netguard works as my expect.
```
private void startNative(ParcelFileDescriptor vpn, List<Rule> listAllowed, List<Rule> listRule) {
	SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(SinkholeService.this);
	boolean log = prefs.getBoolean("log", false);
	boolean filter = prefs.getBoolean("filter", false);
+	boolean log_app = prefs.getBoolean("log_app", false);

	Log.i(TAG, "Start native log=" + log + " filter=" + filter);

	// Prepare rules
-	if (filter) {
-		prepareUidAllowed(listAllowed, listRule);
-		prepareHostsBlocked();
-		prepareUidIPFilters();
-		prepareForwarding();
-		prepareNotify(listRule);
-	} else
-		unprepare();

+	unprepare();
	
-	if (log || filter) {	
+	if (log || filter || log_app) {
+		if(log_app){
+			prepareNotify(listRule);
+		}
+		if(filter){
+			prepareUidAllowed(listAllowed, listRule);
+			prepareHostsBlocked();
+			prepareUidIPFilters();
+			prepareForwarding();
+		}
		int prio = Integer.parseInt(prefs.getString("loglevel", Integer.toString(Log.WARN)));
		jni_start(vpn.getFd(), mapForward.containsKey(53), prio);
	}

	// Native needs to be started for name resolving
	if (filter)
		new Thread(new Runnable() {
			@Override
			public void run() {
				updateUidIPFilters();
			}
		}).start();
}
```

**Comment by M66B** [comment]
With the suggested change you are in fact enabling filtering ...

**Comment by M66B** [comment]
I am wrong, you are not enabling filtering, but enabling notifies for blocked access only, which will only result in questions that people do not see all access attempts.

**Comment by M66B** [comment]
A little more explanation: when filtering is not enabled, only blocked traffic is routed into the VPN. The notifications are based on the traffic flowing through the VPN, so not enabling filtering will only notify blocked traffic.

**Comment by justmyhobby** [comment]
That's what I want. I block all apps by default and enable "Notify on internet access" to notify me each time an app try to access the internet. Then I will check this app and unblock it if it is OK. Of course, I can use "Show log", but I think "Show log" is less convenient than "Notify on internet access".

**Comment by M66B** [comment]
This is not supported, because notify on internet access should notify on all access attempts, also allowed.

You can enable filtering and default block the application(s) to get something close to what you want.

**Comment by justmyhobby** [comment]
is there any differences in performance or battery usage between what you suggested and what I suggested. In fact, what I want from Netguard is that it notifies me when an blocked app try to access the internet then I will check to allow it or not. Something likes "Pending Access" in NoRoot Firewall.

**Comment by M66B** [comment]
The performance and battery usage difference is limited and in any case not more than in other no-root firewalls. Pending access is the same as a blocked notification.

**Comment by justmyhobby** [comment]
OK. Thank you.

**Comment by M66B** [comment]
I have decided to add this to offer the same function as before filtering was introduced.

**Comment by licaon-kter** [comment]
Kinda fixing https://github.com/M66B/NetGuard/issues/231 too?

**Comment by licaon-kter** [comment]
Without filter I never get notified on access, so this does not look fixed.

**Comment by M66B** [comment]
Just tested, works for me.
Note that only blocked internet traffic will be logged with filtering disabled.

**Comment by licaon-kter** [comment]
I have the same apps (like Album or the whole suite of UID 1000) that hit AFWall+ when filtering is on so I won't expect anything else.
Although I need to see how AFWall+ impacts the whole process (what was the order again app->NetGuard->iptables or the other way), given that with `filter on` blocked apps (in NetGuard) register connection attempts blocked in AFWall+ (wondering if packets actually bypass VPN?!?!?!?).

**Comment by M66B** [comment]
AFWall+ probably catches packets routed into the VPN as well, but if filtering is not enabled, the VPN is a sinkhole and the packets go nowhere anyway.

**Comment by licaon-kter** [comment]
Ok, so after a full day of not having any notification, now after a full clear data & restart (of NetGuard) finally it is working as intended.
