### ISSUE TITLE
Proxy branch - use local server

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#363]
Same as forwarding, it needs an app excluder.

**Comment by licaon-kter** [comment]
Invalid because?

**Comment by M66B** [comment]
The feature is not even finished yet.

licaon-kter <notifications@github.com> schreef op 10 maart 2016 08:26:57 CET:

**Comment by licaon-kter** [comment]
:)

**Comment by licaon-kter** [comment]
Then I'll not make a new issue yet for these either: https://gist.github.com/licaon-kter/d24c19ec104ba1452712
