### ISSUE TITLE
Implement hosts file emulator

### ISSUE THREAD

**Issue by RoxKilly** [M66B/NetGuard#364]
Use case:
An app requires internet access to work (eg: a media streamer, multiplayer game).  I am happy to let it access the net but I'm really concerned about the junk requests made to trackers and other privacy offenders.  Manually identifying and blocking offending IPs is too cumbersome (it doesn't scale well when dealing with 15 apps, each of which make requests to 15 servers...). Besides, the average user has no idea which http requests actually leak out private information and which are integral to the app's functions.

[AdAway](https://github.com/Free-Software-for-Android/AdAway) offers a simple solution for rooted devices: change the hosts file to disallow connections to known offending domains and update the blocklist periodically.  Although modifying the hosts file is not possible for NetGuard, can we use the same info to dynamically disallow bad requests? Would this be too burdensome on battery life?

Have you given this some thought? (disclaimer: I'm a user of [Grey Shirts' NoRoot Firewall](https://play.google.com/store/apps/details?id=app.greyshirts.firewall) and have only heard about your project today. Looks really interesting)

**Comment by M66B** [comment]
Ad blocking is already part of NetGuard, but ad blocking is not allowed in the Play store, so you will need to download the GitHub version.

**Comment by RoxKilly** [comment]
Hi.  Please clarify

**Comment by M66B** [comment]
The GitHub version is the same but will behave different and expose more features.
See also here: http://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012
