### ISSUE TITLE
Playing nice together with OpenVPN for Android

### ISSUE THREAD

**Issue by schwabe** [M66B/NetGuard#366]
Hi,

I am the OpenVPN for Android developer and I got the feature request of implementing a firewall (https://github.com/schwabe/ics-openvpn/issues/418).

I do like the idea of adding firewall capabilities to my app. Since passing fds/pipe between apps is possible with the help of the ParcelFileDescriptor I am wondering if you are interested in working with me for enabling that. 

My idea how that could work:

 - User sets in NetGuard Use OpenVPN with profile xxx
 - NetGuard app creates a pipe 
 - NetGuard app calls OpenVPN for Android (with AIDL) and says "please open VPN and use the fd (the pipe) in the Parcel instead writing directly to the tun
 - OpenVPN connects the VPN, uses the VPNService to get a tun, but hands over the tun to NetGuard via AIDL

packets would then flow this way

- [app] -> tun device -> NetGuard -> pipe -> OpenVPN for Android -> network
- network -> OpenVPN for Android -> pipe -> NetGuard -> tun device -> [app]

**Comment by M66B** [comment]
I would love to implement this and my proposal is to chat about the details: XMPP marcel@faircode.eu

**Comment by M66B** [comment]
The necessary changes are done in the branch, though not tested: https://github.com/M66B/NetGuard/tree/openvpn

**Comment by licaon-kter** [comment]
```
am start -a eu.faircode.netguard.START_PROXY \
-n eu.faircode.netguard/eu.faircode.netguard.ServiceProxy
```

What is the procedure exactly or this needs support in OpenVPN and that's not ready yet?
