### ISSUE TITLE
Tethering doesn't work if android's display is off

### ISSUE THREAD

**Issue by micressor** [M66B/NetGuard#367]
Steps to reproduce on my android 5.1 with NetGuard 2.5:

1. NetGuard->Settings->Enable tethering
2. Enable wifi tethering on android
3. Enable NetGuard
4. Ping to internet from my wifi connected computer.
5. If android's display is off, tethering does no longer work (ping timeout)
6. If the display is on again, tethering is working again (ping is back) 

Workaround:
1. Disable NetGuard
2. Tethering is working, when android's screen is off.

May be this is a android bug. But because I have that with NetGuard, please verify this.

Thanks.

**Comment by licaon-kter** [comment]
NetGuard excepted in battery optimisations?

**Comment by M66B** [comment]
NetGuard doesn't nothing different when screen is on or off with tethering.
Basically enabling tethering will route tether traffic outside the VPN:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/SinkholeService.java#L1002

Maybe the suggestion of @licaon-kter helps

**Comment by micressor** [comment]
Got it: Settings > wlan > enhanced > wlan hibernate = always

Thanks.

**Comment by micressor** [comment]
Got it: Settings > wlan > enhanced > wlan hibernate = always

Thanks.

**Comment by micressor** [comment]
Got it: Settings > wlan > enhanced > wlan hibernate = always

Thanks.

**Comment by M66B** [comment]
Should this go into the FAQ?

Marco Balmer <notifications@github.com> schreef op 10 maart 2016 14:42:05 CET:

**Comment by micressor** [comment]
Yes please. I think that could be helpful for others.

**Comment by M66B** [comment]
Is this understandable?
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ22

**Comment by micressor** [comment]
Perfect. Thank you.
