### ISSUE TITLE
Regression: 2.6 from F-Droid keeps crashing on Note 10.1 2014

### ISSUE THREAD

**Issue by sarimak** [M66B/NetGuard#368]
sm-p600, 5.0.1, stock, no root
2.5 works fine
2.6 starts, can display GUI, shows starting state but crashes upon start
workaround: export eettings, uninstall, install 2.5, import settinfs, re-download host list

**Comment by M66B** [comment]
Don't blame me for bad F-Droid builds, I have no control over them. The GitHub build will work.
