### ISSUE TITLE
Crash in 2.7

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#369]
GitHub build on Xperia 4.0.4/5.1.1, [seen on XDA too](http://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012/page188)
Custom debug build (AS 1.5.1) works ok though.

Logcat 4.0.4: https://gist.github.com/licaon-kter/25333b1a28ebf3b62bd7

**Comment by M66B** [comment]
It seems the transition to Android Studio 2.1 is to blame for this. Proguard striped out a few pretty essential classes.

**Comment by licaon-kter** [comment]
Logcat 5.1.1: https://gist.github.com/licaon-kter/f33bd328288fe149de7e
