### ISSUE TITLE
Add wildcard support when creating a rule

### ISSUE THREAD

**Issue by SergeiShir** [M66B/NetGuard#370]
Request to add support for wildcards in rules
in Access Attempt screen and in Log screen
when touching the connection log entry:

--- allow / block specific octets in IP address =
X.X.X.*
X.X.*.*
X.*.*.*
*.*.*.*
--- alow / block all ports

Such support for wildcards is implemented in NoRoot Firewall

**Comment by M66B** [comment]
Sorry, but I will not implement this. Manual entry on small devices is error prone and there would be performance implications.
