### ISSUE TITLE
Add support for global rules that would apply to all apps

### ISSUE THREAD

**Issue by SergeiShir** [M66B/NetGuard#371]
Add support for global rules that would apply to all apps

For example: block access to *.facebok.com

**Comment by M66B** [comment]
If you use a version which was not downloaded from the Play store, you can use a hosts file to block things system wide.

**Comment by SergeiShir** [comment]
I downloaded this app from Google Play Store
Is there any global setting that I missed ?

Thanks

**Comment by M66B** [comment]
Download the version from GitHub and you'll have a few extra options which are not allowed in the Play store.
