### ISSUE TITLE
'Export Settings' opens a link to 'OI File Manager' in Google Play Store

### ISSUE THREAD

**Issue by SergeiShir** [M66B/NetGuard#372]
'Export Settings' opens a link to 'OI File Manager' app in Google Play Store:
https://play.google.com/store/apps/details?id=org.openintents.filemanager

Note: I purchased the full set of pro features

**Comment by M66B** [comment]
You are likely using an older Android version, which doesn't offer the [storage access framework](http://developer.android.com/guide/topics/providers/document-provider.html). Therefore to import/export settings file a file manager is needed. OI File Manager is a simple to use, reliable fully open source file manager which can best be used for this purpose.
