### ISSUE TITLE
can not guard socket long connection （like IM app） in Moblie Network

### ISSUE THREAD

**Issue by zhx00100** [M66B/NetGuard#382]
can guard in Wifi， but can't in Mobile network

**Comment by M66B** [comment]
I am not sure what you mean, so explain in more detail.

**Comment by zhx00100** [comment]
for example， in What'app App or WeChart or QQ， anyway， these apps use socket to push message， and when in WiFi NetGuard can prevent message to send and receive， but in 3g/4g Mobile Network， can't prevent。I wonder if explain exactly

**Comment by M66B** [comment]
There is no difference in NetGuard for the connection type (Wi-Fi or mobile).
Did you block the application both for Wi-Fi and mobile?
Also check your '*when screen on*' rules and other conditions.

**Comment by zhx00100** [comment]
yes， I also think no difference. 
Unfortunately, I'm sure to block both wifi and mobile, but the result is what I describe above, I have test many times, so why I come here to find reason.
I'm in China, use QQ and WeChart to test, Sumsang S6 edge+, android 5.1.
Hope you to test this case,
thanks

**Comment by licaon-kter** [comment]
Mentioning QQ, I guess this is China.
So, what device?
What Android version?
Screenshot of the setting for that app?

**Comment by M66B** [comment]
Please reproduce the problem, take notice of the exact time and generate a log file by tapping seven times on the title of 'about' and post it here.

**Comment by zhx00100** [comment]
how can I post screenshot ? didn't find a way in github, I'm using cellphone

**Comment by zhx00100** [comment]
I tap 7 times on 'about'， but nothing happened...
only an about page still...

**Comment by zhx00100** [comment]
didn't found a log. by the way, I have no root

**Comment by M66B** [comment]
Then your device doesn't have the necessary software to do this.
The only solution is to capture a log file using adb from a PC.

**Comment by licaon-kter** [comment]
@zhx00100 Use https://imgur.com and post the link here.

**Comment by zhx00100** [comment]
oh, I forgot, for testing this case, I try to force closed QQ app and restart it, then NetGuard can prevent in Mobile Network.but when QQ connect ahead of Netguard, then can't prevent Mobile Network.
I think this really a problem, I will test next weak base on the opensource.

**Comment by zhx00100** [comment]
oh, I forgot, for testing this case, I try to force closed QQ app and restart it, then NetGuard can prevent in Mobile Network.but when QQ connect ahead of Netguard, then can't prevent Mobile Network.
I think this really a problem, I will test next weak base on the opensource.

**Comment by M66B** [comment]
Do you have IP filtering enabled in the settings?

**Comment by zhx00100** [comment]
http://pan.baidu.com/share/link?shareid=4134027464&uk=1208163734

I can't use imgur, because no google service...

**Comment by zhx00100** [comment]
I use the default settings, change nothing

**Comment by M66B** [comment]
The default setting for Android 5.1 is IP filtering disabled, which means Android manages all connections.
If this is a bug, it is a bug in your Android version.

Try enabling IP filtering in the settings.

**Comment by zhx00100** [comment]
but in Mobile Network, NetGuard can prevent Http request.

and, can you tell me how to set ip filter in Android system?

**Comment by M66B** [comment]
You can enable IP filtering in the NetGuard settings (use the three dot menu in the top right).

**Comment by zhx00100** [comment]
how can I use Pro features?

**Comment by M66B** [comment]
By purchasing them via the pro features window.

**Comment by zhx00100** [comment]
ok，thks

and sorry that I don't know where and how to enable IP settings in the Settings.
I have found the settings in the three dot menu, but still didn't know how to enable ip filter in the settings.
wish you to figure me out more detailedly.
thank you very much

**Comment by licaon-kter** [comment]
[!filter traffic](https://github.com/M66B/NetGuard/blob/master/screenshots/133-settings-advanced.png)

**Comment by zhx00100** [comment]
I've enabled filter traffic, but seems to be no effective

**Comment by licaon-kter** [comment]
Above Filter do enable Logging and Notification on access.
Is there any new notification appearing for QQ an whatever? If so are the domains written in red or blue?

**Comment by M66B** [comment]
Notifications might be handled by Google cloud messaging or a similar service.
Google cloud messaging is handled by Play services.

**Comment by licaon-kter** [comment]
China does not have GCM, afaik, he says `these apps use socket to push message`, so I guess WebSockets maybe? Anyway the notification might shed some light on what app is exactly connecting.

**Comment by zhx00100** [comment]
in China, cellphone has no google service(gms)

**Comment by zhx00100** [comment]
these apps use Socket to keep long connection(base on TCP),
tomorrow, I'll check Logcat on computer to see if any data to be captured

**Comment by zhx00100** [comment]
http://pan.baidu.com/share/link?shareid=1183412865&uk=1208163734
detect red log, and unlucky, can't prevent WeChart app's message to be sent

**Comment by licaon-kter** [comment]
I see 3 notifications in the status bar, do post a picture of them and their domains.

**Comment by zhx00100** [comment]
http://pan.baidu.com/share/link?shareid=1384733430&uk=1208163734

**Comment by zhx00100** [comment]
when I send message by 微信, there is no notification

**Comment by licaon-kter** [comment]
How do you know it's actually send? You have another device that receives them? Does the app have some icon to confirm?

**Comment by zhx00100** [comment]
yes, another device can receive the message I sent.

**Comment by licaon-kter** [comment]
Simple test, block EVERYTHING, does it still work? If it does, then you are hitting an Android bug.

**Comment by zhx00100** [comment]
can you tell me in more detail what to do about ''block EVERYTHING''

**Comment by zhx00100** [comment]
can you tell me in more detail what to do about ''block EVERYTHING''

**Comment by licaon-kter** [comment]
Block all apps. All should have red icons for all, be sure to uncheck "with screen on" if you see an icon with a blue man drawn.

**Comment by zhx00100** [comment]
block all，but still can send message

**Comment by licaon-kter** [comment]
And you can use the browser?
