### ISSUE TITLE
can't build in Windows, AndroidStudio 2.1 preview3, android-ndk-r11b, jdk7, gradle ver 2.10

### ISSUE THREAD

**Issue by zhx00100** [M66B/NetGuard#384]
Executing tasks: [:app:assembleAllDebug]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:app:compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC'.
> Multiple build operations failed.
      C compiler failed while compiling dhcp.c.
      C compiler failed while compiling icmp.c.
      C compiler failed while compiling ip.c.
      C compiler failed while compiling dns.c.
      C compiler failed while compiling netguard.c.
      C compiler failed while compiling session.c.
      C compiler failed while compiling pcap.c.
      C compiler failed while compiling tcp.c.
      C compiler failed while compiling udp.c.
      C compiler failed while compiling util.c.
  See the complete log at: file:///C:/Users/zhangxin/Desktop/NetGuard/app/build/tmp/compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.699 secs

**Comment by M66B** [comment]
I don't use Windows, so I cannot help you.

In general, if you want to build yourself, it is expected that you can solve problems yourself. If you can't, you can use the pre built version.

**Comment by licaon-kter** [comment]
@zhx00100 What did you modify in the source code so you need to build it yourself?

**Comment by zhx00100** [comment]
not yet. just build but didn't succeed in Windows, it seems 'clang' configuration, but I have no idea

**Comment by zhx00100** [comment]
@M66B so you uses Clang tool chain bundled with XCode on Mac ?

**Comment by M66B** [comment]
I build on Linux.

See here for what you need:
https://github.com/M66B/NetGuard#contributing

**Comment by licaon-kter** [comment]
@zhx00100 [VirtualBox](http://virtualbox.org) + [Lubuntu](http://lubuntu.net) + [this](https://paolorotolo.github.io/android-studio/) :+1:

**Comment by zhx00100** [comment]
thks for tips.
and what I resolved building project on Windows are as below:

use ndk-10, clang version 3.5, and comment out 'platformVersion = "xxx"'
        ndk {
//            platformVersion = "14"
            moduleName = "netguard"
            toolchain = "clang"
            toolchainVersion = "3.5"
            ldLibs.add("log")
        }
