### ISSUE TITLE
Import hosts file option is disabled for github version

### ISSUE THREAD

**Issue by RoxKilly** [M66B/NetGuard#385]
I installed the GitHub version (Netguard 2.7 or 2.8) on an Android 5.1 Moto X 2013 and the hosts file options worked fine; I was able to use the `Import hosts file`, `Hosts file download URL` and `download hosts file` options.  A couple of days ago, while on 2.10 or 2.11, I noticed that in settings all of these options are now greyed out. They've remained inaccessible with 2.12.

To update, I used the app notification (the `check for new releases on GitHub` option is enabled)

I haven't tried to uninstall/reinstall because i don't want to lose PRO features.  Why are the hosts file options disabled?

**Comment by M66B** [comment]
To import/download a hosts file you need to enable IP filtering.

**Comment by RoxKilly** [comment]
@M66B thank you for the fast response.  It may be a good idea to inform the user in the UI when she presses one of the hosts file options while IP filtering is off.

1.  Is this pre-requisite new to recent versions?  Why does hosts file importing require IP filtering?
2.  If I disable IP filtering (to reduce battery usage and improve Android data usage stats) after I have imported the hosts file, will the domains in the hosts file still be blocked?

**Comment by M66B** [comment]
IP filtering is required for ad blocking, see also here:
https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md

RoxKilly <notifications@github.com> schreef op 22 maart 2016 17:45:24 CET:

**Comment by kxra** [comment]
I've enabled the "filter traffic" option, but "block domain names" is greyed out as there is no hosts file available and i don't see where to import one

**Comment by kxra** [comment]
Okay, i've found it now. The guide and UI are very unintuitive as all the required steps are in entirely seprate areas of the settings menus and do not indicate where to look for the necessary switches

**Comment by B00ze64** [comment]
A few releases back the settings were all together, no categories. I actually preferred it this way. It took me a little time to locate the hostfile download button in the new releases (in Backup!) but Marcel says he's left it in Backup because that's where it first appeared and people are used to it by now...
