### ISSUE TITLE
feature request: widget for de-/activating traffic filtering

### ISSUE THREAD

**Issue by neo-luddite** [M66B/NetGuard#388]
on my nexus 5 traffic filtering and domain blocking with a hosts file works great, but consumes lots of battery. therefore it'd be great to have a widget for de-/activating this feature so it would be easy (1-click instead of minimum 4 clicks) to only activate it when in need (e.g. surfing the internet).

tnx!

**Comment by M66B** [comment]
There is already a widget to turn NetGuard on and off ...

neo-luddite <notifications@github.com> schreef op 24 maart 2016 20:43:32 CET:

**Comment by neo-luddite** [comment]
I try to make my point clearer:

I'd like to be online all the time and have netguard running so that only the apps I'd like to can access the internet (e.g . messenger apps). at that time I don't need the filtering which drains the battery a lot, that I only need when surfing the internet. therefore it'd be really nice to have a quick way  (doesn't have to be a widget) of dis-/enabling filtering (not netguard as a whole). right now minimum 4 clicks are needed.

**Comment by M66B** [comment]
I don't think many people will be interested in this rather specialized function and I am afraid it will only result in questions (which are there ashtray enough), so I am not going to implement this, sorry.

**Comment by neo-luddite** [comment]
I totally understand that. 
thanks anyway!
