### ISSUE TITLE
Enable state not respected on import

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#391]
No matter what `enabled` state the app is, given an exported config that has:
```
<setting key="enabled" type="boolean" value="true" />
```
On import NetGuard gets disabled, I guess [here](https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L1138)

**Comment by M66B** [comment]
This is by design, so the settings can be verified before being applied.

**Comment by licaon-kter** [comment]
Then why bother exporting state?

I find it troublesome to bypass the current user state, I'd like, if not importing the state at least do not alter the current user setting, so if I import some saved settings I don't expect the firewall to be disabled and leave all the apps to access the internet. 

Especially since after import I'm not switched to the apps view so I'm not aware that the firewall just got disabled. I'm still looking at settings, maybe tweaking them or loading some hosts while actually the firewall is disabled and all the apps do as they please? :(

**Comment by M66B** [comment]
I have looked into adding this, but there is a practical things that complicates enabling after import: the user might be asked for additional permissions.

I don't think it is worth complicating the code significantly for this, so I will leave it like it is.

**Comment by licaon-kter** [comment]
Or, minimal intervention, after import switch to app view so the user sees that NetGuard is off, what do you think?

**Comment by M66B** [comment]
I think one would go there anyway to check things.

licaon-kter <notifications@github.com> schreef op 26 maart 2016 08:39:51 CET:
