### ISSUE TITLE
Request: Possibility to change an individual rule into a general rule

### ISSUE THREAD

**Issue by w-Oeps** [M66B/NetGuard#392]
Many apps connect other servers once a server is blocked or some kind of load balancing mechanism redirects. For example:
An app connects to server1.trackthisuser.com. I block the domain en a second later or it tries to connect to server2.trackthisuser.com. 
Instead of blocking them all individually I would like to transform the blocking rule server1.trackthisuser.com into *.trackthisuser.com
(Before I started using Netguard I used NoRoot firewall and this has been very effective).
In the user interface it could be a long press on the existing rule. Adding an option to the pop-up: Change rule but you know better than me!

I hope this is possible someday if it does not affect battery life too much.

Thanks!
Willem
Running the Pro version from Github (2.12)

**Comment by M66B** [comment]
Wildcard checking will have an impact on the battery and for this reason I don't want to add this.

If you enable IP filtering, which will also use some more battery, you can block on real domain name (not reverse resolved domain names), which might fix this for you as well.
