### ISSUE TITLE
Ad blocking does not work, after disable/enable mobile network connection

### ISSUE THREAD

**Issue by micressor** [M66B/NetGuard#393]
Steps to reproduce with NetGuard 2.12 on Android 5.1:

1. Check [www.netguard.me/test](http://www.netguard.me/test) - Success
2. Disable mobile network connection
3. Enable mobile network connection
4. Check [www.netguard.me/test](http://www.netguard.me/test) again - Fail

Steps to fix:
1. Disable NetGuard
2. Enable NetGuard
3. Check [www.netguard.me/test](http://www.netguard.me/test) - Success

Tested with mobile network connection. Not tested with WLAN.

**Comment by M66B** [comment]
I cannot reproduce this problem with the latest version of NetGuard.
Did you wait until the hourglass in the action bar stopped showing?

**Comment by micressor** [comment]
Just tested again. NetGuard (2.12) shows hourglass after disabling- and after re-enabling network connection for some seconds and goes away. Still reproduceable on my installation.

**Comment by M66B** [comment]
Please check the number of hosts blocked in the notification (two finger pull down).
I am pretty sure this works okay, since nobody else has complained.
Are you sure no caching is being used?

**Comment by micressor** [comment]
Tested it again:

1. [test page](http://www.netguard.me/test) - Success
2. Clear browser cache and close (I think there is only browser caching on my device!?)
3. Disable mobile network connection
4. Enable mobile network connection (notification shows: 29 allowed, 141 blocked, 27291 hosts)
5. [test page](http://www.netguard.me/test) - Ad blocking does not work

**Comment by M66B** [comment]
I cannot reproduce this, sorry.

**Comment by M66B** [comment]
Android does cache DNS addresses for 10 minutes, so maybe wait ten minutes.

**Comment by licaon-kter** [comment]
What device? Android 5.1 or 5.1.1?

**Comment by micressor** [comment]
According to your comments I played around yesterday:

* I can reproduce this always with mobile network.
* I **can not** reproduce it with WLAN. WLAN works perfectly, as expected.
* Is it really a android dns lookup problem? Because I can fix it with disable/enable NetGuard and it is not necessary to clear firefox cache.
* Android Version 5.1 with Fairphone 2

**Comment by M66B** [comment]
NetGuard does not handle different connection types (mobile, WiFi) in a different way, so I indeed suspect there is something wrong with your Android version.

**Comment by micressor** [comment]
Confirmed. It looks like an android version related problem. I've just reproduced this issue with a 2nd device with same android version. Damn.

May be you can add some instructions, how to debug NetGuard better, before opening a bug. Thanks.
