### ISSUE TITLE
Crash on switch to mobile

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#395]
Xperia 5.1.1 w/ root, NetGuard 2.13 (not-N preview)
Was on Wi-Fi, happened to walk out of range, it changed to mobile, I noticed after a while that the key was missing from status bar, yet the notification was blissfully unaware that the main NetGuard process was dead.

Was `E ConnectivityService: Unexpected mtu value: 0, tun0` seen before too?

Logcat: https://gist.github.com/licaon-kter/367ad5ff1801fb9e9cd09f73fe8234fc

**Comment by M66B** [comment]
I don't see a single log line of NetGuard, so also no crash.

Yes, the tun message was seen before, so that is not new, but there are route problems, likely caused by a bug in Android.

**Comment by M66B** [comment]
Another workaround :-(

**Comment by licaon-kter** [comment]
> I don't see a single log line of NetGuard, so also no crash.

Netguards logcat had nothing from that time, so this is the raw log as root.

> there are route problems, likely caused by a bug in Android.

Not sure if a bug or just a timing coincidence, maybe NetGuard sent the addRoute commands, crashed (taking network 230 down) and just then `ConnectivityService` started to act on that command, hence `(No such device)`.

> Another workaround

Looking at the commit, since I have `tethering on` I would get the same results, more or less.
