### ISSUE TITLE
Can't reactivate netguard vpn after installing github version

### ISSUE THREAD

**Issue by hdmi** [M66B/NetGuard#396]
I've been using NetGuard for a while and worked flawlessly until today that I installed the github version for having the new adblock feature.
As the sign key of the apk was different I was forced to uninstall the playstore netguard before installing the github new version and after this I was not able to activate again the VPN.
I have tried everything: wipe cache partition, restore an app backup from yesterday and it does not work anymore.

Here is the logcat with some useful information: http://pastebin.com/71auTA0K

Thanks for your time

**Comment by licaon-kter** [comment]
What device? Android version? 
When I see this a reboot should do it. Basically you need to remove VPN rights from NetGuard, if you are lucky the Settings->VPN interface ha such an option, if not...

**Comment by hdmi** [comment]
@licaon-kter I am currently using stock android 6.0.1 on a Nexus 6P (rooted). My VPN list in settings is empty

**Comment by M66B** [comment]
First of all the Play store and GitHub version are identical, even the signature.

@licaon-kter pointed you in the right direction, because this is most likely an Android problem:

```
03-30 23:54:59.006 13793 13793 E VpnConfirm: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
```

NetGuard is asking VPN permission and Android is crashing.

**Comment by hdmi** [comment]
I think that I've found the [bug issue](https://code.google.com/p/android/issues/detail?id=201743) in the android repository and as you said it is a bug in the Android operate system.

However even if it is not concern to your application, is there any troubleshoot that I can do for solving it?
I have read that this exceptions came out when you try to accept an already accepted VPN, if only I knew where are physically located those VPN configuration I would be able to wipe them and try to accept the VPN again from the beginning.

**Comment by M66B** [comment]
I am sorry, but I don't know where the settings are stored.

Carlos <notifications@github.com> schreef op 31 maart 2016 13:46:21 CEST:
