### ISSUE TITLE
Forgotten Wi-Fi names get stuck in config

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#397]
And will be exported/imported, although they are not shown in the home selection dialogue, which is correct.

Maybe check if networks are still on the saved list and maybe purge missing ones? Here: https://github.com/M66B/NetGuard/blob/dd7ce17323b97c840f925cce48d195b2ee888b0d/app/src/main/java/eu/faircode/netguard/ActivitySettings.java#L163

**Comment by M66B** [comment]
I see no point in fixing this edge case. Just unchecked a name and leave and enter the settings should remind the name.

**Comment by licaon-kter** [comment]
You can't actually uncheck the name of a network that does not exist anymore.

Basically:
* network exists
* mark network as home
* you export settings
* device gets reset to factory
* you import settings

The old network will be stuck in config, so you need to: export config, edit XML and remove it, reimport.

It just hit me a few days ago:
* connections would not work: https://i.imgur.com/G0vCCqe.jpg
* you can't uncheck it in the UI: https://i.imgur.com/unJktpK.jpg

My solution: see above.

**Comment by M66B** [comment]
Automatically removing forgotten Wi-Fi network names seemed not a good idea to me, so I have added some code to make sure all selected Wi-Fi networks are shown, even if they were forgotten, so they can be deselected manually.

@licaon-kter: could you please test this?

**Comment by licaon-kter** [comment]
Thanks, I'll rebuild asap.
