### ISSUE TITLE
Adblocking does not work in 2.16 beta

### ISSUE THREAD

**Issue by bobness09** [M66B/NetGuard#399]
Hey,

it seems that in the newest version, adblocking does not work after importing a new hosts file (looks like simply upgrading the version to 2.16 without importing a new hosts file works).
In 2.15, I could not import hosts-files because of the bug with disabled import entries.

I then installed 2.14, and adblocking works fine.

Maybe this bug is related to importing the hosts files, because either by download or local file it doesn't work.

My setup: Nexus Pixel C with Marshmellow / newest firmware, german language.

Kind regards,
bobness

**Comment by M66B** [comment]
There is really nothing changed to ad blocking in any of these versions, just the settings, which was undone.

Check here: https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md
