### ISSUE TITLE
Add selective blocking/unblocking of addresses

### ISSUE THREAD

**Issue by githtz** [M66B/NetGuard#4]
Allow the user to define rules for each app to block or unblock certain addresses.
If a domain was entered resolve the assigned IP-address and save domain and IP-address together (this should be helpful if the IP-address assigned to the domain changes).

**Comment by M66B** [comment]
I completely understand this feature request, but unfortunately this is not possible without sacrificing quite some battery power and adding a lot of complex code to do network translation for OSI layer 3 to layer 4 (and thus implementing a TCP/IP stack), which will inevitably introduce bugs as well. This is how most (all?) other no root firewall work.

**Comment by githtz** [comment]
Oh, that's sad, since a lot of use-cases can not be dealt with without selective rules. Thanks for the detailed answer though.

**Comment by M66B** [comment]
For more advanced use cases while not sacrificing battery usage, rooting and using a iptables based firewall, like [AFWall+]https://github.com/ukanth/afwall() is a better option.

NetGuard is for those who don't/can't root their device and need simple per application internet blocking.
