### ISSUE TITLE
Turning on filtering breaks UDP in SIP

### ISSUE THREAD

**Issue by ache** [M66B/NetGuard#401]
No response received. I notice the same situation with other local VPNs with filtering on Android.

**Comment by licaon-kter** [comment]
Device? Android version? Test app? Logcat? PCAP?

**Comment by ache** [comment]
Nexus 5, Android 6.0.1 (not routed), CSipSimple, PCAP: http://rghost.ru/8zw2NtdSB
REGISTER sip:reg.dt-tc.com is out, but no response. Turning off filtering fix it.

**Comment by M66B** [comment]
Registering with the Android built in SIP works.
Can you please provide a logcat?

**Comment by M66B** [comment]
Setting up a SIP session using CSipSimple to my own VoIP provider works.

**Comment by ache** [comment]
On non-rooted device (like mine) any logcat app display its own entries only in the new OSes, so completely useless.
In the same CSipSimple after filtering on, two providers with TCP sessions works, and another one with UDP session always can't register. Just force transport from Auto to UDP in the acc settings to avoid TCP fallback.

**Comment by M66B** [comment]
Please reproduce the problem and right after it, tap seven times on the title of about to send a logcat.

**Comment by ache** [comment]
Logcat: http://rghost.ru/7SkQq7R6s
Notice address 188.246.162.118:5060

**Comment by M66B** [comment]
Which version of NetGuard are you using?

**Comment by ache** [comment]
Freshly downloaded from Google Play, 2.15

**Comment by M66B** [comment]
I don't see anything unusual in the logcat.
SIP over UDP works for me with the Android build in SIP protocol.

**Comment by M66B** [comment]
What you can try is to disable applying rules and conditions for CSipSimple. This will set the application outside of the VPN.

**Comment by M66B** [comment]
What you can try is to disable applying rules and conditions for CSipSimple. This will set the application outside of the VPN.

**Comment by M66B** [comment]
What you can try is to disable applying rules and conditions for CSipSimple. This will set the application outside of the VPN.

**Comment by M66B** [comment]
What you can try is to disable applying rules and conditions for CSipSimple. This will set the application outside of the VPN.

**Comment by M66B** [comment]
What you can try is to disable applying rules and conditions for CSipSimple. This will set the application outside of the VPN.

Ache <notifications@github.com> schreef op 5 april 2016 09:42:59 CEST:

**Comment by ache** [comment]
Yes, it works that way, but with VPN and without filtering (i.e. not grayed out) it works too. Is there any way to selectively disable filtering only?

**Comment by M66B** [comment]
Filtering cannot be selectively enabled. All traffic flowing into the VPN is either filtered or not filtered.


Ache <notifications@github.com> schreef op 5 april 2016 11:57:35 CEST:

**Comment by ache** [comment]
BTW, I have similar problem with Zoiper (another SIP dialer). In filtering mode it can register, but making a call I hear nothing, internal Zoiper stats shows no incoming packets. Looks like Android VPN bug preventing incoming connections in flltering mode or sort of double NAT bug (one NAT in the router and another one by VPN). I expect torrents problem too, but don't test it.

**Comment by M66B** [comment]
Torrents work.
I do stress tests with torrents.

**Comment by M66B** [comment]
Can you please install this debug version, set native log level in the settings to debug, reproduce the problem and provide another logcat?
http://www.netguard.me/NetGuard-v2.16-2016033102-sdk-23-all-debug.apk

**Comment by ache** [comment]
Logcat: http://rghost.ru/6NkfJkWGK
Packet v4 10.1.10.1/47227 > 188.246.162.118/5060 proto 17 flags  uid -1
Is VPN change listening port in filtering mode? If it suppose answer to come to 47277 port it never happens, router have a hole only for 5060 to route to this device.

**Comment by M66B** [comment]
47227 is the local port, 5060 is the remote port.

```
04-06 16:39:37.839 25075  4101 D NetGuard.JNI: Packet v4 10.1.10.1/47227 > 188.246.162.118/5060 proto 17 flags  uid -1
04-06 16:39:37.839 25075  4101 I NetGuard.JNI: UDP forward from tun 10.1.10.1/47227 to 188.246.162.118/5060 data 599
```

NetGuard forwards the packets, but there is never an answer. This could be caused by routing bugs in your Android version or device external factors.

Since this works for me, I am going to assume there is no bug in NetGuard.

**Comment by ache** [comment]
As I say in the very initial ticket, I try 2 other local VPNs, and when filtering mode is active, the bug happens. It is not NetGuard-only bug. It can be either the bug in the common VPN initialization sequence, like missing route, or Android or even Linux bug. As I see in my route log, the answer is passed to the device.

**Comment by M66B** [comment]
My best guess this is an Android routing bug, which are unfortunately not uncommon.
See also this: http://stackoverflow.com/questions/36084816/receive-udp-in-android-marshmallow/36086778

**Comment by ache** [comment]
Do you use datagramChannel.receive() or datagramChannel.read()?
People says that datagramChannel.receive() always return NULL on Android >= 5.0
https://github.com/EsotericSoftware/kryonet/issues/106

**Comment by M66B** [comment]
No, NetGuard handles raw IP packets and uses Linux sockets.
Maybe your application uses these functions.

**Comment by ache** [comment]
> Maybe your application uses these functions.
Zoiper is closed source, but CSipSimple source is available, in case you may look in. It is based on PJSIP library:
https://github.com/r3gis3r/CSipSimple

**Comment by M66B** [comment]
UDP packets from CSipSimple are routed into the VPN, so this is not the problem.
The problem is there are no return packets, which NetGuard has no control over.
