### ISSUE TITLE
IP forwarding doesn't work

### ISSUE THREAD

**Issue by SchmitzA** [M66B/NetGuard#403]
I guess ServiceSinkhole#isAddressAllowed line 1449 should read
 if (fwd.ruid != packet.uid) {
instead of
 if (fwd.ruid == packet.uid) {

**Comment by licaon-kter** [comment]
What device? Android version? NetGuard version? Test case?

**Comment by M66B** [comment]
IP forwarding works for me, I have just tested it again to be sure.
The code line you are referencing is correct.

**Comment by SchmitzA** [comment]
My mistake, sorry! I guess I didn't grasp the concept of "destination application" initally. I was added the source app her; stupid me!
