### ISSUE TITLE
Process terminates and VPN proxy drops

### ISSUE THREAD

**Issue by Andrew17856** [M66B/NetGuard#404]
In low memory conditions, the NetGuard service is terminated by the OS and the VPN drops. 

Obviously this means the firewall ceases to function (which can be expensive if you're using it to block traffic while roaming!)

Can the process priority be increased and/or a notification icon added to prevent termination of the process please?

**Comment by M66B** [comment]
The NetGuard service if already a foreground service with an ongoing notification.

If Android still kills the service, then the memory is really low and Android is panicking. This is a memory problem, which cannot be fixed from NetGuard.

**Comment by Andrew17856** [comment]
Thanks. In that case I wonder if something else is wrong (eg exception being thrown for some reason) that's causing the process to terminate.

None of the other services on my device are terminating (eg Lookout, Tasker etc) and I have 2GB RAM,  so a high end device. Is there a debug log I can activate to help trace the issue?

**Comment by M66B** [comment]
Only a logcat acquired using adb from your PC can tell what happened.

**Comment by licaon-kter** [comment]
@Andrew17856 How do you know it's `in low memory conditions` ?

**Comment by Andrew17856** [comment]
It was an assumption (which I now think was false) based on a problem I had when I wrote a service on one of my apps (which I resolved my making it foreground and adding an icon) -  having now looked a bit more closely at the issue on NetGuard, and given it's already in the foreground with an icon, I don't think it's memory that's the issue.  I think it's terminating for some other reason.

None of the other services that run on my device are affected.  Also, the shield notification icon for NetGuard remains even when the process has terminated, and it still says that it's enforcing the rules (the VPN key disappears though).  I think I'm right in saying that if the system terminates for low memory, the icon would disappear.

**Comment by licaon-kter** [comment]
I have this long standing issue https://github.com/M66B/NetGuard/issues/291
But we need some logs to see if you get `TransactionTooLargeException`, like I do, or something else.
Of note, I see some `OpenGL low memory` too there. This reminds me to upload some 5 logcat (from today) for crashes on that issue.

**Comment by M66B** [comment]
OpenGL memory issues have really nothing to do with NetGuard.

**Comment by licaon-kter** [comment]
Isn't  the memory shared between CPU and GPU?

**Comment by M66B** [comment]
That depends on the device. In any case NetGuard has no part in memory management.
