### ISSUE TITLE
Please provide Access data reset

### ISSUE THREAD

**Issue by Gerolianis** [M66B/NetGuard#405]
Neither protocol/clear nor settings/reset usage currently clear access table entries. Apart from manually  clearing access data per App or, even worse, editing the database ...  I see no feasible way to eliminate inconsistent entries:  over the time (as a consequence to uninstalling and reinstalling applications), the uid will no longer link to the correct application. 

An option to clear all access table entries would be a lot easier to implement than to take care of possibly changing uid <-> app relations

**Comment by Gerolianis** [comment]
Okay, that's how you solved it. Fine! Clearing access log on uninstall will prevent future data corruption, I didn't dare to suggest that - but what to do with already corrupt access data? Clear NetGuard data from appmanager and setup from scratch?

**Comment by M66B** [comment]
Export your settings, clear data and import your settings will clear all access data, but will leave all rules.
