### ISSUE TITLE
Ads not blocked on S7 Edge SM-935F

### ISSUE THREAD

**Issue by wildetudor** [M66B/NetGuard#406]
Apologies if this is not the right place to post this (first time user).

I've installed NetGuard on my S7 Edge (SM-935F) in order to block ads without rooting (had used AdAway on previous phones and it worked perfectly). 

However, after following the installation&setup [instructions](https://github.com/M66B/NetGuard/blob/master/ADBLOCKING.md) to the letter, ads are still shown in some (not all) apps, most notably (annoyingly) in Youtube. Also, when going to your test page, it is mentioned that 
Ad blocking does not work.

Can anyone help? Many thanks in advance.

**Comment by M66B** [comment]
This question has recently been asked and answered in the XDA NetGuard forum.

**Comment by wildetudor** [comment]
I had already searched there before posting here. Searching again only found posts that did not help, and certainly no description of a situation much like mine. Could you possibly please post a direct link? Thanks!

**Comment by M66B** [comment]
In short: NetGuard only blocks ads based on domain name.
YouTube ads are served in another way and cannot be blocked.

**Comment by wildetudor** [comment]
I see, many thanks for claifying. Just one more question: assuming I root the phone, is AdAway then able to block ads even in YT?

**Comment by M66B** [comment]
AdAway blocks ads based on hosts file too, so no.

**Comment by wildetudor** [comment]
OK. I asked because on my old phone (S3, which I had rooted), there were no ads in YT at all, and I can only assume it was due to AdAway. It might have been due to the old YT version (the stock YT that came with Android 4.0), but my bet is still that it was AdAway who needed to be thanked. I'd just prefer not to have to root the S7 Edge.

So are you saying NetGuard will block ads in all apps except from YT? YT aside, I am still not clear on what else I need to do to make the test page say that ad blocking works properly.

**Comment by M66B** [comment]
NetGuard blocks ads server from domains in the hosts file you use.

The test page will work if you follow all instructions and only with the default hosts file download.

**Comment by wildetudor** [comment]
But I already stated that I followed all the instructions, including the download of the default hosts file

**Comment by M66B** [comment]
Then it should work and if it doesn't you did something wrong.

**Comment by wildetudor** [comment]
You don't seem very keen to work with me on *what it is* that I might have done wrong ;) I went through the steps again - they're really not difficult to follow so I take it there's smth else that's not working

**Comment by M66B** [comment]
It is not that I don't want to help, but I don't know how to help.
It works for me and for many others, so you must have done something different.

**Comment by wildetudor** [comment]
OK. Going back to my previous (unanswered) question:

> So are you saying NetGuard will block ads in all apps except from YT?

**Comment by M66B** [comment]
It was not unanswered: "*NetGuard blocks ads server from domains in the hosts file you use*", meaning that ads retrieved in another way cannot be blocked.

**Comment by wildetudor** [comment]
I guess that means "it will block ads in some apps but not in others, depending on what servers the ads in that app use"

**Comment by M66B** [comment]
Basically yes.

**Comment by wildetudor** [comment]
ok - thanks for your help

**Comment by wildetudor** [comment]
by the way: the fact that I still didn't get this app to block any ads technically still leaves the problem open, therefore by closing this thread (issue) as you did - since as you say you do not know how to help - you are really just pretending the problem/issue is gone when it isn't

**Comment by M66B** [comment]
GitHub issues are meant for bugs and I don't think this is a bug, since it works for me and many others.

See also here: https://github.com/M66B/NetGuard#support

**Comment by wildetudor** [comment]
I see - my bad.

**Comment by licaon-kter** [comment]
@wildetudor 
See NewPipe, SkyTube or WebTube on F-Droid, if you want to live without ads, but without some features of the official YouTube client too.
