### ISSUE TITLE
Much traffic does not go through tunnel?

### ISSUE THREAD

**Issue by HyperCriSiS** [M66B/NetGuard#409]
Hi,

when "filter data traffic" is enabled, everything works as expected.
When I disable it and open the log, I only see blocked connections but there are no newly allowed connections at all.
Whats the issue here?
I checked permissions in XPrivacy and every app has VPN permission.

Thanks and regards,
Hyper

**Comment by M66B** [comment]
This is normal, only in filter mode allowed traffic will be shown. Else the VPN server as sinkhole and only blocked traffic will be shown. This cannot be changed.

**Comment by licaon-kter** [comment]
With `filter off`:
* only *blocked* apps are send to the VPN (aka tunnel) hence NetGuard can notify you of them being blocked.
* *allowed* apps just connect unhampered, but can't be observed, hence NetGuard can't notify you of their actions and you can't block hosts.

If the apps can't actually connect with 'filter off', means that your Android version (ROM) has a bad VPN implementation, eg. Samsung 5.0.2, that's the reason 'filter' was coded in the first place as most devices (< Android 5.1.1) can't use the VPN directly.

**Comment by HyperCriSiS** [comment]
Thanks for the fast response.
I am running MM AICP (CM) Rom on S5.
