### ISSUE TITLE
Tunnel hardening

### ISSUE THREAD

**Issue by HyperCriSiS** [M66B/NetGuard#410]
Hi,

it would be great to see some kind of tunnel hardening, so it it impossible that traffic goes through when the tunnel is not active.
Could be available as advanced option. I think that root will be necessary.

What do you think?

Regards,
Hyper

**Comment by M66B** [comment]
There is no need for this, because Android manages the VPN and the internet traffic seamlessly.

**Comment by licaon-kter** [comment]
@HyperCriSiS If the VPN (NetGuard) crashes, you can't do anything (to block the access) without root.

Or were you referring about some other case?

**Comment by HyperCriSiS** [comment]
No, this is what I meant.
