### ISSUE TITLE
Connection issues with "filter traffic" enabled

### ISSUE THREAD

**Issue by HyperCriSiS** [M66B/NetGuard#413]
Hi,

as soon as this option is enabled, nearly all apps get a connection error.
The issue seem to be the connections you see in the screenshot.
I saw this issue here on Github, but I could not find it anymore.
![screenshot_20160414-130816](https://cloud.githubusercontent.com/assets/11708192/14574043/642bea50-0359-11e6-81be-760e2ee48d9c.png)

Allowing these connections does not work. You get a "-1" at the top bar.

Thanks and regards,
Hyper

**Comment by licaon-kter** [comment]
Device? Android version/flavour?

**Comment by HyperCriSiS** [comment]
S5 with AICP (CM13).
With filter off, unfortunately most traffic does not go trough tunnel.

**Comment by licaon-kter** [comment]
> With filter off, unfortunately most traffic does not go trough tunnel.

Not sure what you mean, blocked apps are not send to the tunnel but have access or what?

**Comment by HyperCriSiS** [comment]
Yes sorry my fault. I meant that the traffic is send to tunnel but is blocked.
As you can see in the screenshot, these seem to be some broadcast that maybe are important for the network to work.
I already saw exact this issue here on Github, but I cannot find it anymore.

**Comment by M66B** [comment]
Most of the traffic shown in the logcat is not regular traffic and cannot and need not be routed, so this is normal.

**Comment by M66B** [comment]
Please provide a logcat.

**Comment by licaon-kter** [comment]
> Yes sorry my fault. I meant that the traffic is send to tunnel but is blocked.

Yes, with `filter off` that's normal, BLOCKED traffic is send in the VPN blackhole.
I've already explained it to you: https://github.com/M66B/NetGuard/issues/409#issuecomment-209522583
