### ISSUE TITLE
DNS question

### ISSUE THREAD

**Issue by rmenessec** [M66B/NetGuard#415]
If provided a hosts file, how does NetGuard make use of it? I have an application I need to block by returning NXDOMAIN with AUTHORITY set. For example:
```
localhost ~ [0]$ dig opencandy.com +nsid +multiline

; <<>> DiG 9.10.3-P2 <<>> opencandy.com +nsid +multiline
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55866
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;opencandy.com.     IN A

;; ADDITIONAL SECTION:
dns.gslb.local.    60 IN SOA ns.local. root.local. (
                2017023100 ; serial
                1800       ; refresh (30 minutes)
                900        ; retry (15 minutes)
                604800     ; expire (1 week)
                900        ; minimum (15 minutes)
                )

;; Query time: 35 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 32 13:22:44 EDT 2016
;; MSG SIZE  rcvd: 101
```
I'm currently achieving this with [BIND and RPZ](http://www.zytrax.com/books/dns/ch7/rpz.html), but this solution is not presently portable; I haven't seen BIND or any other DNS service available to host directly on Android.

If NetGuard contains a stub resolver that could return NXDOMAIN instead of—or as well as—127.1/32 or 0/32, I'd love to see this option.

Thanks!

**Comment by M66B** [comment]
NetGuard returns NXDOMAIN, because a connecting attempt to localhost would still use some battery power.

Please ask your next question in the XDA NetGuard forum, so more people can benefit from the answer.

GitHub is for bug reports and features requests.
