### ISSUE TITLE
USB or WiFi tethering not working on some Android 5.0 devices

### ISSUE THREAD

**Issue by yawnbox** [M66B/NetGuard#42]
I'm not able to identify an option to allow the use of the hotspot my Nexus 6 w/ Android 6.

**Comment by M66B** [comment]
Does the hotspot work with NetGuard installed and all applications allowed?

**Comment by yawnbox** [comment]
I did not try this exact scenario. I unchecked all options (block wifi by default, block mobile by default, block roaming by default, and manage system applications) and verified NetGuard was active and no apps were denied. Attempting to connect with my phone's hotspot has the same problem. WiFi devices will "connect" but never actually connect. As soon as I disable NetGuard, I am able to connect without issue.

**Comment by M66B** [comment]
It seems DNS responses are erroneously routed into the VPN sinkhole when using Wi-Fi tethering.

Tether subnet: 192.168.43.1/255.255.255.0
PC address: 192.168.43.215
DNS server: 192.168.43.1

```
11-03 09:22:24.868  8349  8618 E NetGuard.Service: java.io.IOException: java.io.IOException: UDP not supported Packet(IPv4Header(version=4, IHL=5, DSCP=0, EN=0, totalLength=77, reserved=0, DF=true, MF=false, fragmentOffset=0, TTL=64, protocol=17, headerChecksum=25207, sourceAddress=192.168.43.1, destinationAddress=192.168.43.215, options=, calculatedHeaderChecksum=25207), eu.faircode.netguard.Packet$UDPHeader@ba8a46a, bytes=45 00 00 4D 00 00 40 00 40 11 00 00 C0 A8 2B 01 C0 A8 2B D7 00 35 90 E0 00 39 4E 86 3F F3 81 80 00 01 00 01 00 00 00 00 03 77 77 77 08 6E 65 74 67 75 61 72 64 02 6D 65 00 00 01 00 01 C0 0C 00 01 00 01 00 00 0B 87 00 04 17 E5 3D 82)
```

00 35 port 53
90 E0 destination port
00 39 length
4E 86 checksum

3F F3 Message ID
81 80 Flags
00 01 QD count
00 01 AN count
00 00 NS count
00 00 AR count
03 77 77 77 08 6E 65 74 67 75 61 72 64 02 6D 65 00 00 01 00 01 C0 0C 00 01 00 01 00 00 0B 87 00 04 17 E5 3D 82

I didn't see the corresponding DNS request packet flowing through the tunnel.

**Comment by M66B** [comment]
Also DHCP seems to go through the VPN tunnel
```
11-03 09:55:20.225 11282 11652 E NetGuard.Service: java.io.IOException: java.io.IOException: UDP not supported Packet(IPv4Header(version=4, IHL=5, DSCP=0, EN=0, totalLength=343, reserved=0, DF=false, MF=false, fragmentOffset=0, TTL=64, protocol=17, headerChecksum=9677, sourceAddress=10.1.10.1, destinationAddress=192.168.43.215, options=, calculatedHeaderChecksum=9677), eu.faircode.netguard.Packet$UDPHeader@4837269, bytes=45 00 01 57 53 48 00 00 40 11 00 00 0A 01 0A 01 C0 A8 2B D7 *00 43* 00 44 01 43 1C C2 02 01 06 00 B1 E9 3D 5C 00 00 00 00 00 00 00 00 C0 A8 2B D7 C0 A8 2B 01 00 00 00 00 14 2D 27 8D 22 B9 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 63 82 53 63 35 01 05 36 04 C0 A8 2B 01 33 04 00 00 0E 10 3A 04 00 00 07 08 3B 04 00 00 0C 4E 01 04 FF FF FF 00 1C 04 C0 A8 2B FF 03 04 C0 A8 2B 01 06 04 C0 A8 2B 01 0C 04 43 37 32 30 2B 0F 41 4E 44 52 4F 49 44 5F 4D 45 54 45 52 45 44 FF)
```
00 43 = port 67

**Comment by LouisCAD** [comment]
I have the same issue. I realized that tethering isn't working when NetGuard is enabled. It makes me think of a potential feature: Why wouldn't Netguard enable us to monitor devices connected, and allow us to block some of them?

**Comment by M66B** [comment]
I have tried to fix this with several workaround, but unfortunately without luck.
IMO this is a bug in Android, since DHCP and DNS should not go into the VPN tunnel, unless asked for.

**Comment by licaon-kter** [comment]
FYI, just tested and neither one of these work for me for HotSpot either:
* [NoRoot Firewall](https://play.google.com/store/apps/details?id=app.greyshirts.firewall) 
* [NoRoot Data Firewall](https://play.google.com/store/apps/details?id=com.jianjia.firewall)
* [Mobiwol: NoRoot Firewall](https://play.google.com/store/apps/details?id=com.netspark.firewall)
* [LostNet NoRoot Firewall](https://play.google.com/store/apps/details?id=com.lostnet.fw.free)

**Comment by M66B** [comment]
@licaon-kter thanks for testing. This confirm it is likely an Android bug.

**Comment by licaon-kter** [comment]
This looks like an oversight, as routes are not created, also currently it can only be fixed by having root: http://digiex.net/guides-reviews/guides-tutorials/mobile-devices/13974-android-phone-vpn-gateway-bypass-tethering-block.html

I propose this should be closed.

**Comment by LouisCAD** [comment]
But isn't there a way to detect traffic coming from tethering and let it pass through? NetGuard is personally much less practical if I have to constantly enable it and disable it again each time I use tethering... and NetGuard can "protect" me from apps I denied network access while I'm using tethering...

**Comment by licaon-kter** [comment]
As the NetGuard description says _"Most of these features are the result of sending selected traffic to a sinkhole, instead of filtering all internet traffic. This means that advanced features, like address based filtering (needed for ad blocking), **traffic logging, and on-demand configuration**, are not possible."_

Also, as the link says, you need **root** to implement the missing routes with iptables, hence no way.

**Comment by licaon-kter** [comment]
Does this not help: 
[addRoute](https://developer.android.com/reference/android/net/VpnService.Builder.html#addRoute(java.net.InetAddress, int)) ?

Yeah, I guess all the other no-root providers would of used it by now, but... it sounds so right. :)

**Comment by M66B** [comment]
Route: which addresses are routed into the sinkhole = all

Address: the address of the tunnel itself (gateway). Not very interesting, but we don't want a clash with other local addresses (of the local router).

It is good to see you are trying to understand how things work.

**Comment by licaon-kter** [comment]
Umm [#define IP_FORWARD 1](https://github.com/M66B/NetGuard/blob/lwip/app/src/main/jni/lwipopts.h#L189) ;)

**Comment by M66B** [comment]
Fixed by https://github.com/M66B/NetGuard/commit/2b2812588a565ff3a385957dd1325738d26350d0

**Comment by licaon-kter** [comment]
10x
I'll build a test version later.

**Comment by licaon-kter** [comment]
Do reopen this though...

Anyway, testing: it works sometimes, not sure of a pattern yet, I first thought it did not like https:// but if I hit reload a lot or toggle NetGuard on/off on the mobile side it might suddenly start working.

Also, I see that the data usage registers as `Tethering` in Android.

**Comment by M66B** [comment]
Please check the logcat if it doesn't work.

**Comment by M66B** [comment]
@licaon-kter did you test this further?

**Comment by licaon-kter** [comment]
I'll test that later.

Now, on the no-root Samsung 5.0.2, crash on tether activate: https://gist.github.com/licaon-kter/bda50621dc502852351f

**Comment by M66B** [comment]
Can you please try with the commit just done?

**Comment by licaon-kter** [comment]
Now it crashes at 225.0.0.0, see a pattern there?

**Comment by M66B** [comment]
Test version for both issues:
http://www.netguard.me/NetGuard-v0.77-beta-3-2016012401-all-release.apk

**Comment by licaon-kter** [comment]
(on Samsung 5.0.2) It does not crash now, but it blocks all traffic on the device (both mobile and Wi-Fi), so although I can connect to that tether, I can't do anything else.

(on Xperia 5.1.1) Works as expected.

**Comment by M66B** [comment]
This is logical and will be fixed after I have added a DHCP server, so we can route tethered traffic into the VPN. This has also advantage that tethered traffic can be filtered.

The tethered traffic is now erroneously routed into the VPN due to a bug in Android.

**Comment by licaon-kter** [comment]
Not sure I follow.

On Xperia 5.1.1 everything works ( filter or not, tether on or off)
On Samsung 5.0.2 everything is blocked ( filter on since needed, tether on or off)

**Comment by licaon-kter** [comment]
Samsung 5.0.2 now the device works ok (beta7 or 0.78-[non-beta](https://github.com/M66B/NetGuard/commit/8b7820864cd2462d7d67adc97d881f499922ff33#commitcomment-15715056)), but tethering does not work, the other device connects but internet is not reachable.

Disabling Netguard lets the traffic flow. I'll get a logcat later on.

**Comment by M66B** [comment]
Filtering will be likely be fixed in the next release.

What I cannot fix is Android routing problems, so I am going to close this issue.

**Comment by licaon-kter** [comment]
Tested a bit with https://github.com/licaon-kter/NetGuard/commit/103bbf13c81226df315a7371e1ed4f0241f9f3c8 too, on Samsung 5.0.2, still behaving strange:
* on mobile device tethering is on
* NetGuard has tethering support enabled
* UID 1000 covers some 70 apps, one of them called "Tethering automation" so it's allowed
* `routedns` on or off (no conclusion yet)
* tablet has connection (albeit it does complain of missing internet)
* I have NetGuard on non-3G tablet (tested with or without `wifi as metered`/`wifi home`
* AFWall+ with apps allowed only on VPN as they should (except NetGuard etc)
* not working but some packets flow, say 2 ICMP from ping, say a bit of a web page, no clear reason or timing yet
* BUT I see AFWall+ toasts popping out as packets get blocked (aka NOT flowing through the VPN as limited)
* enabling app access on Wi-Fi makes the toasts disappear
* although even w/o AFWall and/or NetGuard, still internet access behaves strange
