### ISSUE TITLE
syncthing-android will EBADF and crash NetGuard w/ filter on

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#420]
I had [syncthing-android](https://github.com/syncthing/syncthing-android) as my main suspect for a while, although it won't appear related in the logs, I can definitely link it with the errors.

Repro w/ `filter on`:
Xperia 5.1.1 w/o root
Xperia 5.1.1 w/ root
Xperia 6.0.1 w/ root

Setup w/ `filter on` (this is essential as with `off` I did not see it crash):
* have [Syncthing](https://syncthing.net) installed on a PC (optionally https://github.com/syncthing/syncthing-gtk )
* have **syncthing-android** on a device w/ NetGuard
* have them both connected on the same network w/ LAN and w/ Wi-Fi respectively
* **syncthing-android** w/ `run in background`, `sync only on Wi-Fi`, `restrict to this network`
* share at least some folder/content between the mobile device and the PC, eg. _/sdcard/DCIM_ (having it just installed w/ actually syncing any content between devices will not crash NetGuard)
* have the notification with `Normal` priority and hide it
* allow **syncthing-android** in NetGuard on Wi-Fi only (this my test case, also syncing on mobile will eat data ratio pretty fast!)
* **syncthing-android** not excepted in Doze optimizations, but NetGuard excepted
* use the device as normal, this means even turning both Wi-Fi and mobile off.

It will error out (network will be disconnected or although it can connect it does not actually work, NetGuard will log `pselect EBADF` and crash if you try to open it) mostly after a long standby period, network connection state will not matter, mostly seen in the morning (device not touched while sleeping) but got it at all kinds of hours.

Eg. had **syncthing-android** off my device for a week without any crashes, installed it for a few days but not configured still no crashes, then got it set up (several folders) and synced ok, turned screen off for 4 hours, opened the device again only to see it w/o working internet, NetGuard crashed, logcat says EBADF.

**syncthing-android** has it's share of issues regarding Wi-Fi for a while now since the introduction of the `restrict to this network` option, not sure if related. It has the tendency to query a lot of relay and discovery servers on a network change and on a timer, this is my guess for where the issue might be, too many connections. This does not occur with `filter off`, hence it might point out to a bug/limitation in the TCP stack implementation in NetGuard.

Also, might be of importance, the Android app is just a wrapper for the native ARM binary of **Syncthing**, this yields some issues like it can't actually pause the syncing say on a network switch, it has to kill the process and such.

This is the point of https://github.com/M66B/NetGuard/issues/291 have any logcat from there for 5.1.1 or this one for 6.0.1: https://gist.github.com/licaon-kter/d11cffe10cc1e21c19d57ca845686194

**Comment by M66B** [comment]
I have checked the code again, but there is little that can really be done if the kernel reports EBADF.

**Comment by licaon-kter** [comment]
Like I said, that's my reasoning (connection/descriptors/something overload), not sure if true though.
Will test and report.

**Comment by M66B** [comment]
I have reduced the maximum usage of file descriptors of NetGuard to 50% of the available descriptors, maybe it helps.

**Comment by licaon-kter** [comment]
Xperia 6.0.1, root, 2.23: https://gist.github.com/licaon-kter/6950728c345c8fca4236076a77f2dfd6

**Comment by licaon-kter** [comment]
And again just now, it was used pretty often so I guess Doze (although excepted) can't get triggered.
Notification _"stopped by error 9"_, log info like above.

**Comment by M66B** [comment]
You can keep posting comments and logcats, but there is really nothing I can do to fix this. Only your ROM/kernel manufacturer can fix this.

**Comment by licaon-kter** [comment]
What's the gist of things here, if I contact them what should I report? "parcel size"? "TransactionTooLarge"? "EBADF"? "Bad file descriptor"?

**Comment by M66B** [comment]
I don't know what the exact cause is, too little binder memory or (system) applications using too much binder memory. Anyway, they can test with a similar setup as yours.



licaon-kter <notifications@github.com> schreef op 9 mei 2016 09:56:20 CEST:

**Comment by licaon-kter** [comment]
What's the difference between:
`NetGuard.Service: Native exit reason=pselect error 9: Bad file number`
and
`NetGuard.Service: Native exit reason=pselect error 9: Bad file descriptor`
?

FYI, still getting this several times per day, mostly when connected/disconnected from a home selected Wi-Fi in Syncthing, as the first post describes.

Also, I saw the parcel (aka large transaction) crash on yet another Xperia 5.1.1 w/ root.

Again, disabling filter fixes everything, which makes me think it's a matter of a some sort of bug in the IP stack implementation in NetGuard.

**Comment by M66B** [comment]
When I have returned home from Peru where I will travel around for three more weeks, I will look more detailed into this. Please use the similar open issue too attach log files.

**Comment by licaon-kter** [comment]
Hey, have a nice trip, don't bother with these. :)

**Comment by M66B** [comment]
Issue locked, because pselect is not being used anymore.
