### ISSUE TITLE
Easily import Adawy host lists

### ISSUE THREAD

**Issue by threader** [M66B/NetGuard#421]
Apparently, there is no way of downloading, copying/pasting, grabbing, sending, sharing, hugging a file via ANY browser on Android..... ( i feel multi-handicapped ). Managed to grab one list, and paste it via an editor in F-Droid, but the others crap out and wont recognize the copy.....  https://github.com/Free-Software-for-Android/AdAway/wiki/hostssources

**Comment by licaon-kter** [comment]
Copy link to the actual host file ( eg. https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts ) and add it in the proper field maybe?

/close as invalid

**Comment by threader** [comment]
Nothing works. i've got Ted from fdroid, text warrior and text edit, they all ignore the massive copy from Chrome/dev. 

/Real problem

**Comment by licaon-kter** [comment]
I understand, but you're doing it wrong. As a last resort: Termux, `wget link -O /sdcard/hosts1.txt` 

What are you trying to do exactly that using the `insert hosts link here` field is not enough?
(Also not a NetGuard issue per se, hence my /close remark)

**Comment by threader** [comment]
Termux does not have access to /storage/emulated/0 even if i throw holy water on it ...

**Comment by licaon-kter** [comment]
It has here, without root of course, if it does not have it on your device call your ROM manufacturer and complain.

In Android, while only an app has access to its own `/data/data/name.app` folder they all (should) have access to `/storage/emulated/0` or `/sdcard` or whatever is that placed called on your flavour of Android.

/again, not a NetGuard issue, this is a forum post at most, or maybe a Google search

**Comment by M66B** [comment]
NetGuard has an option to set a download URL and download a hosts file and an option to import a local, already downloaded/processed hosts file. This should be sufficient in all cases. Editing/merging hosts files will not be supported from NetGuard.

It looks to me that there is a bug in your (custom) ROM. NetGuard cannot fix this.

**Comment by JMJCOMPANY** [comment]
http://adblock.mahakala.is

If I use this host file (about 30 MB in size), Netgaurd stops due to OOM error

**Comment by M66B** [comment]
There is little that can be done to fix this. The hosts file is already stored efficiently in memory and NetGuard cannot force Android to give more memory.

**Comment by M66B** [comment]
And please do not misuse existing issues to report new problems, but create a new issue

**Comment by threader** [comment]
This is not a custom room, its samsung android 6.0.1, but thanks
