### ISSUE TITLE
Something keeps disabling the app

### ISSUE THREAD

**Issue by archchi** [M66B/NetGuard#423]
There is some app or process that keeps disabling netguard. There is a notification message, but I can't read the entire message because the end is clipped (see attachment). 

I tried to switch it back on, but the underlying issue keeps switching it back off no matter how many times I try switching it back. It seems to be a security issue. My device has been scanned and is clean/free of viruses. 

![screenshot_2016-05-09-15-47-34](https://cloud.githubusercontent.com/assets/18718798/15145312/6eeb6220-167a-11e6-8855-f891a1cde6bc.png)

![screenshot_2016-05-09-15-48-13](https://cloud.githubusercontent.com/assets/18718798/15145219/f70c8676-1679-11e6-847a-46a45a434726.png)

**Comment by licaon-kter** [comment]
What device? What Android version?

**Comment by archchi** [comment]
Device: LenovoTAB2A10-70F
Android: 5.0.1

**Comment by M66B** [comment]
Pull down the notification with two fingers to see the entire text:

Possibilities:

* "NetGuard has been disabled, likely by using another VPN based application", see FAQ
* "NetGuard has been disabled, because of an internal error"

**Comment by archchi** [comment]
Unfortunately, there is no way to expand the notification message in that version of Android. It is a known issue that the scrolling ticker notification was eliminated in 5.0 in favor of Heads Up notifications. In other words, there's no way for me to read the full message.

**Comment by M66B** [comment]
Then the logcat will be the only source of the real problem.

**Comment by archchi** [comment]
Sorry, I misunderstood your previous instructions. The two finger pull did seem to work after all. So here's the screen shot. I'm not sure if it's always the same error message, but this is the latest example. Hope it helps.

![screenshot_2016-05-10-11-55-09](https://cloud.githubusercontent.com/assets/18718798/15155696/4909ae66-16a9-11e6-82cb-22e02908d536.png)

**Comment by licaon-kter** [comment]
/duplicate of #420

/jk finally someone else that has it, #291 feels revenged somewhat, for a bit :)

**Comment by M66B** [comment]
Which NetGuard version are you using?

**Comment by archchi** [comment]
2.23

**Comment by M66B** [comment]
Can you please provide a logcat?

**Comment by licaon-kter** [comment]
@archchi 
NetGuard->Menu->About->tab dialogue 7 times->save logcat.txt->use https://gist.github.com to paste the log contents (do look at the log first for sensitive info) and share the link here.

**Comment by archchi** [comment]
https://gist.github.com/archchi/ec62cf2fd209a19f6b4b16ba311855c5

**Comment by M66B** [comment]
There is nothing about this problem in the logcat :-(

**Comment by archchi** [comment]
For whatever reason, the logcat does not go very far back in history. I only installed the app several days ago. I haven't had the same problem in the past couple of days, thankfully. If it happens again, I will repost a new logcat. That's the best I can do.

**Comment by archchi** [comment]
It happened again

https://gist.github.com/archchi/50469663c1f7b6ba724c714e65374abe

**Comment by archchi** [comment]
https://gist.github.com/archchi/83b91e420acd140c10a8537084461708

**Comment by M66B** [comment]
Even though the last logcat is longer, there is still no unexpected stop in it :-(

**Comment by archchi** [comment]
The last logcat was generated after I had toggled the switch to reenable the app, but it just kept automatically switching back off every time I tried...about 5 times in a row before I gave up.  I have no idea why it's not showing up in the log. I did everything I was instructed to do and the problem still persists.

**Comment by licaon-kter** [comment]
This is #417 again, I guess, although (the 224.0.0.0 error) should be fixed for a while now.

@archchi Can you disable Tethering support in NetGuard->Settings?

**Comment by M66B** [comment]
The route error is properly handled, I already checked this.

licaon-kter <notifications@github.com> schreef op 12 mei 2016 10:16:03 CEST:

**Comment by archchi** [comment]
**@licaon-kter**

The "allow tethering" option is already disabled. Are there any other options I should enable or disable? For example, the "filter traffic" option is enabled by default. Not sure what to try next.

**Comment by licaon-kter** [comment]
Oh then there is nothing that NetGuard could do, more probably a ROM issue.

Regarding my #420 do you run Syncthing or any router/server/proxy on your device?

**Comment by archchi** [comment]
> do you run Syncthing or any router/server/proxy on your device?

No to both.

I'll uninstall the app. Thanks for trying to troubleshoot.

**Comment by licaon-kter** [comment]
Feel free to close this issue then

**Comment by marek287** [comment]
Same problem here. It's started yesterday. NetGuard 2.23. Android 6.0.1. Nexus 5x stock ROM.

**Comment by M66B** [comment]
Please provide a logcat.

marek287 <notifications@github.com> schreef op 13 mei 2016 07:12:25 CEST:

**Comment by marek287** [comment]
[logcat.txt](https://github.com/M66B/NetGuard/files/262585/logcat.txt)

**Comment by M66B** [comment]
Can you please try if this version improves things:
https://github.com/M66B/NetGuard/releases/tag/2.24

**Comment by marek287** [comment]
No, same problem.
[logcat.txt](https://github.com/M66B/NetGuard/files/263940/logcat.txt)

**Comment by M66B** [comment]
Too bad :-(

**Comment by marek287** [comment]
My bad. I am using Doze application and NetGuard was not at Active list. I don't know how it was removed. Apologises. Sorry
