### ISSUE TITLE
Show Mobile vs. Wi-Fi Data Usage Separately?

### ISSUE THREAD

**Issue by 808scotti** [M66B/NetGuard#424]
Netguard (v.2.23) can sort apps by data usage and presently shows the amounts uploaded & downloaded.  It appears that both mobile and wi-fi data is tallied ([screenshot](https://www.dropbox.com/s/92ctht9jwresgwj/Screenshot_20160510-085623.png?dl=0)).  Is there a way to have Netguard show (& sort) only the amount of mobile data used, perhaps as a user setting?  I'm mostly concerned with staying under my data cap, so I'm not as concerned with wifi.  Thanks for considering this.

**Comment by M66B** [comment]
Unfortunately Android doesn't provide these statistics to application.

Relevant documentation: http://developer.android.com/reference/android/net/TrafficStats.html

**Comment by 808scotti** [comment]
That's too bad, but thank you for responding, Marcel.  Netguard works well and I particularly like having certain apps enabled & disabled as a group.  It's a small touch, but one that reflects a developer using his knowledge to offer a more refined interface to his users and keep them out of trouble.  Thanks.

Scott

**Comment by licaon-kter** [comment]
> certain apps enabled & disabled as a group

That's an Android limitation: https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ31 :)

**Comment by 808scotti** [comment]
> >certain apps enabled & disabled as a  group
That's an Android limitation: https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ31 :)
> 

Yep, I saw the FAQ and I actually like the simplicity. :-)

**Comment by licaon-kter** [comment]
That depends on the ROM manufacturer, Samsung 5.0.2 has even >70 system apps on the same UID.

**Comment by 808scotti** [comment]
Yow.  Good to know.
