### ISSUE TITLE
Ad blocking not working correctly in HTC one M8

### ISSUE THREAD

**Issue by Esquirish** [M66B/NetGuard#426]
I tried NetGuard an was able to set it up correctly to block ads on HTC one M8 with android 6 (stock GPE, not rooted), however any page with ads embedded take forever to load in chrome, any page with ads take a minute or so to load the first 15% of the page, then the content loads but the page continues loading until about the 3~ minute mark. The ads are blocked correctly but the loading time are clearly affected.

**Comment by licaon-kter** [comment]
Probably the browser waits for those servers to respond, they'll never will since they're blocked.

Firefox works ok? Opera (no Turbo!) works ok?

/mark as invalid

**Comment by Esquirish** [comment]
Firefox presents the same problem. Loading times vary a bit but still waiting that much for a page to begin rendering is frustrating to me. I'm surprised no one has me tiones this issue. Perhaps it's exclusive to HTC phones? For example BBC News page takes a minute+ to begin rendering. Is that the expected behaviour?

**Comment by Esquirish** [comment]
Sorry for the spelling mistakes, writing from my phone

**Comment by licaon-kter** [comment]
Not sure I can confirm, bbc loads pretty fast.

Now, it might be a speed issue, if so, do test with a big file, once with NetGuard off, once with `filter off` and once with `filter on`.

Eg. download (on Wi-Fi) the latest Ubuntu.ISO and see the (average?) download speed in each case.

**Comment by M66B** [comment]
This has recently been discussed and answered on XDA.

In short: NetGuard says the ad domain does not exist, but on some devices this seems to be ignored. There is nothing that can be done to fix this from NetGuard.

**Comment by Esquirish** [comment]
I forgot to specify the issue is present while browsing on WiFi. The sites load normally when filtering is disabled. Will do the download speed tests

**Comment by Esquirish** [comment]
I see, thanks for the response.
