### ISSUE TITLE
No auto start on reboot with Asus ZenFone 2 Laser

### ISSUE THREAD

**Issue by GlenHertz** [M66B/NetGuard#427]
Hi,

Great software!  Running ASUS Android 5.0.2 (latest version) on an Asus ZE551KL (Z00TD), Netguard doesn't automatically start on reboot.  Likely a ROM bug but I thought I would report it in case others are looking to buy a phone or have the same issue.  I tapped the About window 7 times to get the log file:

https://gist.github.com/GlenHertz/e86b46cfa76ab144dcf9816ee8ed67c8

Glen

**Comment by M66B** [comment]
NetGuard will attempt to start on boot when your device was powered down with NetGuard enabled, however, some Android versions contains bugs and this attempt will fail. This can unfortunately not be fixed from NetGuard.
