### ISSUE TITLE
No internet through WiFi hotspot (BQ Aquaris M5)

### ISSUE THREAD

**Issue by WoogieBoogie** [M66B/NetGuard#428]
Hi,
While having netguard active my wifi Hotspot doesn't deliver any internet although other devices can connect to it.

**Comment by licaon-kter** [comment]
Probably a ROM issue, since you've toggled tethering ON right?

What Android version?

**Comment by M66B** [comment]
Did you enable subnet routing and tethering in the settings?

WoogieBoogie <notifications@github.com> schreef op 16 mei 2016 18:25:45 CEST:

**Comment by WoogieBoogie** [comment]
licaon-kter 
commented
Probably a ROM issue, since you've toggled tethering ON right?

- yes, tethering (WiFi Hotspot) is on.

What Android version?

- 5.1.1 Bq original. No root or whatsoever.

M66B commented
Did you enable subnet routing and tethering in the settings?

- how do i do that?

Thanks for the quickness.

Ps. Other devices can't actually connect to the wireless network while netguard is on. Once it's off other devices can succefully connect.

**Comment by M66B** [comment]
As said you can enable subnet routing and tethering in the settings.

WoogieBoogie <notifications@github.com> schreef op 17 mei 2016 01:59:03 CEST:

**Comment by WoogieBoogie** [comment]
In deed.
This is no problem at all, just a user misundertanding.

Sorry for the trouble and thank you both.
