### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by venusdharan** [M66B/NetGuard#429]
Hi Im quite new with NDK projects, The project source code is downloaded from github and opened in Android Studio and i added the NDK to SDK folder and pointed it to it.
But the build is get error.
the output.txt contents are the following
See file:///NetGuard-master/app/build/tmp/compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC/output.txt for all output for compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC.
compiling dhcp.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling pcap.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling icmp.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling ip.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling netguard.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling dns.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling util.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling udp.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling tcp.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

compiling session.c failed.
clang.exe: error: argument to '-x' is missing (expected 1 value)
clang.exe: error: no input files

Finished compileNetguardArmeabi-v7aDebugSharedLibraryNetguardMainC, see full log 

how to resolve this issue, i tried to google for it but couldn't find a satisfactory answer

**Comment by M66B** [comment]
Please see the GitHub instructions on building.
