### ISSUE TITLE
Feature: VPN client inside NetGuard

### ISSUE THREAD

**Issue by ni720** [M66B/NetGuard#430]
Hello,

how about if NetGuard had its own built-in VPN client?
This way only one app uses the VPN service and still a VPN connection would be possible.
So all blocked traffic gets rerouted to 127.0.0.1 and the rest to the actual VPN (if the option is turned on).
Of course one would have to enter the VPN connection details and credentials within the NetGuard app.
I know this would be a lot of work, but it would "fix" the only downside of NetGuard beeing a non-root firewall.

I know something similar was requested with: https://github.com/M66B/NetGuard/issues/366,
but I think it should be the other way around (the firewall should have a vpn client and not the vpn client a firewall).

Thanks for considering!

**Comment by M66B** [comment]
I don't think it is a good idea to duplicate openVPN in NetGuard and going to maintain two openVPN applications.
