### ISSUE TITLE
Disables all networks connectivities when data network is disabled

### ISSUE THREAD

**Issue by rkeshmir** [M66B/NetGuard#433]
I installed the app on android version 4.1.2
When I enable the option that prevent all apps from connecting via data network, all other networks like WiFi are also disabled.

**Comment by licaon-kter** [comment]
Device? Android OEM version or CM or ?

**Comment by M66B** [comment]
Please provide screenshots of the technical information in the settings while this problem is occurring.

**Comment by M66B** [comment]
Without more information there is little that can be done.
