### ISSUE TITLE
Low/high bandwidth condition

### ISSUE THREAD

**Issue by sebaschn** [M66B/NetGuard#435]
Dear NetGuard Team,

I frequently travel between the city and country back and forth.
Since I have a very good bandwidth in the city, I use like several apps at once (Maps, messaging, email, games ...). But as soon as I have a bad connection, I would like to block all nonessential apps.

The idea:
How about with different profiles, from which you can change the settings of the apps, as does the situation require?

Greetings from germany
S. Schneider

**Comment by licaon-kter** [comment]
You already have those:
* set up as for city1
* export city1.xml
* set up as for city2
* export city2.xml

Enter City1->Import city1.xml... you get the point.

**Comment by M66B** [comment]
Profiles of not a planned feature, see the FAQ about why.
However, I am willing to investigate a new condition "when high bandwidth".

**Comment by M66B** [comment]
I am thinking about this:

Low bandwidth: GPRS, EDGE (2G)
High bandwidth: HSDPA (3G), LTE (4G), Wi-Fi

Would this work in your case?

sebaschn <notifications@github.com> schreef op 6 juni 2016 10:30:46 GMT-05:00:

**Comment by sebaschn** [comment]
@licaon-kter: thanks for the idea. this is exactly what i was looking for.
since i am not an expert i did'nt know to use the export feature as profiles.
well, it isn't the most comfortable way to switch settings, but it did the job.

@M66B: i'm sorry if there was a missunderstanding. i never thought about automatic profile changing. it would be enough if i could change these exported files via a dropdown or something like that.
that would be much more userfriendly and since you already have the import/export feature that shouldn't be much work to implement, isn't it?

so far great thanks to you. i like the app very much !! great work :-)

**Comment by M66B** [comment]
https://gist.github.com/emil2k/5130324

**Comment by M66B** [comment]
The network type is not a good indication for the available bandwidth. A 3G HSDPA connection can even have a lower actual bandwidth than a 2G EDGE connection. Measuring bandwidth will only work when there is traffic, which might be a good solution to scale the work in an application like Facebook, but it isn't for NetGuard. It could even result in chicken/egg problems.

Summarize: I see no reliable way to implement a bandwidth condition.
