### ISSUE TITLE
TCP fragmentation

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#437]
Having these regularly Netguard crashes ( `filter on` ) with [i2p](https://github.com/i2p/i2p.android.base) router running:
```
E NetGuard.JNI: IP fragment offset XXXX
W NetGuard.Service: Native error 2: TCP fragmentation
```

XXXX is 4864 or 5120 or 5632 (as in, they did not vary, these are the values in the logcats over a long period of time, say weeks)

/LE: Oh, though you were back, nvm then, this will wait. :)

**Comment by M66B** [comment]
Fragmentation should not happen with an MTU of 10,000

**Comment by M66B** [comment]
This could be caused by the application changing the MTU or by the application sending too large packets.

**Comment by licaon-kter** [comment]
@str4d Any idea?

**Comment by str4d** [comment]
Is this an issue with I2P integration in NetGuard, or an issue with running I2P while NetGuard is running? (I don't know this app. Hi!)

**Comment by M66B** [comment]
I2P is not integrated into NetGuard, so it is an issue running I2P alongside NetGuard.

**Comment by licaon-kter** [comment]
@str4d Alongside, i2p does it thing while NetGuard allows i2p's access to the network, either by not blocking it's access to the local VPN (`filter OFF` in Settings; but I have not seen this issue while setup it like this) or by routing and allowing i2p into the local VPN (`filter ON` in Settings; this is where the issue is seen)

**Comment by licaon-kter** [comment]
Build at 711b869 , I wasn't expecting a fix for this anyway.
I got a dozen of these while walking out of Wi-Fi range so mobile would have kicked in, although it complains a lot about network unreachable, but that should not be an issue (I guess):

```
E NetGuard.JNI: IP fragment offset 4864
W NetGuard.Service: Native error 2: TCP fragmentation
E NetGuard.JNI: uid v4 p17 10.1.10.1/17080 not found
W NetGuard.Service: Allowing unknown system uid=-1 v4 p17 someIP/port
```

**Comment by M66B** [comment]
@licaon-kter nobody else complained about this, so this is being caused by i2p sending fragmented packets. This won't be a problem on non rooted devices, for which NetGuard was designed.

**Comment by licaon-kter** [comment]
i2p does not need root, not sure what you meant with that.
Anyway, it happens pretty often here even with build up to c8fcf87

**Comment by M66B** [comment]
Since assembling IP packets is expensive in terms of CPU and memory usage and this is the only known use case where packets seems to be fragment, I have chosen to drop any fragmented packets.

**Comment by M66B** [comment]
@licaon-kter I am not sure what you mean by '_auto forced logcat saving_', since nothing is being forced saved.

**Comment by M66B** [comment]
@licaon-kter can you please test if i2p still works and if it doesn't create a pull request to add a note that i2p [is incompatible](https://github.com/M66B/NetGuard/#compatibility) with NetGuard?

**Comment by licaon-kter** [comment]
> I am not sure what you mean by 'auto forced logcat saving', since nothing is being forced saved.

Not sure how to describe it, basically you see the notification with the error (but sometimes it disappears all by itself and reappears multiple times in a row), and when you touch it NetGuard opens directly with the save logcat.txt view, so you save it.

Is that how it's supposed to be so one can log (these or other) errors?

**Comment by M66B** [comment]
The error handling has been changed recently, so no 'forced saves' anymore.

Fragmented packets will just be dropped, so no leaking.

**Comment by licaon-kter** [comment]
`E NetGuard.JNI: epoll mod tcp error 2: No such file or directory` is the new error? Because I get plenty of these now.

**Comment by M66B** [comment]
It is the first time this error is reported.
I need a logcat to look into it.

**Comment by M66B** [comment]
Also, please create a new issue for this, since it is unrelated to this issue.
