### ISSUE TITLE
No connection after switching airplane mode/wifi/mobile network

### ISSUE THREAD

**Issue by antnm** [M66B/NetGuard#438]
Sorry if this has been raised already, but I couldn't find it in previous issues (may be related to #395?).
I have a Huawei P9, 6.0, no root, filter on with default hosts.
All connections (any app) are blocked when i disable the airplane mode and when the mobile automatically switch from mobile network to wifi. 
Switching netguard off & on again solved the problem

**Comment by antnm** [comment]
By the way (should have said that first actually), great job. Thank a lot netguard is an awesome project, this issue is a very little thing compared with how easy netguard makes it to manage connections

**Comment by licaon-kter** [comment]
Log?

**Comment by licaon-kter** [comment]
Log? _NetGuard->menu->About->tap dialogue 7 times->save the file-> paste it at https://gist.github.com ->paste link here_

**Comment by antnm** [comment]
848153ed7364e6c21d158d60bd1b789b

**Comment by antnm** [comment]
https://gist.github.com/antnm/848153ed7364e6c21d158d60bd1b789b

**Comment by antnm** [comment]
What I did here was : switch airplane mode on then off, load a webpage in chrome (failed), switch netguard off and on again, load same webpage (successfully)

**Comment by antnm** [comment]
https://gist.github.com/antnm/08e8b3ff06bb89d13a4f7b5253263620
This log is before switching netguard off & on again, sorry for double posting

**Comment by licaon-kter** [comment]
Can you try with `filter off`?

**Comment by antnm** [comment]
Same issue

**Comment by licaon-kter** [comment]
New log please.

**Comment by antnm** [comment]
Edit: finally it seems that not ALL connections are blocked. Some protocols seem to work, others don't. Some of my apps are connected, others like chrome not at all and even within a single app some contents are updated while others are not (e.g update on weather data but ads are not loaded even though filter is off)

**Comment by licaon-kter** [comment]
An idea, restarting Chrome after the network change helps?

**Comment by antnm** [comment]
New log: https://gist.github.com/antnm/4c424e977bfe93a7ac0276093c373be4

**Comment by antnm** [comment]
Restarting chrome doesn't help

**Comment by M66B** [comment]
Which Android version?
It looks like your Android version doesn't send network changed events.
A log file is needed to diagnose this.
Log files are often large, so please indicate the time of the event.

antnm <notifications@github.com> schreef op 7 juni 2016 10:50:32 GMT-05:00:

**Comment by antnm** [comment]
https://gist.github.com/antnm/5b461156c9580878e27af235166248d3
Switched airplane mode on at 19:17:50
Switched airplane mode of at 19:18:00
Tried to load something in chrome at 19:18:30
Wrote log at 19:19:00
Running Android 6.0 (with EMUI 4.1 from Huawei)

**Comment by antnm** [comment]
So sorry, I found the problem, doesn't come from netguard. I forgot I left some wrong advanced config settings on my wifi network (proxy). This is what caused connection errors when turning the airplane mode back off (regardless netguard being switched on or not). Everything is working fine now

**Comment by licaon-kter** [comment]
do close this then
