### ISSUE TITLE
pselect error 9: Bad file numer

### ISSUE THREAD

**Issue by web-web** [M66B/NetGuard#440]
Netguard sometimes disables itself, and displays notification about being disabled due to an error. I managed to get adb logcat. The error appears to be:

Android 4.4.2
Device: Samsung G355H
NetGuard 2.25
[logcat.txt](https://github.com/M66B/NetGuard/files/311280/logcat.txt)

**Comment by web-web** [comment]
Yes, I see that there are a few other same issues, but like to provide you with an additional information, in order to help you fix them!

**Comment by licaon-kter** [comment]
Then close this and provide said info (nothing new in you logcat now) in the other issue.

**Comment by M66B** [comment]
Thanks for the log file, but please follow the referenced open issue for progress on this problem.

**Comment by M66B** [comment]
Issue locked, because pselect is not being used anymore.
