### ISSUE TITLE
Quick manage speed graph notification

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#442]
On: status bar action in main notification
Off: swipe away speed graph notification

**Comment by licaon-kter** [comment]
Two issues here:
* swiping the graph notification dismisses it, I find it counter productive
* GRAPH button in notification ONLY toggles it ON, on touching again it makes the graph notification disappear for a second but then it reappears.

**Comment by M66B** [comment]
Swiping is a common way of dismissing notifications.
Tapping the graph button again will reset the graph.

**Comment by M66B** [comment]
Unfortunately swiping away will not work if the speed graph notification is shown without the service running.
