### ISSUE TITLE
Setup wizard

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#444]
Select on first run:

* White/black list mode
* Manage user/system applications
* Allow/block push messages (Play services)
* Add NetGuard to battery saver exception list
* Add NetGuard to data saver exception list (Android N)

**Comment by licaon-kter** [comment]
/duplicate of #178 but hey, glad it's on your mind :)

**Comment by M66B** [comment]
There is now more reason to include a setup wizard, for example to configure the new Android N data saver. Also, user feedback learns that some less experienced users need more guidance than I anticipated.

**Comment by M66B** [comment]
There is now more reason to include a setup wizard, for example to configure the new Android N data saver. Also, user feedback learns that some less experienced users need more guidance than I anticipated.

**Comment by mva1985** [comment]
The app is kinda an advanced app imho...  that's not a bad thing

**Comment by pulser** [comment]
A hybrid approach half-way towards a full setup wizard, without all the effort, would be a "welcome" screen, showing the 4 main features of the app. This gives a framework around which the wizard can be added going forwards.

I'd suggest perhaps the 4 main features are:

1. Blocking apps from the internet entirely. Block inbuilt or system apps you don't want/need, and keep apps that shouldn't need the internet away from it.
2. Block ads, tracking/social, and other user-hostile things on the internet
3. Save data. Control what can use data/wifi. Prevent background data too if you want to save power.
4. Take control over exactly what an app can do online, and where it talks to

**Comment by M66B** [comment]
Instead of an intrusive wizards, I have added hint texts.

The Android N data saver is by default disabled, so there doesn't need to be a wizard to configure this. There will be an alert dialog when opening the UI when the data saver has been enabled, similar to the one for battery optimization.
