### ISSUE TITLE
Notification issue with Android N-ify

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#446]
Using [Android N-ify](http://forum.xda-developers.com/xposed/modules/xposed-android-n-ify-features-t3345091) the notification can't be expanded, I can only see `Enforcing rules` and the expand gesture does not show the `allowed,blocked,hosts` text line.

Not sure if this actually mirrors Android N behaviour or just an app (Android N-ify that is) implementation glitch.

**Comment by M66B** [comment]
I don't see what I can do from NetGuard to solve this issue.
Android N-ify is basically Android marshmallow for which NetGuard works. I will look into Android N support later, but I don't think that will solve this issue

**Comment by licaon-kter** [comment]
Other apps (say [Conversations](https://github.com/siacs/Conversations/) or [ForceDoze](http://forum.xda-developers.com/android/apps-games/app-forcedoze-force-doze-mode-screen-t3377694)) expand their lower info ok, but they might use a LOW priority notification type instead.

**Comment by licaon-kter** [comment]
Fixed in https://github.com/M66B/NetGuard/commit/ffca21cba1fb1c6a69280c9d8a6a18446c0279a4 :)

**Comment by M66B** [comment]
Then adding the action fixes it.
A lucky change!

**Comment by licaon-kter** [comment]
Oh, reverted :(

Maybe you can keep the other changes (no buttons I mean) though?

**Comment by M66B** [comment]
There were no other changes, except for the buttons.

**Comment by licaon-kter** [comment]
Oh, interesting, I'll try to make some pics so you can see the difference.
