### ISSUE TITLE
Reorganize settings

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#447]
Reorganize settings using custom views.

Refs: https://github.com/M66B/NetGuard/commit/865b0695a9d2edc811519f646cdad93271021db1

**Comment by eshultz** [comment]
Perhaps move the "download hosts file" menu entry to the "advanced options" menu rather than "backup"?

**Comment by M66B** [comment]
@eshultz I understand the idea and it would allow to make the hosts file settings dependent on 'filter' again (which was removed to fix a crash on some devices), but people are now used to find these settings in the backup section, which is related to file operations, and it would make the advanced section even more crowded than it already is.
