### ISSUE TITLE
Captive Portal

### ISSUE THREAD

**Issue by qwerty017** [M66B/NetGuard#448]
I see that NetGuard can tell when it is on a Wifi with a Captive Portal so is there a way to force an app to use the Wifi connection through Netguard even if the Portal has not been logged into yet? I have tried blocking the app from accessing the cell connection in Netguard but then it just hangs. I am currently using a Samsung S7 with latest android updates and 2.25 Pro version of Netguard.

Example: I use a captive portal autologin app. If the captive portal has not been either logged into already or the Keep Connection button isn't pressed then it will be forced out the cell connection instead of going through the wifi connection to login to the portal.

**Comment by M66B** [comment]
I am sorry, but this is not what NetGuard is designed for.

**Comment by qwerty017** [comment]
Ok. I didn't know if there was a way to force an app to use a specific
connection so decided to ask. Thank you for the quick reply.

On Thu, Jun 23, 2016 at 12:13 PM, Marcel Bokhorst <notifications@github.com>
wrote:

> I am sorry, but this is not what NetGuard is designed for.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/M66B/NetGuard/issues/448#issuecomment-228154402>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AANP-4TTEhALpQzNO-XUO03Y2pIy_lyQks5qOtq-gaJpZM4I9JEo>
> .
>



-- 
Life is a tragedy for those who feel, and a comedy for those who think.
