### ISSUE TITLE
Why does NetGuard use so much data?

### ISSUE THREAD

**Issue by isaacgallegos** [M66B/NetGuard#449]
I googled around and found no explanation. 
![screenshot_2016-06-24-01-51-33](https://cloud.githubusercontent.com/assets/19722267/16330373/5ddf4cba-39ae-11e6-9361-ab2b479e7528.png)

**Comment by M66B** [comment]
So, why not take a look into the FAQ?
https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ32
