### ISSUE TITLE
Unfair Play store ratings

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#450]
Demotivating unfair Play store ratings

**Comment by M66B** [comment]
Refs: https://bugs.launchpad.net/ubuntu/+bug/1

**Comment by licaon-kter** [comment]
Tot sure what the ref should tell us!?

**Comment by M66B** [comment]
It is a similar impossible issue.

**Comment by eshultz** [comment]
Note: I attempted to drop a 5 star rating and detailed description in the Play Store, but it's not allowed - Play Store recognizes that I do in fact have the app installed, but won't let me rate since "you are running a test version of this app".

**Comment by M66B** [comment]
Why would you want to drop a 5 star rating?

**Comment by eshultz** [comment]
Sorry, didn't mean "drop" as in remove. I meant "drop" as in "leave something".

I was trying to give the app a 5 star rating.

**Comment by M66B** [comment]
Users subscribed to the [Play store test program](https://play.google.com/apps/testing/eu.faircode.netguard) cannot rate/comment, so you will have to (temporarily) unsubscribe.

**Comment by eshultz** [comment]
I'm not subscribed though, I don't think. The link you posted takes me to the invitation "become a tester" page.

I am using the apk from GitHub, not the play store, perhaps that's why? Maybe Play recognizes the app signature but assumes if the apk is not one that's been published then it must be a test version?

**Comment by M66B** [comment]
Could be. If that is the case you can solve it by uninstalling the GitHub version, installing the Play store version and installing the GitHub version over the Play store version.
(don't forget to export your settings first)

**Comment by eshultz** [comment]
This worked perfectly, thank you
