### ISSUE TITLE
Allow mobile when screen is on is not working on Note 4?

### ISSUE THREAD

**Issue by ilkerhk** [M66B/NetGuard#451]
On android 5.1.1. Note 4 couldn't make this feature work. 
It works on my wifes s5 with android marshmallow. 
Below is how to replicate the issue : 
- Check  "Allow mobile when screen is on is not working" for an app, say chrome. 
- Open chrome and try to browse and observe no internet connection
- in the notification netguard complains "chrome attemted internet access". There are no other complains...

**Comment by M66B** [comment]
Please provide a logcat directly after turning the screen on.
Logcat: tap seven times on the title of 'about'.
If you send it by email, please reference this issue (else it will likely be ignored).

**Comment by ilkerhk** [comment]
Hi,
I disabled "manage system applications" and it seems working now. I will send you the log if it repeats.
Thanks...

**Comment by licaon-kter** [comment]
Do get a log with "manage system apps" enabled.
You could enable "logging" and "notify attempts", when it does not work so you can see what app can't reach (address with red in notification)

**Comment by M66B** [comment]
My best guess: Chrome is a system application, which was not allowed when screen is on (or maybe a related component).

**Comment by ilkerhk** [comment]
I enabled "manage system apps" again and now interestingly it seems all working. I don't know may be I enabled some system app this time... Anyways thanks for quick responses. 
I will revive this topic if it happens again but seems working smooth now.
