### ISSUE TITLE
View top mobile data using apps

### ISSUE THREAD

**Issue by ilkerhk** [M66B/NetGuard#452]
Is there a way to see the apps with the most mobile data usage ?
When I sort by "data usage" I think it counts both wifi+mobile....

thanks.

**Comment by M66B** [comment]
Unfortunately Android has no APi for that.
See here: https://developer.android.com/reference/android/net/TrafficStats.html

**Comment by M66B** [comment]
To be clear: it is possible to request the total bytes sent/received via a mobile data connection, but not per application.
