### ISSUE TITLE
Android N compatibility

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#453]
* [Notifications](https://developer.android.com/preview/features/notification-updates.html) done)
* [Always-On VPN](https://developer.android.com/preview/features/afw.html#always-on-vpn) (done)
* [Data saver](https://developer.android.com/preview/features/data-saver.html) (done)
* [Direct boot](https://developer.android.com/preview/features/direct-boot.html), [more info](https://android-developers.blogspot.nl/2016/04/developing-for-direct-boot.html) (not possible)

**Comment by M66B** [comment]
Android doesn't allow starting the VPN service in direct boot mode.

**Comment by M66B** [comment]
New Android N notification layout:
http://android-developers.blogspot.nl/2016/06/notifications-in-android-n.html

This is somewhat problematic, since Google added the application name to the notification. However, NetGuard already often shows the application name as title and the message as content text. The problem is that the context text is often too long to be used as title.

**Comment by manad777** [comment]
With the Always On feature, is Netguard's vulnerability window at system startup gone? Have you ran tests where you monitor your connections at the firewall/router level?

**Comment by M66B** [comment]
No, I didn't test this, but according to the always on VPN documentation this should be the case. Always on VPNs are also intended for company environments, so it is reasonable to assume Google did resolve this decently.

**Comment by manad777** [comment]
What could be done about this, other than waiting for N? (for which Xposed/Xprivacy support won't follow for a long time)

I don't know much about iptables, but could it be used to provide a solution for root users? Have a dummy iptables config that prevents all traffic, which is what the system always boots with. During Netguard init, undo those rules in a non-persistent way.

**Comment by licaon-kter** [comment]
See AFWall Wiki, it's pretty hard to do.

**Comment by pylerSM** [comment]
Quick Tile to on/off NetGuard?

**Comment by M66B** [comment]
Quick settings tile has been added
