### ISSUE TITLE
Drop support for Android 4.0-4.3 (SDK 14-18)

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#454]
Refs:

* http://forum.xda-developers.com/showpost.php?p=67492630&postcount=2697
* https://source.android.com/source/build-numbers.html

Benefits:

* Less support requests for unsolvable problems, less bad ratings/reviews
* Permission WRITE_EXTERNAL_STORAGE can be dropped

Only a small number of users will be affected by this (based on Play store statistics).

**Comment by M66B** [comment]
Another benefit is that the native code, which is forward compatibly only, can be compiled for a more recent SDK version as well, resulting in better optimized code and more variety in processor architectures.

**Comment by licaon-kter** [comment]
Given the current NetGuard status (aka pretty ok if it worked already), I guess that's fine.

**Comment by licaon-kter** [comment]
Why the change of heart?

**Comment by M66B** [comment]
Play store statistics:

Android 6.0 | 35,86%
Android 5.1 | 24,94%
Android 5.0 | 18,04%
Android 4.4 | 13,94%
Android 4.2 | 2,92%
Android 4.1 | 1,95%
Android 4.3 | 1,33%
Android | 4.0.3 - 4.0.4 0,60%
Other | 0,42%
