### ISSUE TITLE
Notifications on a specific app are still appearing

### ISSUE THREAD

**Issue by sebaschn** [M66B/NetGuard#457]
Dear Net-Guard Team,

i'm using the App "jodel" 
( https://play.google.com/store/apps/details?id=com.tellm.android.app&hl=de )

there you can post things like twitter and comment others. these "jodels" are voted.
If your posts or comments are voted or commented, you will recieve a notification

When i'm disabling it, the notifications are still appearing. But when i'm openig the app, it can't connect to the internet, as it shouldn't.

maybe you have an idea or there is still a backdoor in your app?

greetings and thanks!

**Comment by M66B** [comment]
Push messages are almost always handled by the system component Play services and not by applications themselves, so there is no backdoor, but you'll need to block a system component from accessing the internet. Note that you'll block push messages for probably all applications.
