### ISSUE TITLE
epoll mod tcp error 2: No such file or directory

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#458]
Logcat grepped on this and connection status: https://gist.github.com/licaon-kter/022ae2c86308e218b0c503ad2b27f38d

I have plenty of logcats that feature this, any pointers on what to look/grep for?

**Comment by M66B** [comment]
Can you try if with the latest commits there are less error messages like this? There is a commit which closes the TCP session when encountering this problem, preventing the error from repeating.

In any case this is better than with pselect, because NetGuard doesn't die on it anymore.

**Comment by licaon-kter** [comment]
Updated to c23b03c and rebooted (for ca17b09d).
I'll dump a logcat later today to inspect.

**Comment by licaon-kter** [comment]
Looks ok for now.
