### ISSUE TITLE
Issues with ad blocking instructions

### ISSUE THREAD

**Issue by kxra** [M66B/NetGuard#459]
"Enable the setting 'Block domain names' (default enabled)
Import or download a hosts file using the NetGuard settings"

the block domain names setting is visible in the network settings section of the app settings menu, but can not be enabled because there is no hosts file. 

i also do not see where to import a hosts file in the settings. 

either way, these two instructions should be swapped so that the importing is first, and probably clarity added on how/where to do these two actions

**Comment by M66B** [comment]
There setting to block domain names depends only on the filtering setting, no on the import/download of a hosts file. The instructions are therefore in the correct order.

**Comment by M66B** [comment]
I always forget the the use hosts setting is set in another way as well.
