### ISSUE TITLE
NetGuard tries to connect to crowd/github

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#462]
...on network connection toggled on, although both `check for updates` and `submit usage data` are disabled.

**Comment by M66B** [comment]
I don't think so.

GitHub update check:

https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ServiceSinkhole.java#L506

Share usage data:

https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/ServiceJob.java#L132

It could be that usage data has been queue before turning sharing of usage data off.

**Comment by M66B** [comment]
I have just checked and usage data will not be queued when sharing of usage data is turned off.
I am quite sure the update check will be turned off, since this was tested before.

**Comment by licaon-kter** [comment]
> I don't think so.

I see the notification.
I see the log entries.

> It could be that usage data has been queue before turning off sharing of usage data.

How do I clear that queue?

**Comment by M66B** [comment]
You can't clear the queue, even a reboot will not help, this is by design.

I am quite sure the update check will not be done when it is disabled.

**Comment by licaon-kter** [comment]
Clear data should do it, right?
But, on restart the queue will be remade since it's ON by default, hence it will try to connect to crowd again? 

Maybe reopen this then.

**Comment by M66B** [comment]
I am not sure if clear data will clear the queue, since Android manages the queue.
It would be interesting to know.

My reasoning is that anything in the queue was user approved.
Note that only changed settings will be put into the queue.

**Comment by licaon-kter** [comment]
Again, it's **on** by default on install.

When is the queue created?

Can the user have a chance to disable sharing **before** creation?

**Comment by M66B** [comment]
Yes, it is on by default on install and yes you can disable the setting to share usage data before usage data is being shared, by doing this before changing any of the settings.

**Comment by licaon-kter** [comment]
Then this needs to be properly documented, maybe add another bottom notification for paying users that asks them if they want to contribute or not and *not* make any queue to submit until you get that yes or no answer.

**Comment by M66B** [comment]
Everybody accepted the updated terms and condition at first startup, so everybody basically opted in.
Pro feature users have the option to opt out again and nothing will be queued until settings are being changed, which I will document in the FAQ.

**Comment by licaon-kter** [comment]
Umm, Pro feature users will also send data (at least once), the order of setup steps does not include reading the FAQ, the condition "one setting was changed" is not intuitive.

Yes the first screen includes that info, but I feel it would be nicer that the usage data is collected and queued on first network connection, not on app start where it can't be cancelled anymore and it will be sent on first connection.

**Comment by M66B** [comment]
The term & condition dialog clearly mention that pro feature users will be able to disable sharing usage data.

Usage data is queued/sent only after changing settings, so no data is being sent automatically. So, pro feature users have the option to opt out before anything has been sent.

To me it seems obvious that usage is needed to send usage data.

**Comment by licaon-kter** [comment]
It does not say that a submit is made if one fails to disable submissions before changing even one setting.

**Comment by M66B** [comment]
IMHO this is quite obvious.

**Comment by licaon-kter** [comment]
Again it is not, consider this, even a careful/privacy aware user probably will setup it like this:
* clean install
* network off
* read info that does *not* urge one to "DISABLE THIS NOW IF YOU WANT **OR** ELSE..."
* setup setting/import settings
* data is queued for submission BY DEFAULT
* user disables submissions being sure his/her data is NOT shared anywhere
* network on
* data is submitted EVEN if submission is OFF

**Comment by M66B** [comment]
Setup settings = usage = queuing/sending.
IMHO this is quite obvious.

Moreover, no harm is done in any way, because no privacy sensitive data whatsoever is being sent.

**Comment by licaon-kter** [comment]
The info says *"free version...data submission"8, now this is forced on paying users too, by omission, a FAQ entry somewhere does not *make it fair*.

Also, your users are mostly free-loaders, I guess, hence you're not missing out on that much data from those users. Privacy sensitive or not has nothing to do with it, imho.

Why do you want this (like that) so much though? Why not hold the data until a connection? Why not make the queue in such a way that once submission is disabled the queue is cleared?

**Comment by M66B** [comment]
Nothing is forced upon pro feature users, since they can disable sending usage data right away, which is stated on first run also right away. Nevertheless it is a good idea to clear the queue on opting out, see commit. The queue involves waiting for an unmetered connection already, so this will work as you would expect.

**Comment by licaon-kter** [comment]
Thank you.

**Comment by M66B** [comment]
Thanks for bringing this up as well.
I might be stubborn as times, but I will always listen to arguments.
