### ISSUE TITLE
"Check for updates" needs option to ignore beta releases

### ISSUE THREAD

**Issue by kiuuik** [M66B/NetGuard#473]
"Check for updates" (in Settings - Options) should offer more options like "show all releases including betas", "show only regular releases" (and maybe even "show only major releases and versions with critical bugfixes")

I have searched the issues section and your FAQ but didn't find anything useful.

I'm not a pro user but I care a little bit about privacy. So I bought your app on Google Play with all In-App Products. After some time I switched to the github version to have adblocking. 
In the last days I get daily reminders that a new version is available. Whenever I check on github it's only a beta. I don't think a beta is good for a regular user. That's too time consuming. So for me (and I think most users) an option like "show only regular releases" would be helpful.

I think an even more unobtrusive option might be interesting. I'd like to give at least some adblocking to friends and family. For them manually installing would be to difficult and might lead to dangerous behavior (install everything from everywhere as people do it in Microsoft Windows). Some would be irritated or unsettled by too frequent notifications about new releases. If there were only 3-4 new versions a year that might work for them. These people don't need perfect filtering. Some filtering is better than no filtering at all. So for them it wouldn't be a problem if their "long-term-release" had some holes in the firewall.  Adblocking with AdAway etc. is not an option for those relatives because I don't think regular users should have their phone rooted.

**Comment by M66B** [comment]
Actually I can control while releasing if there will be an update notification (independent of stable/beta/alpha version) and if there is an increased risk of bugs, there will be no update notification. So, don't worry to much about this.

Currently there is a new feature in development, which explains the increased number of updates, but this will soon be a thing of the past.
