### ISSUE TITLE
feature request: redirect to https for supported websites

### ISSUE THREAD

**Issue by Harish1n1ly** [M66B/NetGuard#477]
As netguard now supports domain-level adblocking, I was wondering if it can emulate the functionality of [HTTPS Everywhere](https://www.eff.org/https-everywhere) browser extensions developed by [EFF](https://www.eff.org). This is an essential feature but currently unavailable in mobile platforms.

. [HTTPS-Everywhere source](https://github.com/EFForg/https-everywhere) . [Redirection Rules](https://github.com/EFForg/https-everywhere/tree/master/src/chrome/content/rules) .

**Comment by licaon-kter** [comment]
You know you can install that addon in Firefox for Android, right?

**Comment by M66B** [comment]
In theory this is possible, but since this is already possible in some Android browsers, I see no reason to put effort into this.
