### ISSUE TITLE
Netguard not blockable since v2.38

### ISSUE THREAD

**Issue by gthbbr** [M66B/NetGuard#478]
I've just updated from 2.32 (f-droid) to 2.38 (playstore, because f-droid said other signature) and now there is no Netguard in the app list of Netguard anymore. Why should there be no possibility to see and control what Netguard does itself? 

In my case I blocked Netguard and it worked perfectly. Apps like Firefox tried to connect via the Netguard UID (at least what the protocol is saying). Please let the users decide, you could implement a warning, that host list download etc isn't working anymore afterwards. 

Thanks in advance.

**Comment by licaon-kter** [comment]
As expected: https://github.com/M66B/NetGuard/issues/461#issuecomment-233187041

Not sure why you would switch from F-Droid to Google Play store?!

**Comment by gthbbr** [comment]
I'm Pro User and didn't want to set up everything again, just because there is a different signature error. So I tried with gplay and it worked. So do I understand right, that this is just an issue with the play version. Then I'll have to update the hard way...

**Comment by licaon-kter** [comment]
Not an issue, intended behaviour.

Also, both Github and Google Play store have the same signature. F-Droid signature is of course  different.

You know you can Export and then Import your settings, right?
