### ISSUE TITLE
Can you add a different icon for status bar disabled state?

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#68]
A different shield, one with a line cutting it?

**Comment by M66B** [comment]
A different icon is possible, but it has to be 'flat', meaning monochrome.
IMHO the current icon is okay, but maybe you have a better proposal?

**Comment by licaon-kter** [comment]
Monocrome is ok, feature a diagonal black line across it maybe?

**Comment by M66B** [comment]
Test version: https://github.com/M66B/NetGuard/releases/tag/0.17

**Comment by M66B** [comment]
I am planning to use this icon for "off":
https://www.google.com/design/icons/#ic_do_not_disturb_alt

**Comment by M66B** [comment]
Other suggestions are welcome.

**Comment by licaon-kter** [comment]
That would look odd when you use "no disturb" though.

These would work (providing that you change it in the notification too):
* https://www.google.com/design/icons/#ic_highlight_off
* https://www.google.com/design/icons/#ic_error_outline
* https://www.google.com/design/icons/#ic_cancel

or

My rough editing (just for 1): https://imgur.com/a/GUGw7

**Comment by licaon-kter** [comment]
It was slow to react/sync with the app for on/off and that's its main function I guess, since the VPN key serves as a notice that NetGuard is working.
