### ISSUE TITLE
Can't install app on the playstore with netguard enabled :/

### ISSUE THREAD

**Issue by LifeIsStrange** [M66B/NetGuard#70]
I have Allowed the wifi and Mobile data for the playstore but I can't install apps, I have enabled the blocking of system apps. I'm on a oneplus one with cyanogenmod Android 5.1.1
Your app is really awesome, thanks !!

**Comment by licaon-kter** [comment]
You need these allowed I guess:
* com.google.android.gms
* com.android.vending

**Comment by LifeIsStrange** [comment]
I have Allowed all of this and still don't work :/
But my downloads on Firefox and f-droid still work

**Comment by LifeIsStrange** [comment]
I have find ! We need to enable com.android.providers.downloads =) 
It work yet with allow when device in use 
I think you should allow by default com.android.providers.downloads and com.google.android.gms because everybody body use and need the playstore. 
Also we don't need com.google.android.gsf and 
com.google.android.gsf.login
com.google.android.gsf.login because the playstore still work without

**Comment by licaon-kter** [comment]
Yes, I tested in the mean time and reached the same conclusion. :)

As for _"everybody body use and need the playstore"_ that's debateable, I'd vote for no defaults.

**Comment by LifeIsStrange** [comment]
"everybody body use and need the playstore" that's debateable" i'm absolutely agree, we can use f-droid+ aptoide instead BUT we need to think for the majority, for the mass and actually and for probably forever use what it is by default and by default it's Google play store, so people will use your app and don't understund why the Google play don't work, they will panic and uninstall your app because their are not curious. 
So for the good of the majority I think that Allowed by default is a necessity.

**Comment by LifeIsStrange** [comment]
But I'm questionning, Google play is before to be an application, is a website, so why it doesn't exist an open source Google play application based on the website with à reworked Ui and better perf because in the client side ? 
An application like https://github.com/theScrabi/NewPipe which is an open source YouTube based application like the Google proprietary application. 
An Google play store open source application will be a revolution !! 
this youtube application not need Google play service and is more powerfull than the Google YouTube app (you can easyly download music, video, play in background, etc)

**Comment by licaon-kter** [comment]
Or, if @M66B can pull it off, only the PlayStore build should have them.

I for one, having PlayStore update on me in background all by itself on a no Google account device just because I forgot the Wi-Fi enabled when I rebooted felt rather wrong. ( yes, AFWall+ did start but a bit later in the boot process )

I also did this PR: https://github.com/M66B/NetGuard/pull/72 which should help noob alike, if merged.

**Comment by LifeIsStrange** [comment]
Oh thanks !! It's look like really promising

**Comment by M66B** [comment]
I think adding default rules for the Play store is not a good idea:

* Manage system application is meant for expert users (next versions will indicate this more clearly)
* Privacy aware people may want to have the Play store blocked by default
* Default rules are for exceptional cases, like always allowing a remote wipe
