### ISSUE TITLE
[Feature request] Add the ability to block network for app on the background. 

### ISSUE THREAD

**Issue by LifeIsStrange** [M66B/NetGuard#71]
A lot of app are on the background and use network for spying (service Google play for example) so it will be a really good thing to give the ability to block network for background :)

**Comment by licaon-kter** [comment]
Click on the down arrow on the left side of an app name, and only check _"Allow when device in use"_ but DON'T click on the network icons, so they are red (blocked). The little human icon will appear for that app.

**Comment by LifeIsStrange** [comment]
Oh amazing ! Thanks so much
