### ISSUE TITLE
Show state indicators always

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#82]
i don't see the gain to have them disabled anyway.

Remove this setting, keep indicators always on but add a tooltip on touching them with the legend that explains what they mean.

**Comment by M66B** [comment]
The state indicators are mainly meant for debugging purposes and for expert users.
Most users will not be interested in this, since it adds nothing in terms of functions and will only be a distraction and raise questions what the icons mean.

**Comment by licaon-kter** [comment]
My take, it adds to the safety feeling that it's working, and that it protects this and that.
The tooltip should help with the questions.

**Comment by licaon-kter** [comment]
Ok, another thing, don't show them if no network is currently connected.
Right now they show *the last active* network type.
