### ISSUE TITLE
Rules for current active application

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#87]
Consider detecting the active application like this:
http://stackoverflow.com/questions/3873659/android-how-can-i-get-the-current-foreground-activity-from-a-service/27642535#27642535

**Comment by licaon-kter** [comment]
Please don't use Accesibilty, [this bug](https://code.google.com/p/android/issues/detail?id=79309) is rather dumb, sad and makes things insecure all over.
I can repro it with Greenify.

**Comment by M66B** [comment]
There is one alternative:
http://stackoverflow.com/questions/24590533/how-to-get-recent-tasks-on-android-l/26885469#26885469

But unfortunately this requires user approval as well.

Basically there is no way on recent Android versions anymore to determine the current foreground application without disadvantages.

**Comment by licaon-kter** [comment]
User approval is way better, compared to that.

**Comment by M66B** [comment]
True, but novice users will not always understand this, also resulting in unfair negative reviews.
And maybe they are even right, because things should simply be simple.

**Comment by licaon-kter** [comment]
It depend on how that works, any other app that does this already for us to test the whole set/agree workflow?

**Comment by M66B** [comment]
It is a kind of ugly, the user needs to be directed to an Android settings screen, find the correct application and enable usage data access on a sub screen.

To open this settings screen:
```
adb shell am start -a "android.settings.USAGE_ACCESS_SETTINGS"
```

**Comment by M66B** [comment]
I am closing this feature request, since there is no way to implement this in a nice way.
