### ISSUE TITLE
Bug after translation

### ISSUE THREAD

**Issue by Ivan4537** [M66B/NetGuard#89]
M66B, hello, I translated your app to Russian language.
https://drive.google.com/file/d/0BxFZ1q9evk3-YjFNcy02UWREblE/view

I noticed a bug. After its translation into Russian of the application menu disappears button "Invite". Don't know what it involves.

**Comment by licaon-kter** [comment]
Invite button needs PlayStore/Services active, do you have them?

**Comment by Ivan4537** [comment]
Yes. Until I translated into Russian - the button was.

**Comment by M66B** [comment]
Invites (and donations) will work only in versions I have built and signed with my private key, so this is normal.

**Comment by M66B** [comment]
Actually this is a Google requirement, which the code of NetGuard takes care of. Google checks the signature's fingerprint and will report an error if it doesn't match with the signature of the application in the Play store or as registered in the developers console.

**Comment by Ivan4537** [comment]
Thank you! Got it!
