### ISSUE TITLE
PIN protection

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#92]
Requested on Play store: "*Please add pin-protection for deactivating it:)*"

**Comment by licaon-kter** [comment]
Sound good, PIN, password, pattern, what can you implement?

**Comment by M66B** [comment]
Reference: [createConfirmDeviceCredentialIntent](http://developer.android.com/reference/android/app/KeyguardManager.html#createConfirmDeviceCredentialIntent(java.lang.CharSequence, java.lang.CharSequence))

**Comment by licaon-kter** [comment]
Can you ask for credentials again on "disable verify credentials" ?

**Comment by M66B** [comment]
Everything is possible, but you will need to verify to open the application already and if you don't verify (cancel) all settings are disabled. Use 'back' to close the application if you are done and everything should be safe.

**Comment by licaon-kter** [comment]
Using back or task manager -> close, yes.
But not when using home ( switch to launcher ).

**Comment by M66B** [comment]
Yes, that is the same as in my tests.
You need to explicitly close the activity for the credentials to be verified again.
There is no simply way around this, but I will try to think something out.

**Comment by licaon-kter** [comment]
This needs to be reconsidered since [this](https://github.com/M66B/NetGuard/issues/125) exists.
